## 04. scratchpad

### 1. Data Upload

In [1]:
import pandas as pd
import os
from collections import defaultdict, Counter
import re
import time
from tqdm.notebook import tqdm
import copy

In [2]:
def upload_to_dataframe(root, files, num_lines):
    path_eng, path_pol = [root+f for f in files]
    data = defaultdict(list)
    
    with open (path_eng, encoding="utf_8") as f_eng, open (path_pol, encoding="utf_8") as f_pol:
        for _ in range(num_lines):
            data['eng_text'].append(f_eng.readline().strip())
            data['pol_text'].append(f_pol.readline().strip())
    return pd.DataFrame(data)

In [3]:
root = "../data/opus_opensub/en-pl.txt/"
files = ('OpenSubtitles.en-pl.en', '/OpenSubtitles.en-pl.pl')
df = upload_to_dataframe(root, files, 600000)

### 2. EDA & Sanitazation

#### 2.1 English Non-Ascii Sentences

In [4]:
def nonascii_list(df_series, is_pol):
    if is_pol:
        pl_chars = set("ąęćłńóśźżĄĘĆŁŃÓŚŹŻ")
        requir = lambda x: x.isascii() or x in pl_chars
    else:
        requir = lambda x: x.isascii()
        
    text_all = ''.join(df_series)
    unique_dct = {x for x in text_all if not requir(x)}
    return sorted(list(unique_dct))

In [5]:
print(nonascii_list(df['eng_text'], False))

['\x80', '\x81', '\x82', '\x83', '\x84', '\x85', '\x88', '\x8b', '\x8c', '\x8e', '\x8f', '\x91', '\x94', '\x96', '\x98', '\x99', '\x9c', '\x9d', '\xa0', '¡', '¢', '£', '¤', '¥', '¦', '§', '¨', '©', 'ª', '¬', '\xad', '°', '±', '²', '³', '´', 'µ', '¶', '·', '¸', '¹', 'º', '¼', '½', '¾', '¿', 'Á', 'Â', 'Ã', 'Ä', 'Å', 'Ç', 'É', 'Ê', 'Ì', 'Ï', 'Ð', 'Ñ', 'Ô', 'Ö', 'Ø', 'Ü', 'Ý', 'Þ', 'ß', 'à', 'á', 'â', 'ã', 'ä', 'å', 'ç', 'è', 'é', 'ê', 'ì', 'í', 'î', 'ï', 'ð', 'ñ', 'ó', 'ô', 'ö', 'ù', 'ú', 'û', 'ü', 'ý', 'þ', 'Ă', 'ď', 'ę', 'Ł', 'ń', 'ő', 'œ', 'ś', 'Š', 'š', 'Ј', 'С', 'й', '،', 'أ', 'إ', 'ئ', 'ا', 'ب', 'ة', 'ت', 'ح', 'ر', 'س', 'ش', 'ع', 'غ', 'ف', 'ك', 'ل', 'م', 'ن', 'و', 'ي', 'َ', 'ُ', 'ِ', 'ّ', 'ْ', '\u200b', '‒', '–', '—', '‚', '€', '™', '─', '☻', '♥', '♪', '慹', '拢', '檛', '鈥', 'ﬁ', 'ﬂ']

In [6]:
is_ascii = lambda text: text.isascii()
maska = df['eng_text'].apply(is_ascii)
df_non_ascii = df[~maska].copy().reset_index(drop=True)
print(df_non_ascii.shape)
df_non_ascii.head()

(4595, 2)

,eng_text,pol_text
0,¿You had never seen A crab suedes? Them there ...,- Nigdy wcześniej nie widziałaś raków?
1,"He hears ¿, where you live?",Nigdy wcześniej nie byłam w lesie.
2,"Boys ¿, they are there?",Jesteście tam chłopaki?
3,- Te atrapé. - No es gracioso. Your he catches...,- Ale twoje mina była.
4,"Your also ¿, it is not like that?","- Tak, niezła jest"

In [7]:
df_2 = df[maska].reset_index(drop=True)
df_2.shape

(595405, 2)

#### 2.2 Polish Non-Ascii Sentences

In [8]:
pl_chars = set("ąęćłńóśźżĄĘĆŁŃÓŚŹŻ")
requir = lambda let: not let.isascii() and let not in pl_chars
maska = df_2['pol_text'].apply(lambda snt: any([requir(let) for let in snt]))
df_non_ascii = df_2[maska].copy().reset_index(drop=True)
print(df_non_ascii.shape)
df_non_ascii.sample(10)

(1227, 2)

,eng_text,pol_text
1195,On the avenue,¶ Na alei
349,- I knew it.,Maréchal nie mógł się na to zdobyć.
11,"Yoko, a famous singer, had married Koichiro an...",Słynna śpiewaczka Yôko poślubiła Kôichirô i po...
484,I see you had a little publicity...,"Widze, že masz juž reklame."
619,I've been told the whole thing is his idea to ...,"Slyszalem, že wymyšlil szwindel, by sie wzboga..."
142,"My, you ought to see how little Emily's grown.","Ojej, powinieneś zobaczyć jak ​​mała Emily uro..."
88,since you have at last renounced the errors of...,"Nie spotka cię ekskomunika, albowiem przyznała..."
379,- I don't know... Maybe.,- Nie wiem... može.
578,If there's money in each one...,Ješli w každym sa pieniadze?
971,"Hamburg, GroBe Bleichen 1 5.","Hamburg, Große Bleichen 15."

In [9]:
df_3 = df_2[~maska].reset_index(drop=True)
print(df_3.shape)
df_3.sample(5)

(594178, 2)

,eng_text,pol_text
243257,No.,Niestety.
20712,I'll bet he stole those boots!,"Założę się, że ukradł te buty!"
342049,THERE ARE TAX DEDUCTIONS. THERE HAD NEVER BEEN...,Coś nie z tej ziemi.
278998,I'm freezing.,Zimno mi.
196034,"And whatever they've done to him, no matter wh...","I cokolwiek z nim zrobią, nie ważnie gdzie ter..."

In [10]:
print(nonascii_list(df_3['eng_text'], False))
print(nonascii_list(df_3['pol_text'], True))

[]
[]

In [11]:
df_3.iloc[74182]['eng_text']

'The next time I...'

In [12]:
df_3.iloc[74182]['pol_text']

'Następnym razem...'

#### 2.3 Short Or Empty Examples

In [13]:
mask1 = df_3['eng_text'].str.len() >= 3
mask2 = df_3['pol_text'].str.len() >= 3

In [14]:
df_4 = df_3[mask1 & mask2].reset_index(drop=True)
df_4.head()

,eng_text,pol_text
0,"Previously on ""The Blacklist""...",/W poprzednich odcinkach: /
1,- You want to call your daddy?,- Chcesz zadzwonić do taty?
2,"- Yeah, I want to tell him I'm okay.","- Tak, powiem, że wszystko w porządku."
3,Okay.,Dobrze.
4,Lizzy... Be careful of your husband.,"Lizzy, uważaj na męża."

In [15]:
df_4.shape

(593894, 2)

#### 2.4 Dialog like sentences [starts with - ]

In [16]:
is_dialog = lambda snt: bool(re.match(r"^ *- *", snt))
mask = df_4['eng_text'].apply(is_dialog) | df_4['pol_text'].apply(is_dialog)
df_dialogs = df_4[mask].copy().reset_index(drop=True)
df_dialogs.head()

,eng_text,pol_text
0,- You want to call your daddy?,- Chcesz zadzwonić do taty?
1,"- Yeah, I want to tell him I'm okay.","- Tak, powiem, że wszystko w porządku."
2,- 45 seconds.,Szybciej! 45 sekund.
3,It's okay. It's okay. It's okay.,- Już dobrze.
4,It's okay. You're okay. You're okay.,- Odpoczywaj.

In [17]:
def fix_dialog(snt):
    return re.sub(r"^ *- *", "", snt)

df_4['eng_text'] = df_4['eng_text'].apply(fix_dialog).reset_index(drop=True)
df_4['pol_text'] = df_4['pol_text'].apply(fix_dialog).reset_index(drop=True)
df_4.sample(5)

,eng_text,pol_text
32447,Is anyone there?,Czy jest ktoś?
265856,Uh-uh. I should've told you first that I love ya.,"Od razu powinienem ci powiedzieć, że kocham cię."
215180,"No, I don't go no place much.","Nie, nie chodze ma miejsca duzo."
432755,Don't kid me.,Nie oszukuj mnie.
378859,I'm Professor Siletsky.,Jestem profesor Silecki.

#### 2.5 Broken Dialog like sentences [somehwere has -]

# Do naprawy (lepszy re przed tokenziacja)

In [18]:
broken_dialog = lambda snt: bool(re.match(r".* +- +.*", snt))
mask1 = df_4['eng_text'].apply(broken_dialog)
mask2 = df_4['pol_text'].apply(broken_dialog)

In [19]:
df_4[mask1 | mask2].sample(5)

,eng_text,pol_text
5796,I hear in my head the judge's voice as he pron...,"Słyszę w mojej głowie wyrok sądu, który stwier..."
195540,"Hey, Rock! - So long, Rocky!","Na razie, Rocky!"
285559,"""Or What the Kitchen Maid Saw Through the Keyh...","""Albo to, co podejrzała kucharka."" Koniec cytatu."
288557,Mademoiselle will have lunch with me.,Zechce pani zjeść obiad razem ze mną? - Nie mo...
540943,About what?,Myślę o... - Powiedz!

In [20]:
df_5 = df_4[~mask1 & ~mask2].reset_index(drop=True)

In [21]:
broken_dialog = lambda snt: bool(re.match(r".*-.*", snt))

In [22]:
df_5.sample(5)

,eng_text,pol_text
301312,No!,Nie!
179544,"Fifty dollars, a hundred dollars. A thousand d...","50 dolarów, 100, 1000 góra."
291552,"Here we are, good strong tea.",O mamy herbatkę.
59836,Get me some too.,Dla mnie też.
474245,She doesn't know anybody here.,Nikogo tu nie zna.

#### 2.6 Different Last Case

In [23]:
mask = df_5['eng_text'].str[-1] != df_5['pol_text'].str[-1]
mask.sum()

57558

In [24]:
df_6 = df_5[~mask].reset_index(drop=True)

#### 2.7 Text length difference

In [25]:
mask = df_6['eng_text'].str.split
df_6['len_ratio'] = df_6['eng_text'].str.split().str.len() / df_6['pol_text'].str.split().str.len()
df_6.head()

,eng_text,pol_text,len_ratio
0,You want to call your daddy?,Chcesz zadzwonić do taty?,1.500000
1,"Yeah, I want to tell him I'm okay.","Tak, powiem, że wszystko w porządku.",1.333333
2,Okay.,Dobrze.,1.000000
3,Lizzy... Be careful of your husband.,"Lizzy, uważaj na męża.",1.500000
4,I can only lead you to the truth.,/Mogę naprowadzić cię na prawdę.,1.600000

In [26]:
thres_left = df_6["len_ratio"].quantile(0.05)
thres_right = df_6["len_ratio"].quantile(0.95)
thres_left, thres_right

(0.75, 2.5)

In [27]:
mask = (df_6["len_ratio"] >= thres_left) & (df_6["len_ratio"] <= thres_right)
mask.sum()

472209

In [28]:
df_7 = df_6[mask].reset_index(drop=True)
df_7.sample(5)

,eng_text,pol_text,len_ratio
133186,"But you see, I've never had the advantages tha...","Ale widzisz, nigdy nie miałem tego co inni mal...",1.25
102630,"But, madame, the bank would not be interested ...","Ale, proszę pani, bank nie jest zainteresowany...",1.40
75593,Did he tell you where he was going?,Powiedział dokąd się wybiera?,2.00
448097,"She wanted to break the rules, like cigarettes...","Łamała zasady, zaczęła palić, używać perfum, s...",1.40
469816,All I ask is for you to let me love you.,"Jedyne o co cię proszę, to abyś pozwolił mi ci...",1.00

In [29]:
df_7.sample(5)

,eng_text,pol_text,len_ratio
328287,What house?,Gdzie?,2.000000
449604,His car's out there in the rain.,Jego wóz tam stoi.,1.750000
18686,Christian Thompson.,Christian Thompson.,1.000000
20339,"For three days and nights, I've had no other t...","Trzy dni i noce myślałem tylko o tym, jak cię ...",1.272727
29424,or a traitor.,Lub zdrajca.,1.500000

#### 2.8 Sentences starting with * fix

In [30]:
fix_star = lambda snt: re.sub(r"^ *[*].*", "", snt)
df_7['eng_text'] = df_7['eng_text'].apply(fix_star)
df_7['pol_text'] = df_7['pol_text'].apply(fix_star)

#### 2.9 Action Comments

In [31]:
def mask_distinct(df, col1, col2, chars):
    chars_escaped = "".join(re.escape(c) for c in chars)
    templ = f"[{chars_escaped}]"

    m1 = df[col1].str.contains(templ, regex=True, na=False)
    m2 = df[col2].str.contains(templ, regex=True, na=False)

    return m1 ^ m2

chars = '[]()/\*+#$"️'
mask = mask_distinct(df_7, "eng_text", "pol_text", chars)

df_8 = df_7[~mask].reset_index(drop=True)
df_8.shape

(467550, 3)

In [32]:
df_8.sample(5)

,eng_text,pol_text,len_ratio
284414,"All right, back it up!",Cofnijcie się!,2.500000
110487,"You may be right, Calamity.","Może masz rację, Calamity.",1.250000
65780,"Sir, you will address Her Highness by her corr...",Proszę zwracać się do Jej Wysokości po właściw...,1.111111
103889,I want to confess!,Chcę się przyznać!,1.333333
416846,Nobody knows me around here.,Nikt mnie tu nie zna.,1.000000

#### 2.10  " ` " ---> " ' " & del " ~ "

In [33]:
wanted_case = '`'
mask = df_8["eng_text"].apply(lambda x: wanted_case in x)
df_8[mask]

,eng_text,pol_text,len_ratio
214145,"Revolution had broken out, her diplomats sued ...","Rewolucja na tyłach frontu, dąży do zawarcia p...",1.277778
214152,We`ll examine it.,Zbadajmy go.,1.500000
214157,What do you think you`re doing?,Wstawaj! Co ty robisz?,1.500000
214161,Where`s your hand grenade?,Gdzie masz swój granat?,1.000000
214163,Let `em have it!,Niech je poczują!,1.333333
...,...,...,...
214943,We don`t want to hate one another.,Bez nienawiści ani pogardy.,1.750000
214944,There`s room for everyone.,Każdy ma swe miejsce.,1.000000
214947,"Greed has poisoned men`s souls, has barricaded...","Chciwość zatruła nasze dusze, wzniosła mury ni...",1.333333
214963,You don`t hate.,Przestańcie nienawidzieć.,1.500000
214965,"Soldiers, don`t fight for slavery, fight for l...","Nie walczcie o niewolę, lecz o wolność!",1.142857

In [34]:
df_8["eng_text"] = df_8["eng_text"].str.replace("`", "'", regex=False)
df_8["pol_text"] = df_8["pol_text"].str.replace("`", "'", regex=False)

In [35]:
df_8["eng_text"] = df_8["eng_text"].str.replace("~", "", regex=False)
df_8["pol_text"] = df_8["pol_text"].str.replace("~", "", regex=False)

#### 2.11 Del rows with specific case

In [36]:
def del_row_with_char(df, eng_col, pol_col, chars):
    df_proc = df.copy()
    for char in chars:
        mask1 = df_proc[eng_col].apply(lambda x: char in x)
        mask2 = df_proc[pol_col].apply(lambda x: char in x)
        df_proc = df_proc[~(mask1 | mask2)].reset_index(drop=True)
    return df_proc
    

chars = "=+*@#;|_}{"
df_9 = del_row_with_char(df_8, "eng_text", "pol_text", chars)

#### 2.12 Del rows with dialog -

In [37]:
mask1 = df_9["eng_text"].apply(lambda x: bool(re.search(r' +-[^ ]+', x)))
mask2 = df_9["pol_text"].apply(lambda x: bool(re.search(r' +-[^ ]+', x)))
df_data = df_9[~(mask1 | mask2)].reset_index(drop=True)

#### 3. Data Tokenization

In [38]:
uniq_cases = set("".join(df_data["eng_text"].astype(str)))
tab1 = sorted(list(uniq_cases), reverse=True)
print(tab1)

['z', 'y', 'x', 'w', 'v', 'u', 't', 's', 'r', 'q', 'p', 'o', 'n', 'm', 'l', 'k', 'j', 'i', 'h', 'g', 'f', 'e', 'd', 'c', 'b', 'a', ']', '[', 'Z', 'Y', 'X', 'W', 'V', 'U', 'T', 'S', 'R', 'Q', 'P', 'O', 'N', 'M', 'L', 'K', 'J', 'I', 'H', 'G', 'F', 'E', 'D', 'C', 'B', 'A', '?', ':', '9', '8', '7', '6', '5', '4', '3', '2', '1', '0', '/', '.', '-', ',', ')', '(', "'", '%', '$', '"', '!', ' ']

In [39]:
uniq_cases = set("".join(df_data["pol_text"].astype(str)))
tab2 = sorted(list(uniq_cases), reverse=True)
print(tab2)

['ż', 'Ż', 'ź', 'Ź', 'ś', 'Ś', 'ń', 'Ń', 'ł', 'Ł', 'ę', 'Ę', 'ć', 'Ć', 'ą', 'Ą', 'ó', 'Ó', 'z', 'y', 'x', 'w', 'v', 'u', 't', 's', 'r', 'q', 'p', 'o', 'n', 'm', 'l', 'k', 'j', 'i', 'h', 'g', 'f', 'e', 'd', 'c', 'b', 'a', ']', '[', 'Z', 'Y', 'X', 'W', 'V', 'U', 'T', 'S', 'R', 'Q', 'P', 'O', 'N', 'M', 'L', 'K', 'J', 'I', 'H', 'G', 'F', 'E', 'D', 'C', 'B', 'A', '?', ':', '9', '8', '7', '6', '5', '4', '3', '2', '1', '0', '/', '.', '-', ',', ')', '(', "'", '%', '$', '"', '!', ' ']

In [40]:
def tokenize_eng(snt):
    snt = snt.lower()
    snt = re.sub("(?<! )'(?! )", r" '", snt)
    snt = re.sub(r"""([\]?:)\[(/\.\-,%\$"!])""", r" \1 ", snt)
    snt = re.sub(r"\s+", " ", snt).strip()
    return re.split(r'\s+', snt.strip())

In [41]:
def tokenize_pol(snt):
    snt = snt.lower()
    snt = re.sub(r"""([\]?:)\[(/\.\-,%\$"!])""", r" \1 ", snt)
    snt = re.sub(r"\s+", " ", snt).strip()
    return re.split(r'\s+', snt.strip())

In [42]:
df_data = df_data.drop(['len_ratio'], axis=1)

#### 3.1 Splitting and trimming on quantile

In [43]:
df_data['eng_split'] = df_data['eng_text'].apply(tokenize_eng)
df_data['pol_split'] = df_data['pol_text'].apply(tokenize_pol)
df_data.sample(10)

,eng_text,pol_text,eng_split,pol_split
428269,I don't know the man.,Nie znam go.,"[i, don, 't, know, the, man, .]","[nie, znam, go, .]"
351732,Nobody was proud of me.,Nikt nie był ze mnie dumny.,"[nobody, was, proud, of, me, .]","[nikt, nie, był, ze, mnie, dumny, .]"
38069,Yes. My mother was Egyptian.,Moja mama była Egipcjanką.,"[yes, ., my, mother, was, egyptian, .]","[moja, mama, była, egipcjanką, .]"
278164,I'll drop by in the morning.,"Spadam już, bo się rozwidnia.","[i, 'll, drop, by, in, the, morning, .]","[spadam, już, ,, bo, się, rozwidnia, .]"
359066,Come on!,Chodźcie!,"[come, on, !]","[chodźcie, !]"
11235,"Well, get a load of this, big boy.","Dobra, posłuchaj mnie, grubasie.","[well, ,, get, a, load, of, this, ,, big, boy, .]","[dobra, ,, posłuchaj, mnie, ,, grubasie, .]"
15414,A dagger.,Sztylet.,"[a, dagger, .]","[sztylet, .]"
194953,Sure.,Pewnie.,"[sure, .]","[pewnie, .]"
237836,"Good morning, Miss Bragg.","Dzień dobry, panno Bragg.","[good, morning, ,, miss, bragg, .]","[dzień, dobry, ,, panno, bragg, .]"
348275,You're with me.,Jesteś ze mną.,"[you, 're, with, me, .]","[jesteś, ze, mną, .]"

# TODO - zamien lt na It

In [44]:
df_data[df_data['eng_split'].apply(lambda x: 'lt' in x)]

,eng_text,pol_text,eng_split,pol_split
9781,lt was the only thing they had.,"To było jedyne, jakie mieli wolne.","[lt, was, the, only, thing, they, had, .]","[to, było, jedyne, ,, jakie, mieli, wolne, .]"
9811,lt was your fault you put the thing under the ...,"To twoja wina, bo położyłeś go pod łóżko.","[lt, was, your, fault, you, put, the, thing, u...","[to, twoja, wina, ,, bo, położyłeś, go, pod, ł..."
10953,Beat it. lt's a bull!,"Uciekajmy, to gliniarz!","[beat, it, ., lt, 's, a, bull, !]","[uciekajmy, ,, to, gliniarz, !]"
10957,lt went in your pocket.,Wpadł ci do kieszeni.,"[lt, went, in, your, pocket, .]","[wpadł, ci, do, kieszeni, .]"
10981,lt caught in your pocket.,On utknął w kieszeni...,"[lt, caught, in, your, pocket, .]","[on, utknął, w, kieszeni, ., ., .]"
...,...,...,...,...
412362,Okay. lt's your f uneral.,Dobrze. To twój cyrk.,"[okay, ., lt, 's, your, f, uneral, .]","[dobrze, ., to, twój, cyrk, .]"
412366,lt's important.,To ważne.,"[lt, 's, important, .]","[to, ważne, .]"
412439,"Maybe, maybe not. lt's a pretty story.","Może tak, może nie. Niezła historia.","[maybe, ,, maybe, not, ., lt, 's, a, pretty, s...","[może, tak, ,, może, nie, ., niezła, historia, .]"
412454,lt's unlocked.,Jest otwarta.,"[lt, 's, unlocked, .]","[jest, otwarta, .]"
412482,lt's in my pocket.,Jest w mojej kieszeni.,"[lt, 's, in, my, pocket, .]","[jest, w, mojej, kieszeni, .]"

In [45]:
thres1 = df_data['eng_split'].str.len().quantile(0.99)
mask1 = df_data['eng_split'].str.len() > thres1

thres2 = df_data['pol_split'].str.len().quantile(0.99)
mask2 = df_data['pol_split'].str.len() > thres2
print(mask1.sum(), mask2.sum(), (mask1 | mask2).sum())

df_data = df_data[~(mask1 | mask2)].reset_index(drop=True)

4113 3960 5510

#### 3.2 BPE Init. Uniq_freq & Rozklad chars

In [46]:
uniq_freq_eng = Counter(df_data['eng_split'].explode())
uniq_freq_pol = Counter(df_data['pol_split'].explode())

In [47]:
len(uniq_freq_eng), len(uniq_freq_pol)

(40087, 113603)

In [48]:
char_factor = lambda word: [x for x in word] + ['_']
vocab_chars_eng = [[char_factor(k), v] for k, v in uniq_freq_eng.most_common()]
vocab_chars_pol = [[char_factor(k), v] for k, v in uniq_freq_pol.most_common()]
print(len(vocab_chars_eng), vocab_chars_eng[:5], '\n')
print(len(vocab_chars_pol), vocab_chars_pol[:5])

40087 [[['.', '_'], 435802], [[',', '_'], 177291], [['y', 'o', 'u', '_'], 134548], [['i', '_'], 122767], [['t', 'h', 'e', '_'], 89859]]

113603 [[['.', '_'], 413780], [[',', '_'], 183948], [['?', '_'], 83444], [['n', 'i', 'e', '_'], 82694], [['t', 'o', '_'], 53190]]

#### 3.3 BPE Tokenizer

In [72]:
class BPETokenizer_5():
    def __init__(self, vocab_chrs, vocab_pairs, vocab_size, is_tgt):
        self.vocab_chrs = vocab_chrs
        self.vocab_pairs = vocab_pairs
        self.vocab_size = vocab_size
        self.pair_counts = self.pair_counts_init(vocab_pairs)
        self.vocab = self.vocab_init(vocab_chrs, is_tgt)
        self.base_size = len(self.vocab)

    def vocab_init(self, vocab_chrs, is_tgt):
        vocab = {'<pad>': 0, '<unk>': 1, '<eos>': 2, '_': 3}
        if is_tgt:
            vocab['<bos>'] = 4
            
        uniq_toks = {tok for toks, _ in vocab_chrs for tok in toks}
        uniq_toks.remove('_')
        for i, tok in enumerate(uniq_toks, len(vocab)):
            vocab[tok] = i
        return vocab

    def pair_counts_init(self, vocab_pairs):
        pair_counts = defaultdict(int)
        for toks, freq in vocab_pairs:
            for pair in toks:
                pair_counts[pair] += freq
        return pair_counts

    def train_bpe(self):
        for i in tqdm(range(self.base_size, self.vocab_size)):
            pair = self.most_common_pair()
            self.vocab[pair] = i
            self.replace_pairs(pair)

    def replace_pairs(self, pair):
        pair_con = f"{pair[0]}{pair[1]}"
        p_1, p_2 = map(re.escape, pair)
        
        for i in range(len(self.vocab_chrs)):
            if pair in self.vocab_pairs[i][0]:
                new_chr = re.sub(rf"(?<=\s){p_1}\s{p_2}(?=\s)", pair_con, f" {' '.join(self.vocab_chrs[i][0])} ").split()
                self.vocab_chrs[i][0] = new_chr
                self.update_pair_count(list(zip(new_chr, new_chr[1:])), i)
        self.pair_counts.pop(pair)

    def update_pair_count(self, new_pairs, i):
        old_pairs, val = self.vocab_pairs[i]
        for tup in old_pairs:
            self.pair_counts[tup] -= val  
        for tup in new_pairs:
            self.pair_counts[tup] += val
        self.vocab_pairs[i][0] = new_pairs
      
    def most_common_pair(self):
        return max(self.pair_counts, key=self.pair_counts.get)

In [109]:
vocab_test5 = [[char_factor(k), v] for k, v in uniq_freq_eng.most_common()]
pair_vocab5 = [[list(zip(tab, tab[1:])), v] for tab, v in vocab_test5]
tokenizer_test5 = BPETokenizer_5(vocab_test5, pair_vocab5, 8000, False)

t = time.time()
tokenizer_test5.train_bpe()
print(f"{time.time()-t:.2f} seconds")

  0%|          | 0/7945 [00:00<?, ?it/s]

169.12 seconds

#### 3.4 BPE Encoder propably should add to the BPE Class Later

In [145]:
tokenizer_test5.vocab_chrs[11500]

[['gi', 'll', 'ingham_'], 8]

In [122]:
dct_encoder = {"".join(k): v for k, v in tokenizer_test5.vocab.items()}
dct_encoder

{'<pad>': 0,
 '<unk>': 1,
 '<eos>': 2,
 '_': 3,
 'd': 4,
 'j': 5,
 '7': 6,
 't': 7,
 ':': 8,
 'f': 9,
 ']': 10,
 '-': 11,
 's': 12,
 '.': 13,
 '6': 14,
 '5': 15,
 'p': 16,
 'r': 17,
 '"': 18,
 '?': 19,
 'l': 20,
 'n': 21,
 ',': 22,
 ')': 23,
 "'": 24,
 '/': 25,
 '4': 26,
 'g': 27,
 'w': 28,
 '$': 29,
 'i': 30,
 'y': 31,
 '!': 32,
 'c': 33,
 'v': 34,
 '3': 35,
 '2': 36,
 'k': 37,
 'h': 38,
 'o': 39,
 'z': 40,
 'x': 41,
 '[': 42,
 'e': 43,
 'a': 44,
 'b': 45,
 'q': 46,
 '%': 47,
 '8': 48,
 'm': 49,
 '9': 50,
 'u': 51,
 '1': 52,
 '(': 53,
 '0': 54,
 'e_': 55,
 '._': 56,
 't_': 57,
 'th': 58,
 's_': 59,
 'ou': 60,
 'n_': 61,
 'd_': 62,
 ',_': 63,
 'er': 64,
 'y_': 65,
 'you': 66,
 'o_': 67,
 'in': 68,
 'you_': 69,
 'i_': 70,
 'an': 71,
 'l_': 72,
 'r_': 73,
 'the_': 74,
 'g_': 75,
 'at_': 76,
 '?_': 77,
 'a_': 78,
 'll_': 79,
 'to_': 80,
 'ing_': 81,
 'er_': 82,
 'ar': 83,
 'f_': 84,
 'it_': 85,
 'me_': 86,
 'on_': 87,
 'wh': 88,
 'm_': 89,
 'on': 90,
 'ow': 91,
 "'s_": 92,
 'is_': 93,
 've_': 94,
 'ea': 95,
 'or': 96,
 "'t_": 97,
 'ed_': 98,
 'k_': 99,
 'and_': 100,
 'ha': 101,
 'in_': 102,
 'st': 103,
 'en': 104,
 'that_': 105,
 'li': 106,
 'ow_': 107,
 'h_': 108,
 'ere_': 109,
 'en_': 110,
 'of_': 111,
 'wa': 112,
 'es_': 113,
 'or_': 114,
 'an_': 115,
 'he_': 116,
 'ri': 117,
 'wi': 118,
 'st_': 119,
 'gh': 120,
 'go': 121,
 '!_': 122,
 'et_': 123,
 're': 124,
 'se_': 125,
 'el': 126,
 'ti': 127,
 'what_': 128,
 'ght_': 129,
 'ke_': 130,
 'ma': 131,
 'now_': 132,
 'be': 133,
 'p_': 134,
 'co': 135,
 'ro': 136,
 'di': 137,
 're_': 138,
 'la': 139,
 'bu': 140,
 'for_': 141,
 'le_': 142,
 'we_': 143,
 'hi': 144,
 'the': 145,
 'no': 146,
 'lo': 147,
 'be_': 148,
 'ld_': 149,
 'out_': 150,
 'th_': 151,
 'tt': 152,
 'my_': 153,
 'si': 154,
 'ev': 155,
 'ell_': 156,
 'ce_': 157,
 'this_': 158,
 'sa': 159,
 'ta': 160,
 'your_': 161,
 'don_': 162,
 "'ll_": 163,
 'have_': 164,
 'ly_': 165,
 'all_': 166,
 'ra': 167,
 'do_': 168,
 'se': 169,
 'no_': 170,
 'are_': 171,
 'ca': 172,
 "'m_": 173,
 'one_': 174,
 'so': 175,
 'but_': 176,
 'can_': 177,
 'was_': 178,
 "'re_": 179,
 'thing_': 180,
 'with_': 181,
 'mi': 182,
 'un': 183,
 'not_': 184,
 'to': 185,
 'ch': 186,
 'ab': 187,
 'here_': 188,
 'le': 189,
 'su': 190,
 'ust_': 191,
 'me': 192,
 'get_': 193,
 'ck_': 194,
 'there_': 195,
 'know_': 196,
 'him_': 197,
 'sh': 198,
 'ss_': 199,
 'bo': 200,
 'ther_': 201,
 'ch_': 202,
 'al': 203,
 'well_': 204,
 'if_': 205,
 'ne': 206,
 'fi': 207,
 'go_': 208,
 'ould_': 209,
 'they_': 210,
 'yes_': 211,
 'do': 212,
 "'ve_": 213,
 'like_': 214,
 'thin': 215,
 'ry_': 216,
 'rea': 217,
 'come_': 218,
 'da': 219,
 'od_': 220,
 'right_': 221,
 'wan': 222,
 'te_': 223,
 'ba': 224,
 'so_': 225,
 'she_': 226,
 'po': 227,
 'about_': 228,
 'up_': 229,
 'ho': 230,
 'gi': 231,
 'fa': 232,
 'dn_': 233,
 'oh_': 234,
 'lea': 235,
 'will_': 236,
 'just_': 237,
 'see_': 238,
 'ni': 239,
 'ur': 240,
 'ts_': 241,
 'as_': 242,
 'for': 243,
 'mor': 244,
 'good_': 245,
 'ent_': 246,
 'man_': 247,
 'her_': 248,
 'dy_': 249,
 'got_': 250,
 'de': 251,
 'wor': 252,
 'how_': 253,
 'ever_': 254,
 'pa': 255,
 '"_': 256,
 'way_': 257,
 'own_': 258,
 'mo': 259,
 'oun': 260,
 'ver': 261,
 'loo': 262,
 'pp': 263,
 'w_': 264,
 'ga': 265,
 "'d_": 266,
 'ind_': 267,
 '-_': 268,
 'want_': 269,
 'king_': 270,
 'think_': 271,
 'why_': 272,
 'sp': 273,
 'some': 274,
 'his_': 275,
 'ter_': 276,
 'mr_': 277,
 'qu': 278,
 'ds_': 279,
 'ge_': 280,
 'gu': 281,
 'ys_': 282,
 'ck': 283,
 'ee': 284,
 'de_': 285,
 'going_': 286,
 'where_': 287,
 'did_': 288,
 'ru': 289,
 'ell': 290,
 'id_': 291,
 'ex': 292,
 'let_': 293,
 'fu': 294,
 'take_': 295,
 'ear': 296,
 'them_': 297,
 'ci': 298,
 'fro': 299,
 'ty_': 300,
 'been_': 301,
 'any': 302,
 'ear_': 303,
 'tter_': 304,
 'when_': 305,
 'from_': 306,
 'll': 307,
 'com': 308,
 'ers_': 309,
 'ong_': 310,
 'tell_': 311,
 'ge': 312,
 'mar': 313,
 'who_': 314,
 'sn_': 315,
 'mu': 316,
 'say_': 317,
 'ted_': 318,
 'us_': 319,
 'gh_': 320,
 'any_': 321,
 'tion_': 322,
 'ey_': 323,
 'time_': 324,
 'than': 325,
 'very_': 326,
 'con': 327,
 'back_': 328,
 'our_': 329,
 'sta': 330,
 'ttle_': 331,
 'cou': 332,
 'af': 333,
 'ine_': 334,
 'look_': 335,
 'ver_': 336,
 'of': 337,
 'mon': 338,
 'na': 339,
 'had_': 340,
 'ks_': 341,
 'sel': 342,
 'pe': 343,
 'ever': 344,
 'too_': 345,
 'op': 346,
 'ct': 347,
 'vi': 348,
 'pla': 349,
 'fe': 350,
 'cu': 351,
 'pro': 352,
 'would_': 353,
 'ran': 354,
 'ki': 355,
 'jo': 356,
 'ough_': 357,
 'never_': 358,
 'day_': 359,
 'bi': 360,
 'sti': 361,
 'pu': 362,
 'der': 363,
 'sh_': 364,
 'didn_': 365,
 'were_': 366,
 'sir_': 367,
 'pi': 368,
 'some_': 369,
 'little_': 370,
 'gs_': 371,
 'par': 372,
 'by_': 373,
 'ss': 374,
 'more_': 375,
 'mb': 376,
 'rs_': 377,
 'ound_': 378,
 'per': 379,
 'down_': 380,
 'then_': 381,
 'pre': 382,
 'ought_': 383,
 'plea': 384,
 'fe_': 385,
 'give_': 386,
 'son_': 387,
 'sure_': 388,
 'must_': 389,
 'ldn_': 390,
 'end_': 391,
 'make_': 392,
 'ble_': 393,
 'lly_': 394,
 'ter': 395,
 'self_': 396,
 'only_': 397,
 'te': 398,
 'tal': 399,
 'der_': 400,
 'men_': 401,
 'ting_': 402,
 'happ': 403,
 'could_': 404,
 'as': 405,
 'lu': 406,
 'tw': 407,
 'has_': 408,
 'other_': 409,
 'ying_': 410,
 'something_': 411,
 'car': 412,
 'thank_': 413,
 'al_': 414,
 'over_': 415,
 'body_': 416,
 'night_': 417,
 'ess_': 418,
 'ful_': 419,
 'won_': 420,
 'much_': 421,
 '0_': 422,
 'aga': 423,
 'ard_': 424,
 'use_': 425,
 'sor': 426,
 'ning_': 427,
 'tr': 428,
 'sto': 429,
 'c_': 430,
 'am_': 431,
 'please_': 432,
 'hea': 433,
 'qui': 434,
 'ct_': 435,
 'whi': 436,
 'hel': 437,
 'min': 438,
 'ean_': 439,
 'ir_': 440,
 'new_': 441,
 'sin': 442,
 'fo': 443,
 'better_': 444,
 'mp': 445,
 'every': 446,
 'yea': 447,
 'yeah_': 448,
 'na_': 449,
 'nothing_': 450,
 'wo': 451,
 'fri': 452,
 'dr': 453,
 'ment_': 454,
 'tra': 455,
 'off_': 456,
 'anything_': 457,
 'hu': 458,
 'away_': 459,
 'old_': 460,
 'two_': 461,
 'dea': 462,
 'du': 463,
 'ding_': 464,
 'mean_': 465,
 'love_': 466,
 'ello_': 467,
 'gre': 468,
 'ant_': 469,
 'ous_': 470,
 'br': 471,
 'hello_': 472,
 'sed_': 473,
 'tu': 474,
 'fore_': 475,
 'gen': 476,
 'ling_': 477,
 'miss_': 478,
 'chi': 479,
 'fir': 480,
 'before_': 481,
 'said_': 482,
 'again_': 483,
 'ose_': 484,
 'b_': 485,
 'ving_': 486,
 "'_": 487,
 'find_': 488,
 'kee': 489,
 'sha': 490,
 'ven_': 491,
 'ons_': 492,
 'should_': 493,
 'pe_': 494,
 'roo': 495,
 'long_': 496,
 'stand_': 497,
 'cour': 498,
 'hear': 499,
 'han': 500,
 'ouldn_': 501,
 'isn_': 502,
 'hou': 503,
 'father_': 504,
 'chan': 505,
 'sorry_': 506,
 'help_': 507,
 'ser': 508,
 'ster_': 509,
 'ways_': 510,
 'mber_': 511,
 'than_': 512,
 'after_': 513,
 'cause_': 514,
 'thought_': 515,
 'ac': 516,
 'ely_': 517,
 'ce': 518,
 'put_': 519,
 'gra': 520,
 'even_': 521,
 'home_': 522,
 'may': 523,
 'ople_': 524,
 'first_': 525,
 'people_': 526,
 'gir': 527,
 'tur': 528,
 'sho': 529,
 'ked_': 530,
 'gon': 531,
 'ssi': 532,
 'mind_': 533,
 'thr': 534,
 'things_': 535,
 'always_': 536,
 'those_': 537,
 'maybe_': 538,
 'ight_': 539,
 'les_': 540,
 'into_': 541,
 'keep_': 542,
 'talk_': 543,
 'last_': 544,
 'gonna_': 545,
 'ain_': 546,
 'wait_': 547,
 'mrs_': 548,
 'told_': 549,
 'ree_': 550,
 'try_': 551,
 'ried_': 552,
 'may_': 553,
 'because_': 554,
 'ves_': 555,
 'ps_': 556,
 'ms_': 557,
 'leave_': 558,
 'est': 559,
 'ft_': 560,
 'these_': 561,
 'char': 562,
 'lie': 563,
 'dar': 564,
 'under': 565,
 'dear_': 566,
 'tch_': 567,
 'around_': 568,
 'life_': 569,
 'sw': 570,
 'tting_': 571,
 'course_': 572,
 'ju': 573,
 'money_': 574,
 'ger_': 575,
 'ence_': 576,
 'place_': 577,
 'lan': 578,
 'il_': 579,
 'ears_': 580,
 'wouldn_': 581,
 'il': 582,
 'minu': 583,
 'morning_': 584,
 'coun': 585,
 'pri': 586,
 'ton': 587,
 'man': 588,
 'really_': 589,
 'x_': 590,
 'work_': 591,
 'name_': 592,
 'nice_': 593,
 'ad': 594,
 'matter_': 595,
 'ctor_': 596,
 'room_': 597,
 'everything_': 598,
 'might_': 599,
 'bea': 600,
 'star': 601,
 'har': 602,
 'ok_': 603,
 'ny_': 604,
 'haven_': 605,
 'still_': 606,
 'dan': 607,
 'est_': 608,
 ':_': 609,
 'enough_': 610,
 'clo': 611,
 'girl_': 612,
 'ved_': 613,
 'hur': 614,
 'call_': 615,
 'row_': 616,
 'mes_': 617,
 'house_': 618,
 'fin': 619,
 'doing_': 620,
 'ja': 621,
 'does_': 622,
 'hon': 623,
 'ye_': 624,
 'reme': 625,
 'head_': 626,
 'ppo': 627,
 'thanks_': 628,
 'came_': 629,
 'eel_': 630,
 'at': 631,
 'hey_': 632,
 'cha': 633,
 'lled_': 634,
 'need_': 635,
 'stay_': 636,
 'ff': 637,
 'your': 638,
 'see': 639,
 'tru': 640,
 'el_': 641,
 'mer': 642,
 'sc': 643,
 'sen': 644,
 'stop_': 645,
 'most_': 646,
 'boy_': 647,
 'tty_': 648,
 'tle': 649,
 'list': 650,
 'coming_': 651,
 'raid_': 652,
 'ded_': 653,
 'red_': 654,
 'mother_': 655,
 'remember_': 656,
 'lon': 657,
 'live_': 658,
 'ready_': 659,
 'ened_': 660,
 'sy_': 661,
 'ask_': 662,
 'another_': 663,
 'years_': 664,
 'my': 665,
 'stu': 666,
 'hear_': 667,
 'side_': 668,
 'through_': 669,
 'yourself_': 670,
 'shi': 671,
 'understand_': 672,
 'afraid_': 673,
 'doe': 674,
 'bro': 675,
 'doesn_': 676,
 'kn': 677,
 'belie': 678,
 'done_': 679,
 'made_': 680,
 'kes_': 681,
 'gla': 682,
 'ber': 683,
 'sit_': 684,
 'won': 685,
 'their_': 686,
 'big_': 687,
 'believe_': 688,
 'cer': 689,
 'ka': 690,
 'great_': 691,
 'left_': 692,
 'cor': 693,
 'ep_': 694,
 'feel_': 695,
 'tonight_': 696,
 'ner_': 697,
 'shall_': 698,
 '00_': 699,
 'wal': 700,
 'kind_': 701,
 'bad_': 702,
 'every_': 703,
 'tain_': 704,
 'hor': 705,
 'ir': 706,
 'couldn_': 707,
 'ows_': 708,
 'ned_': 709,
 'bab': 710,
 'suppo': 711,
 'je': 712,
 'gentle': 713,
 'lot_': 714,
 'woman_': 715,
 'who': 716,
 'cap': 717,
 'friend_': 718,
 'three_': 719,
 'rong_': 720,
 'tri': 721,
 'stor': 722,
 'brea': 723,
 'spe': 724,
 'tes_': 725,
 'ol_': 726,
 'bar': 727,
 'with': 728,
 'od': 729,
 'care_': 730,
 'fran': 731,
 'drin': 732,
 'cra': 733,
 'lli': 734,
 'darling_': 735,
 'listen_': 736,
 'ph': 737,
 'wanted_': 738,
 'doctor_': 739,
 'bla': 740,
 'myself_': 741,
 'im': 742,
 'ma_': 743,
 'seen_': 744,
 'lady_': 745,
 'youn': 746,
 'busin': 747,
 'ls_': 748,
 'war': 749,
 'ff_': 750,
 'once_': 751,
 'inter': 752,
 'minute_': 753,
 'heard_': 754,
 'else_': 755,
 'wai': 756,
 'poli': 757,
 'che': 758,
 'able_': 759,
 'gar': 760,
 'world_': 761,
 'ening_': 762,
 'ley_': 763,
 'ouble_': 764,
 'business_': 765,
 'din': 766,
 'tch': 767,
 'fine_': 768,
 'lor': 769,
 'morrow_': 770,
 'ans_': 771,
 'such_': 772,
 'beau': 773,
 'pretty_': 774,
 'tomorrow_': 775,
 'dr_': 776,
 'show_': 777,
 'pt_': 778,
 'hope_': 779,
 'ged_': 780,
 'wife_': 781,
 'land_': 782,
 'cy_': 783,
 'alone_': 784,
 'quite_': 785,
 'gr': 786,
 'dre': 787,
 'happy_': 788,
 'young_': 789,
 'ed': 790,
 'while_': 791,
 'getting_': 792,
 'dead_': 793,
 'ses_': 794,
 'bring_': 795,
 'men': 796,
 'wasn_': 797,
 'knew_': 798,
 'yet_': 799,
 'same_': 800,
 'sle': 801,
 'saw_': 802,
 'without_': 803,
 'guess_': 804,
 'ins_': 805,
 'mur': 806,
 'wish_': 807,
 'sk': 808,
 'sing_': 809,
 'ele': 810,
 'being_': 811,
 'ide': 812,
 'lt_': 813,
 'med_': 814,
 'comp': 815,
 'ary_': 816,
 'idea_': 817,
 'die_': 818,
 'can': 819,
 'ste': 820,
 'tions_': 821,
 'que': 822,
 'ces_': 823,
 'cho': 824,
 'looking_': 825,
 'wrong_': 826,
 'suppose_': 827,
 'happened_': 828,
 'boys_': 829,
 'por': 830,
 'lf_': 831,
 'spea': 832,
 'bor': 833,
 'offi': 834,
 'joh': 835,
 'bye_': 836,
 'hun': 837,
 'days_': 838,
 'along_': 839,
 'eng': 840,
 'att': 841,
 'age_': 842,
 'rest_': 843,
 'pr': 844,
 'found_': 845,
 'turn_': 846,
 'stan': 847,
 'unti': 848,
 'soon_': 849,
 'town_': 850,
 'ger': 851,
 'went_': 852,
 'bel': 853,
 'wee': 854,
 'bri': 855,
 'gone_': 856,
 'many_': 857,
 'dis': 858,
 'bra': 859,
 'hold_': 860,
 'fell': 861,
 'drink_': 862,
 'cked_': 863,
 'vo': 864,
 'ends_': 865,
 'ing': 866,
 'app': 867,
 'guy_': 868,
 'sent_': 869,
 'trouble_': 870,
 'xt_': 871,
 'ght': 872,
 'win': 873,
 'bur': 874,
 'next_': 875,
 'ness_': 876,
 'ally_': 877,
 'best_': 878,
 'va': 879,
 'ot_': 880,
 'uh_': 881,
 'dge_': 882,
 'pap': 883,
 'gentlemen_': 884,
 'until_': 885,
 'sur': 886,
 'few_': 887,
 'ke': 888,
 'since_': 889,
 'married_': 890,
 'glad_': 891,
 'mine_': 892,
 'job_': 893,
 'wri': 894,
 'less_': 895,
 'today_': 896,
 'ei': 897,
 'int_': 898,
 'kay_': 899,
 'ssed_': 900,
 'ani': 901,
 'dri': 902,
 'uni': 903,
 'whole_': 904,
 'ffer': 905,
 'ken_': 906,
 'trying_': 907,
 'good': 908,
 'times_': 909,
 'run_': 910,
 'talking_': 911,
 'cla': 912,
 'wonder': 913,
 'hand_': 914,
 'spi': 915,
 'gott': 916,
 'used_': 917,
 'sig': 918,
 "in'_": 919,
 'waiting_': 920,
 'bed_': 921,
 'ze_': 922,
 'ton_': 923,
 'lie_': 924,
 'forget_': 925,
 'perha': 926,
 'perhaps_': 927,
 'late_': 928,
 'beauti': 929,
 'sb': 930,
 'captain_': 931,
 'says_': 932,
 'cti': 933,
 'toge': 934,
 'case_': 935,
 'nu': 936,
 'word_': 937,
 'kill_': 938,
 'together_': 939,
 'cr': 940,
 'son': 941,
 'ten': 942,
 'fr': 943,
 'expe': 944,
 'dd': 945,
 'which_': 946,
 'okay_': 947,
 'meet_': 948,
 'led_': 949,
 'act': 950,
 'ugh': 951,
 'open_': 952,
 'evening_': 953,
 'plan': 954,
 'huh_': 955,
 'play_': 956,
 'len': 957,
 'eu': 958,
 'tt_': 959,
 'aren_': 960,
 'each_': 961,
 'cks_': 962,
 'send_': 963,
 'ago_': 964,
 'wants_': 965,
 'under_': 966,
 'da_': 967,
 'car_': 968,
 'husb': 969,
 'somebody_': 970,
 'shed_': 971,
 'police_': 972,
 'beautiful_': 973,
 'ort': 974,
 'mada': 975,
 'pay_': 976,
 'mp_': 977,
 'tain': 978,
 'ous': 979,
 'pped_': 980,
 'gran': 981,
 'took_': 982,
 'bit_': 983,
 'up': 984,
 'dly_': 985,
 'worry_': 986,
 'killed_': 987,
 'water_': 988,
 'ven': 989,
 'door_': 990,
 'ship_': 991,
 'husband_': 992,
 'zy_': 993,
 'chance_': 994,
 'ture_': 995,
 'low': 996,
 'out': 997,
 'ad_': 998,
 'sou': 999,
 ...}

In [125]:
dct_encoder.get("running_", None)

1538

In [120]:
char_factor("running")

['r', 'u', 'n', 'n', 'i', 'n', 'g', '_']

In [162]:
def word_encoder(word, vocab_pairs, vocab_enc):
    word_proc = char_factor(word)
    word_enc = vocab_enc.get("".join(word_proc), None)
    if word_enc:
        return [word_enc]
    else:
        word_pairs = list(zip(word_proc, word_proc[1:]))
        for pair in list(vocab_pairs.keys())[55:]:
            if pair in word_pairs:
                p_1, p_2 = map(re.escape, pair)
                word_proc = re.sub(rf"(?<=\s){p_1}\s{p_2}(?=\s)", f"{pair[0]}{pair[1]}", f" {' '.join(word_proc)} ").split()
                word_pairs = list(zip(word_proc, word_proc[1:]))
        return [vocab_enc[x] for x in word_proc]

In [169]:
word_encoder("poland", tokenizer_test5.vocab, dct_encoder)

[227, 782]

In [171]:
tokenize_eng("I've been thinking about asking her out.")

['i', "'ve", 'been', 'thinking', 'about', 'asking', 'her', 'out', '.']

In [172]:
def sentence_encoder(snt, vocab_pairs, vocab_enc):
    snt_proc = tokenize_eng(snt)
    return [word_encoder(wrd, vocab_pairs, vocab_enc) for wrd in snt_proc]

In [173]:
sentence_encoder("I've been thinking about asking her out.", tokenizer_test5.vocab, dct_encoder)

[[70], [213], [301], [1071], [228], [1707], [248], [150], [56]]