## 04. scratchpad

In [3]:
import pandas as pd
import os
from collections import defaultdict

In [2]:
tup = ('sigma', 'alfa')
kon = 'brabus/'
a, b = [kon+f for f in tup]
print(a)
print('ladskfhasldf')
print(b)

brabus/sigma
ladskfhasldf
brabus/alfa

In [5]:
def upload_to_dataframe(root, files, num_lines):
    path_eng, path_pol = [root+f for f in files]
    data = defaultdict(list)
    
    with open (path_eng, encoding="utf_8") as f_eng, open (path_pol, encoding="utf_8") as f_pol:
        for _ in range(num_lines):
            data['eng_text'].append(f_eng.readline().strip())
            data['pol_text'].append(f_pol.readline().strip())
    return pd.DataFrame(data)

In [6]:
root = "../data/opus_opensub/en-pl.txt/"
files = ('OpenSubtitles.en-pl.en', '/OpenSubtitles.en-pl.pl')
df = upload_to_dataframe(root, files, 600000)

In [16]:
df.head()

,eng_text,pol_text
0,"Previously on ""The Blacklist""...",/W poprzednich odcinkach: /
1,- You want to call your daddy?,- Chcesz zadzwonić do taty?
2,"- Yeah, I want to tell him I'm okay.","- Tak, powiem, że wszystko w porządku."
3,Okay.,Dobrze.
4,Lizzy... Be careful of your husband.,"Lizzy, uważaj na męża."

In [24]:
df.sample(n=30)

,eng_text,pol_text
451074,Monke!,Monke!
339469,There.,Gówno!
367456,"All right, Shannon.","Dobrze, Shannon."
176994,But it was starving!,Przecież był głód!
564036,Maybe some day we can send a little committee ...,Kiedyś wyślemy nasz własny komitet do zbadania...
20924,I've been waiting for this for three weeks.,Czekałem na to trzy tygodnie.
268439,"- Now, if I didn't like ya... - Now, just a mi...",- Gdybym cię nie lubił...
204870,- A little frightening.,- Trochę przerażająco.
143304,Connie?,Connie?
484528,"Where are they, out digging' a grave?",Kopią teraz grób?
505884,I know that you're looking for a man who wears...,"Wiem, że szuka pan człowieka, który nosi tupecik."
338988,Is whatever it is painful?,Czy to bolesne?
500906,-Mr. Berg...!,- Panie Berg...!
281993,Christopher Columbus! We're being shot at!,Strzelają do nas!
131820,- Flatfoot.,- Gliniarza.
251535,- I just finished law school.,- Właśnie skończyłem wydział prawa.
435119,"I'm obliged to you, lieutenant, and I thank yo...","Jestem panu zobowiązany, poruczniku, i dziękuj..."
569432,That's a tree.,To jest drzewo.
358808,"Tough guy, aren't you?","Twardy facet, prawda?"
234774,"Ashley's safe, he isn't listed!",Ashley jest cały!
373710,"Here, take this one.",- Weź to. - A ja?
579803,The ballroom's out.,Usunięta.
349549,♪ In you ♪,# Ze sobą #
167183,Why would I have advised you... to wear a Euro...,Dlaczego miałbym poradzić ci... założenie euro...
60411,He was run over by a truck.,- Został przejechany przez ciężarówkę.
41346,"- Hello, kid. - Hello, Tom.",Cześć.
86282,I'll get Wellington.,Wezmę Wellingtona.
40804,Save me!,Ratunku!
74006,"One, two.","Raz, dwa."
129836,Play smart.,Graj mądrze.

In [ ]:
path = "../data/opus_opensub/en-pl.txt/
files = ('OpenSubtitles.en-pl.en', '/OpenSubtitles.en-pl.pl')

In [2]:
os.listdir("../data/opus_opensub/en-pl.txt")

['LICENSE', 'OpenSubtitles.en-pl.en', 'OpenSubtitles.en-pl.pl', 'README']

In [53]:
with open("../data/opus_opensub/en-pl.txt/OpenSubtitles.en-pl.en", encoding="utf_8") as f:
    data_eng = []
    for _ in range(500000):
        data_eng.append(f.readline().strip())

In [54]:
with open("../data/opus_opensub/en-pl.txt/OpenSubtitles.en-pl.pl", encoding="utf_8") as f:
    data_pol = []
    for _ in range(500000):
        data_pol.append(f.readline().strip())

In [57]:
data_eng[50390:50410]

["What's your theory, Doctor?",
 'Strangulation by terrifically powerful hands.',
 'You will notice how deeply the thumbs are embedded in the sternocleidomastoid.',
 'And what do you think of this incision at the base of the brain?',
 'Obviously made by some type of scalpel used for brain dissecting.',
 "But it's peculiar that this left deltoid muscle should be missing.",
 "- It's been torn right out.",
 "- Gentlemen, it wasn't torn.",
 'This is cannibalism.',
 '- This portion of the body was...',
 '- Impossible!',
 "There's no doubt about it.",
 'Thank you, Doctor.',
 'I appreciate your professional opinion.',
 "I'm only too happy to be of any service to you, gentlemen.",
 "Now, if you'll excuse me, I have rather an important experiment in progress that demands my attention every few hours.",
 "I hardly think I can be of any further use to you, so if you don't mind, I'm very, very sorry, but I'll say good night.",
 "Just a moment, Doctor, if you don't mind.",
 'One thing more.',
 '- Very well, sir.']

In [58]:
data_pol[50390:50410]

['Jaka jest twoja teoria, doktorze?',
 'Została uduszona przez kogoś bardzo silnego.',
 'Wyraźnie widać ślady kciuków... na mięśniach mostkowo-obojczykowo-sutkowych.',
 'Co myślisz o tym nacięciu u podstawy mózgu?',
 'Oczywiście wykonane przez jakiś rodzaj skalpela... używanego do sekcji mózgu.',
 'Ale to dziwne brakuje lewego mięśnia naramiennego.',
 '- Został wyrwany.',
 '- Panowie, nie został wyrwany.',
 'To kanibalizm.',
 '- Ta część ciała była...',
 '- Niemożliwe!',
 '- Nie ma co do tego wątpliwości.',
 '- Dziękuję doktorze.',
 'Doceniam twoją profesjonalną opinię.',
 'Jestem szczęśliwy mogąc wam pomóc, panowie.',
 'A teraz wybaczcie, mam ważny eksperyment i muszę regularnie... monitorować jego postępy.',
 'Nie sądzę, żebym mógł się jeszcze przydać, więc jeśli nie macie nic przeciwko, bardzo przepraszam, ale życzę dobrej nocy.',
 'Chwileczkę doktorze, jeśli nie masz nic przeciwko.',
 'Jeszcze jedno.',
 '- Dobrze, sir?']