## 04. scratchpad

### 1. Data Upload

In [455]:
import pandas as pd
import os
from collections import defaultdict, Counter
import re

In [2]:
def upload_to_dataframe(root, files, num_lines):
    path_eng, path_pol = [root+f for f in files]
    data = defaultdict(list)
    
    with open (path_eng, encoding="utf_8") as f_eng, open (path_pol, encoding="utf_8") as f_pol:
        for _ in range(num_lines):
            data['eng_text'].append(f_eng.readline().strip())
            data['pol_text'].append(f_pol.readline().strip())
    return pd.DataFrame(data)

In [3]:
root = "../data/opus_opensub/en-pl.txt/"
files = ('OpenSubtitles.en-pl.en', '/OpenSubtitles.en-pl.pl')
df = upload_to_dataframe(root, files, 600000)

### 2. EDA & Sanitazation

#### 2.1 English Non-Ascii Sentences

In [4]:
def nonascii_list(df_series, is_pol):
    if is_pol:
        pl_chars = set("ąęćłńóśźżĄĘĆŁŃÓŚŹŻ")
        requir = lambda x: x.isascii() or x in pl_chars
    else:
        requir = lambda x: x.isascii()
        
    text_all = ''.join(df_series)
    unique_dct = {x for x in text_all if not requir(x)}
    return sorted(list(unique_dct))

In [5]:
print(nonascii_list(df['eng_text'], False))

['\x80', '\x81', '\x82', '\x83', '\x84', '\x85', '\x88', '\x8b', '\x8c', '\x8e', '\x8f', '\x91', '\x94', '\x96', '\x98', '\x99', '\x9c', '\x9d', '\xa0', '¡', '¢', '£', '¤', '¥', '¦', '§', '¨', '©', 'ª', '¬', '\xad', '°', '±', '²', '³', '´', 'µ', '¶', '·', '¸', '¹', 'º', '¼', '½', '¾', '¿', 'Á', 'Â', 'Ã', 'Ä', 'Å', 'Ç', 'É', 'Ê', 'Ì', 'Ï', 'Ð', 'Ñ', 'Ô', 'Ö', 'Ø', 'Ü', 'Ý', 'Þ', 'ß', 'à', 'á', 'â', 'ã', 'ä', 'å', 'ç', 'è', 'é', 'ê', 'ì', 'í', 'î', 'ï', 'ð', 'ñ', 'ó', 'ô', 'ö', 'ù', 'ú', 'û', 'ü', 'ý', 'þ', 'Ă', 'ď', 'ę', 'Ł', 'ń', 'ő', 'œ', 'ś', 'Š', 'š', 'Ј', 'С', 'й', '،', 'أ', 'إ', 'ئ', 'ا', 'ب', 'ة', 'ت', 'ح', 'ر', 'س', 'ش', 'ع', 'غ', 'ف', 'ك', 'ل', 'م', 'ن', 'و', 'ي', 'َ', 'ُ', 'ِ', 'ّ', 'ْ', '\u200b', '‒', '–', '—', '‚', '€', '™', '─', '☻', '♥', '♪', '慹', '拢', '檛', '鈥', 'ﬁ', 'ﬂ']

In [6]:
is_ascii = lambda text: text.isascii()
maska = df['eng_text'].apply(is_ascii)
df_non_ascii = df[~maska].copy().reset_index(drop=True)
print(df_non_ascii.shape)
df_non_ascii.head()

(4595, 2)

,eng_text,pol_text
0,¿You had never seen A crab suedes? Them there ...,- Nigdy wcześniej nie widziałaś raków?
1,"He hears ¿, where you live?",Nigdy wcześniej nie byłam w lesie.
2,"Boys ¿, they are there?",Jesteście tam chłopaki?
3,- Te atrapé. - No es gracioso. Your he catches...,- Ale twoje mina była.
4,"Your also ¿, it is not like that?","- Tak, niezła jest"

In [7]:
df_2 = df[maska].reset_index(drop=True)
df_2.shape

(595405, 2)

#### 2.2 Polish Non-Ascii Sentences

In [8]:
pl_chars = set("ąęćłńóśźżĄĘĆŁŃÓŚŹŻ")
requir = lambda let: not let.isascii() and let not in pl_chars
maska = df_2['pol_text'].apply(lambda snt: any([requir(let) for let in snt]))
df_non_ascii = df_2[maska].copy().reset_index(drop=True)
print(df_non_ascii.shape)
df_non_ascii.sample(10)

(1227, 2)

,eng_text,pol_text
328,"Laughing, happy.",Šmieja sie. Ciesza sie.
99,Death!,...jest mi ¶mierci±!
811,Are we going to let a man like that throw mud ...,"POWSTRZYMAC SMITHA Pozwolimy, by ktoš taki obr..."
143,He was going to send for you As soon as you go...,Zamierzał po ciebie posłać jak ​​tylko stąd wy...
951,There is a legend he can drink two bottles of ...,"Istnieje legenda, że ​​może wypić dwie butelki..."
157,The JurgenStrasse isn't it.,"To jest JürgenStrasse, prawda?"
724,Every aspect of this matter was dealt with in ...,Wszystkie sporne kwestie zostaly wyjašnione na...
767,- I've seen filibustering...,PAINE'A - Widzialem juž takie filipiki.
319,"Come on, boss.","Šmialo, szefuniu."
46,This is blasphemy.,BluĽnisz przeciw Bogu.

In [9]:
df_3 = df_2[~maska].reset_index(drop=True)
print(df_3.shape)
df_3.sample(5)

(594178, 2)

,eng_text,pol_text
460399,"Whenever there's trouble, you're always on the...",Proszę wejść.
422385,You talk as if you wanted to see her tried for...,"Mówi pan, jakby chciał ją zobaczyć sądzoną za ..."
116876,"Ask me anything else, anything!","Proszę. Proś mnie, o co zechcesz."
42758,And I'm going to take you in my arms now and h...,I zaraz wezmę cię w ramiona i przytulę mocno! ...
33941,It's Elizabeth!,To Elizabeth!

In [10]:
print(nonascii_list(df_3['eng_text'], False))
print(nonascii_list(df_3['pol_text'], True))

[]
[]

In [11]:
df_3.iloc[74182]['eng_text']

'The next time I...'

In [12]:
df_3.iloc[74182]['pol_text']

'Następnym razem...'

#### 2.3 Short Or Empty Examples

In [13]:
mask1 = df_3['eng_text'].str.len() >= 3
mask2 = df_3['pol_text'].str.len() >= 3

In [14]:
df_4 = df_3[mask1 & mask2].reset_index(drop=True)
df_4.head()

,eng_text,pol_text
0,"Previously on ""The Blacklist""...",/W poprzednich odcinkach: /
1,- You want to call your daddy?,- Chcesz zadzwonić do taty?
2,"- Yeah, I want to tell him I'm okay.","- Tak, powiem, że wszystko w porządku."
3,Okay.,Dobrze.
4,Lizzy... Be careful of your husband.,"Lizzy, uważaj na męża."

In [15]:
df_4.shape

(593894, 2)

#### 2.4 Dialog like sentences [starts with - ]

In [16]:
is_dialog = lambda snt: bool(re.match(r"^ *- *", snt))
mask = df_4['eng_text'].apply(is_dialog) | df_4['pol_text'].apply(is_dialog)
df_dialogs = df_4[mask].copy().reset_index(drop=True)
df_dialogs.head()

,eng_text,pol_text
0,- You want to call your daddy?,- Chcesz zadzwonić do taty?
1,"- Yeah, I want to tell him I'm okay.","- Tak, powiem, że wszystko w porządku."
2,- 45 seconds.,Szybciej! 45 sekund.
3,It's okay. It's okay. It's okay.,- Już dobrze.
4,It's okay. You're okay. You're okay.,- Odpoczywaj.

In [17]:
def fix_dialog(snt):
    return re.sub(r"^ *- *", "", snt)

df_4['eng_text'] = df_4['eng_text'].apply(fix_dialog).reset_index(drop=True)
df_4['pol_text'] = df_4['pol_text'].apply(fix_dialog).reset_index(drop=True)
df_4.sample(30)

,eng_text,pol_text
313445,So you and the old boy cross swords?,Więc posprzeczałeś się ze staruszkiem?
139898,See you all later,Do zobaczenia.
171937,Love is a strange thing.,Miłość to dziwna rzecz.
445872,What about the poorhouse?,A przytulisko?
223879,Halt!,Stać!
531417,I'll get rid of them.,Dlaczego nie mogę?
1364,"Yes, of course.","Tak, oczywiście."
163491,Try and come to an understanding with the boss.,Spróbuj się porozumieć z szefową.
31358,You're not going to see some young lieutenant ...,Nie masz dziś w planach randki z jakimś młodym...
136937,I couldn't marry a dead man.,Nie mogę wyjść za nieboszczyka.
534334,"""For I'm foolish.""","""Bo jestem głupia."""
412608,Hollywood caught up with you?,Załapałeś się w Hollywoodzie?
11628,"""No, no, anything but that!""","""Nie, wszystko tylko nie to!"""
79175,"Gee, it's warm in here.","Rany, ale tu jest gorąco."
442093,"Darling, you are the song","Kochanie, jesteś piosenką"
218031,I wasn't thinking of that.,Nie o tym myślałem.
509772,"Have to get it yourself, mister.",Musi pan wziąć sam.
380890,"ONE ""B.""",Zabierasz ze sobą lunch?
585265,This lady I've been telling you about.,"Ta dama, o której mówiłam."
580837,We'll bunk in it.,Będziemy tam nocować.
530655,Sorry about you two. Kathy told my wife this m...,"Przykro mi, że się wam nie ułożyło."
16178,Director:,Reżyseria:
320964,"They are men too, like us.",Są takimi samymi ludźmi jak my.
112447,I wasn't sleeping.,Nie spałem. Byłem...
386065,There you are Donald.,Tu jesteś Donald.
30257,"Boss, I'm sorry. I should have been with you.","Przepraszam, powinienem być z tobą."
197660,"That's Aunt Hedwige, the head of the family.","To ciocia Hedwige, głowa rodu."
94274,That's me.,To ja.
29895,Just because...,Przyjdzie...
326922,It's a good game.,To dobra gra.

#### 2.5 Broken Dialog like sentences [somehwere has -]

# Do naprawy (lepszy re przed tokenziacja)

In [18]:
broken_dialog = lambda snt: bool(re.match(r".* +- +.*", snt))
mask1 = df_4['eng_text'].apply(broken_dialog)
mask2 = df_4['pol_text'].apply(broken_dialog)

In [19]:
df_4[mask1 | mask2].sample(5)

,eng_text,pol_text
407931,Get back!,Wracać. - Ewakuacja!
508312,Would you take a note in for me? - When he buz...,Zaniosłabyś mu liścik ode mnie?
492639,He's coming. - Who?,Kto?
127576,"She's gone, sir. - Gone?","Wyjechała, proszę pana."
329368,"And maybe in a flash, like a bolt of lightning...","Nie przetrwałby bez korzeni, które sięgają głe..."

In [20]:
df_5 = df_4[~mask1 & ~mask2].reset_index(drop=True)

In [21]:
broken_dialog = lambda snt: bool(re.match(r".*-.*", snt))

In [22]:
df_5.sample(50)

,eng_text,pol_text
424250,"Oh, how I do hate living in a London flat.",Jak ja nienawidzę mieszkać w londyńskim mieszk...
203754,I can't.,Nie mogę.
368225,HeilHitler.,Heil Hitler.
428530,"There's a $10,000 reward out for just the kind...",Jest 10 tysięcy nagrody za ten rodzaj informac...
565153,Yes. Is there something I can do?,Jestem jego żoną.
301504,"Yes, yes, I'll do it.","Tak, tak, zrobię to."
537393,German victory is inevitable.,Zwycięstwo Niemiec jest pewne.
391344,You hear that?,Słyszałeś to?
504670,"Furthermore, she knew precisely how to guide m...",Pomogła mi wyjść tylnymi drzwiami.
51847,He's probably under one.,Baravelli do mnie.
380754,Mrs Walden.,Pani Walden.
6708,"""Good evening, Mr. Hull!""","Dzień dobry, panie Hull!"
215020,Let's sit down.,Usiądźmy.
125821,"Oh please, Andre.","Błagam, Andre!"
219179,And you're irritable because your nerves are a...,"Jest pani rozdrażniona, bo ma napięte nerwy."
543714,"This isn't a country for glory, Owen.",To nie jest kraj gdzie można zdobyć chwałę.
504995,In these things we'd be spotted right away.,W tych ciuchach zaraz nas namierzą.
109051,Beasts.,Bestie.
154091,It's got the Falins' smell on it.,Ma na sobie zapach Falinów.
40814,"No, he wouldn't!",Tak myślisz?
23942,You can't be serious.,Pan raczy żartować!
151982,Meet Mr. Hawkins.,To pan Hawkins.
564898,"How dare you? Who are you, anyway?",Kim jesteś?
322593,"Mommy, you're a heroine.","Mamo, jesteś bohaterką."
30082,I am Dracula.,Jestem... Dracula.
356293,I'm afraid Bananas is only used to forecastles.,"Obawiam się, że Bananowi brak trochę ogłady."
348245,Where are you going?,Dokąd idziesz?
356140,You found your anchor?,Wciągaj kotwicę.
84587,What?,Co?
372183,"I love you, Sam.","Kocham cię, Sam."
70431,She's been put In solitary.,Wzięli ją do izolatki.
338582,"Now, you've got to listen to me.",Posłuchaj mnie.
380662,"Come on, honey, and sit down.",Usiądź słoneczko.
21430,"Exactly, nothing elaborate.","Miejsce, które można nazwać domem a żonie powi..."
530794,Who are they eh?,Kim oni są?
98945,MacCaulay? I can't believe it!,Nie do wiary!
76355,"Alright, I'll leave in five minutes.","Dobra, wyjdę za pięć minut."
411328,"No, thanks.",Nie.
529721,"Hello, Grannie.","Cześć, babciu."
374186,"Worse than that, there was a strike at the fac...","Co gorsza, w fabryce był strajk, a ja, kierown..."
299982,Twenty years?,Dwadzieścia lat?
513647,Seem any easier?,Trochę lepiej?
371360,"I mean, Mrs. Craig.","Znaczy, pani Craig."
198291,It was my way of making him happy.,Tak mogłam go uszczęśliwić.
325315,It's a waste of time. If you want to get sore ...,"Jeśli cię irytuję, to normalne., wszystkim dzi..."
34868,"Well, I'm sorry I wasted your time, Mr. Taylor.",No to przykro mi. Zmarnowałem twój czas panie ...
575191,"What's he ke, Nor ko?","Jaki on jest, Noriko?"
108537,Clear deck!,Opuścić pokład!
43771,SHE'S DEAD.,Ona nie żyje.
505094,We never saw him before.,Widzimy go pierwszy raz.

#### 2.6 Different Last Case

In [23]:
mask = df_5['eng_text'].str[-1] != df_5['pol_text'].str[-1]
mask.sum()

57558

In [24]:
df_6 = df_5[~mask].reset_index(drop=True)

#### 2.7 Text length difference

In [25]:
mask = df_6['eng_text'].str.split
df_6['len_ratio'] = df_6['eng_text'].str.split().str.len() / df_6['pol_text'].str.split().str.len()
df_6.head()

,eng_text,pol_text,len_ratio
0,You want to call your daddy?,Chcesz zadzwonić do taty?,1.500000
1,"Yeah, I want to tell him I'm okay.","Tak, powiem, że wszystko w porządku.",1.333333
2,Okay.,Dobrze.,1.000000
3,Lizzy... Be careful of your husband.,"Lizzy, uważaj na męża.",1.500000
4,I can only lead you to the truth.,/Mogę naprowadzić cię na prawdę.,1.600000

In [26]:
thres_left = df_6["len_ratio"].quantile(0.05)
thres_right = df_6["len_ratio"].quantile(0.95)
thres_left, thres_right

(0.75, 2.5)

In [27]:
mask = (df_6["len_ratio"] >= thres_left) & (df_6["len_ratio"] <= thres_right)
mask.sum()

472209

In [28]:
df_7 = df_6[mask].reset_index(drop=True)
df_7.sample(20)

,eng_text,pol_text,len_ratio
255829,I've got about $500 left.,Zostało mi 500 dolarów.,1.250000
375607,Sorry.,Przepraszam.,1.000000
115059,Mr. Waldemar!,Panie Waldemar!,1.000000
149747,Hurry.,Szybko.,1.000000
273679,I see.,Rozumiem.,2.000000
339633,Even if it is about Hitler?,Nawet jeżeli dotyczy Hitlera?,1.500000
139800,You'd never sell your old stock.,Nigdy nie sprzedałaby pani starego towaru.,1.000000
12781,Look. My family.,Moja rodzina.,1.500000
414887,You see me climb in? Sure. Or I wouldn't sugge...,Inaczej nie zachęcałbym cię do wyjścia.,2.333333
276094,I saw the tunnel that my pal Lefty Matson dug ...,Widziałem ten tunel co mój kumpel Lefty Matson...,1.153846
40716,"We could wait here a few minutes, and say that...","Poczekajmy tu parę minut, potem zejdźmy i powi...",1.083333
93320,Stand by to go aloft!,Przygotować się do wejścia na maszt!,0.833333
124075,Certainly.,Oczywiście.,1.000000
152776,Yeah. Yeah.,Pewnie.,2.000000
282714,"Is Vin still a vege... ""Vegetenarian,"" mother?",On ciągle jest wegetarianinem?,1.750000
225470,"Oh, speaking of that Zorro, could you provide ...","A co do tego Zorro, ekscelencjo... zapewnisz m...",1.181818
22248,I can't get it out of my mind.,Nie mogę tego wyrzucić z umysłu.,1.333333
217741,I've been looking for you tramps.,"Szukałam was, dranie.",2.000000
219594,He promised me money and a good position if I ...,"Obiecał mi pieniądze i dobrą posadę, jeśli nic...",1.400000
324553,Have your own elderberry bushes?,Macie panie własne krzewy bzu?,1.000000

In [29]:
df_7.sample(50)

,eng_text,pol_text,len_ratio
173037,Twice I've seen you dead in my dreams.,Dwa razy widziałem cię martwego w moich snach.,1.000000
284328,It was pretty sweet of him to come from New Yo...,"I to miłe z jego strony, że zechciał przyjecha...",0.866667
162221,Reverend Ethan Wilkins! Reverend Wilkins has c...,Wielebny Ethan Wilkins który przybył z Marylan...,1.600000
160195,Right.,Dobrze.,1.000000
106869,Ferryboat.,Prom.,1.000000
86412,"If it was anybody else but you, I'd chuck you ...","Gdyby to był ktoś niż ty, wyrzuciłbym za burtę.",1.222222
365955,Shut up. You're a cheap crook and you killed him.,Jesteś oszustem i go zabiłeś.,2.000000
200980,They can fall out of love.,Mogą się odkochać.,2.000000
427879,"Well, there is some ale in the kitchen if you ...","Mamy w kuchni trochę piwa, jeśli chcecie...",2.000000
295928,"Remember that, Tokyo.",Pamiętaj Tokyo.,1.500000
69092,What are you so nervous about?,Co się tak stresujesz?,1.500000
282284,Amen.,Amen.,1.000000
131375,"Yes, sir, but...","Tak, proszę pana, aIe...",0.750000
320756,"Yes, it bows in sorrow.","Tak, pochyla się ze smutku.",1.000000
317388,That's got nothing to do with it.,To nie ma nic do rzeczy.,1.166667
80208,"A draper, a greengrocer, someone humble fit to...","Sukiennika, handlarza, kogoś pokornego, pasują...",1.250000
100196,He never did love me.,. Nigdy nie kochał mnie.,1.000000
394856,But I can't!,Ale nie mogę!,1.000000
333920,"Yes, thank you.","Tak, dziękuję.",1.500000
286358,"And to cinch it, I'll give him 50 percent.",Dla pewności dam mu 50.,1.800000
161537,One would be enough.,Wystarczyłby jeden.,2.000000
342785,"At your age, you best not be lifting things so...","W twoim wieku, nie powinieneś dźwigać takich c...",1.375000
205200,"We'll go wildcatting, huh?",Czy zrobimy dzikie wiercenie?,1.000000
35707,Thought you'd gone to bed.,"Myślałem, że poszłaś do łóżka.",1.000000
355234,"Please sit, we'll say hello later.","Siadajcie, później się przywitamy.",1.500000
136211,You can live like a great lord!,Możesz żyć jak wielki pan!,1.400000
55793,Come on.,Chodźcie.,2.000000
275039,I seem to have put my big foot in it.,Nie powinnam była się w to mieszać.,1.428571
343229,"You should be ashamed, throwing yourself at a ...","Wstydź się, rzucać się na takiego faceta.",1.571429
379554,"Come here, belle.","Chodź tu, Belle.",1.000000
16362,I got some surprise for you!,Mam dla ciebie niespodziankę!,1.500000
170558,Put the musket balls aside.,połóż je z boku.,1.250000
410483,I don't hear anything jingle.,Nie słyszę żadnego brzęczenia.,1.250000
353471,What a dumb town!,Co za głupie miasto!,1.000000
340538,The third remains.,Trzeci jeszcze nie.,1.000000
153637,The fight is over.,Walka skończona.,2.000000
469971,What's that supposed to mean?,Jak to?,2.500000
57371,How are you?,Jak się masz?,1.000000
375107,"You're not going to commit a second murder, Dr...","Dr Mercheson, nie zamierzasz chyba popełnić dr...",1.250000
135754,"Stay right where you are, countess.","Zostań tam, gdzie jesteś, hrabino.",1.200000
35493,I want you to give Dr. X full credit for trapp...,"Chcę, żebyś dał Doktorowi X, pełne uznanie za ...",1.200000
21003,Tell me.,Powiedz mi.,1.000000
56163,"Yes. When I was called, the girl had been dead...","Gdy mnie wezwano, dziewczyna była martwa 3, 4 ...",1.777778
61614,I finally found the coal man.,W końcu znalazłem dostawcę węgla.,1.200000
24169,"You're a man of the world, and you know that t...",Dokładnie tak. Jesteś człowiekiem światowym i ...,1.523810
216478,Just a few dissenters.,Kilku buntowników.,2.000000
25955,Women?,Kobiety?,1.000000
212461,"I mean, where are you sleeping?","To znaczy, gdzie śpisz?",1.500000
26492,Are you sure she's all right?,"Jesteś pewien, że wszystko w porządku?",1.000000
241279,Thank you.,Dziękuję.,2.000000

#### 2.8 Sentences starting with * fix

In [30]:
fix_star = lambda snt: re.sub(r"^ *[*].*", "", snt)
df_7['eng_text'] = df_7['eng_text'].apply(fix_star)
df_7['pol_text'] = df_7['pol_text'].apply(fix_star)

#### 2.9 Action Comments

In [31]:
def mask_distinct(df, col1, col2, chars):
    chars_escaped = "".join(re.escape(c) for c in chars)
    templ = f"[{chars_escaped}]"

    m1 = df[col1].str.contains(templ, regex=True, na=False)
    m2 = df[col2].str.contains(templ, regex=True, na=False)

    return m1 ^ m2

chars = '[]()/\*+#$"️'
mask = mask_distinct(df_7, "eng_text", "pol_text", chars)

df_8 = df_7[~mask].reset_index(drop=True)
df_8.shape

(467550, 3)

In [32]:
df_8.sample(50)

,eng_text,pol_text,len_ratio
198320,I know.,Wiem.,2.000000
4018,"It was very good advice, indeed.",Ta twoja rada doskonale się sprawdziła.,1.000000
421037,Truffles and champagne.,Trufle i szampan.,1.000000
89116,You sent for a manicurist?,Zamawiano tutaj manicure?,1.666667
107639,Please.,Proszę.,1.000000
301349,Where do we go?,Dokąd idziemy?,2.000000
67230,"That's a short jerky movement, like this.",To taki gwałtowny ruch.,1.750000
416361,"What's the matter, Mortimer?","o co chodzi, Mortimer?",1.000000
401008,Come on.,Wstawaj.,2.000000
464452,They said I'd never do it alone.,"Mówili, że nigdy nie zrobię tego sam.",1.000000
223787,Tell them which rooms they're to have.,Pani Imbrie i panu Connorowi. Musicie im przyd...,0.777778
297878,You must have observed him for months.,Musiał pan go obserwować od kilku miesięcy.,1.000000
107890,"Pass the sugar, lover.","Podaj cukier, kochany.",1.333333
425603,! -Two!,Dwa!,2.000000
316423,"Franz Gruber, first violin in the first stater...","Franz Gruber, pierwszy skrzypek w I klasie na ...",1.200000
427810,"How old are you, Alfred?","Ile masz lat, Alfred?",1.250000
5674,Take Gunther's form and break Brunhild's iron ...,Przybierz postać Gunthera i złam żelazną wolę ...,1.000000
362245,I'm not a murderer.,Nie jestem mordercą.,1.333333
203418,Hi.,Cześć.,1.000000
139140,"""This is not according to form.","""To wbrew normalnej praktyce.",1.500000
132363,Oh.,Och.,1.000000
317096,And it's women and children first!,"A to oznacza, że wpierw kobiety i dzieci!",0.750000
405875,Breaks a glass.,Tłuką szkło.,1.500000
439494,"Oh, I don't know.",Sama nie wiem.,1.333333
129191,"Ahoy there, on the mud scow.","Ahoj, załogo zakichanej łodzi.",1.500000
184486,Hiding on the moor ever since.,Od tego czasu ukrywał się na wrzosowiskach.,0.857143
345293,Come in.,Proszę wejść.,1.000000
275192,"Oh, I don't know, he didn't leave word.","Nie wiem, nie powiedział ani słowa.",1.333333
344431,"No, seriously, Pam.",Bądź poważna.,1.500000
227416,"This way, sir.","Tędy, sir.",1.500000
259237,Shall I call the police?,Może zadzwonimy na policję?,1.250000
155962,"In life, I was your partner, Jacob Marley.","Za życia byłem twoim wspólnikiem, Jakubem Marl...",1.142857
199563,"Miriam, how's matrimony? Still making a go of it?","Miriam, wciąż bawi cię małżeństwo?",1.800000
282332,"Be good. Say your prayers, Camille.","Do zobaczenia, Camille.",2.000000
141872,In all sorts of ways.,Na różne sposoby.,1.666667
55820,I'm celebrating.,Świętuję.,2.000000
323101,And right then it came over me that I hadn't w...,"W pewnej chwili dotarło do mnie, że niczego ta...",1.347826
119508,"Nothing very hopeful, Chief.","Nic napawającego otuchą, szefie.",1.000000
254659,He's a terrible example of places like Marysport.,Jest okropnym przykładem miejsc takich jak Mar...,1.142857
157738,You needn't have asked.,Nie musisz o to prosić.,0.800000
404247,You've been driving almost 10 hours.,Prowadzisz prawie od 10 godzin.,1.200000
184340,Jack has some theory about them.,Jack ma na ten temat teorię.,1.000000
441215,Have it sounded.,Proszę zagrać.,1.500000
363111,Good.,Dobrze.,1.000000
467040,"I want to take you with me, now that I know wh...","Teraz, gdy cię poznałem, chcę zabrać cię ze sobą.",1.555556
232453,But I don't want to get it by double-crossing ...,Ale nie mogę zawieść Joe.,2.000000
150982,Give him the dough.,"Daj mu forsę, powiedziałem.",1.000000
160502,"Perfectly, and thank you very much, gentlemen.",Oczywiście. Dziękuję bardzo.,2.333333
131010,"We're just terribly hurt, that's all.",Bardzo nas zraniono.,2.000000
298417,MAYBE IF WE GOT A PILE OF FEATHERS AND MADE HI...,Może gdybyśmy mieli mnóstwo piór... i sprawili...,1.636364

#### 2.10  " ` " ---> " ' " & del " ~ "

In [87]:
wanted_case = '`'
mask = df_8["eng_text"].apply(lambda x: wanted_case in x)
df_8[mask]

,eng_text,pol_text,len_ratio
214145,"Revolution had broken out, her diplomats sued ...","Rewolucja na tyłach frontu, dąży do zawarcia p...",1.277778
214152,We`ll examine it.,Zbadajmy go.,1.500000
214157,What do you think you`re doing?,Wstawaj! Co ty robisz?,1.500000
214161,Where`s your hand grenade?,Gdzie masz swój granat?,1.000000
214163,Let `em have it!,Niech je poczują!,1.333333
...,...,...,...
214943,We don`t want to hate one another.,Bez nienawiści ani pogardy.,1.750000
214944,There`s room for everyone.,Każdy ma swe miejsce.,1.000000
214947,"Greed has poisoned men`s souls, has barricaded...","Chciwość zatruła nasze dusze, wzniosła mury ni...",1.333333
214963,You don`t hate.,Przestańcie nienawidzieć.,1.500000
214965,"Soldiers, don`t fight for slavery, fight for l...","Nie walczcie o niewolę, lecz o wolność!",1.142857

In [88]:
df_8["eng_text"] = df_8["eng_text"].str.replace("`", "'", regex=False)
df_8["pol_text"] = df_8["pol_text"].str.replace("`", "'", regex=False)

In [95]:
df_8["eng_text"] = df_8["eng_text"].str.replace("~", "", regex=False)
df_8["pol_text"] = df_8["pol_text"].str.replace("~", "", regex=False)

#### 2.11 Del rows with specific case

In [216]:
def del_row_with_char(df, eng_col, pol_col, chars):
    df_proc = df.copy()
    for char in chars:
        mask1 = df_proc[eng_col].apply(lambda x: char in x)
        mask2 = df_proc[pol_col].apply(lambda x: char in x)
        df_proc = df_proc[~(mask1 | mask2)].reset_index(drop=True)
    return df_proc
    

chars = "=+*@#;|_}{"
df_9 = del_row_with_char(df_8, "eng_text", "pol_text", chars)

#### 2.12 Del rows with dialog -

In [217]:
mask1 = df_9["eng_text"].apply(lambda x: bool(re.search(r' +-[^ ]+', x)))
mask2 = df_9["pol_text"].apply(lambda x: bool(re.search(r' +-[^ ]+', x)))
df_data = df_9[~(mask1 | mask2)].reset_index(drop=True)

#### 3. Data Tokenization

In [287]:
uniq_cases = set("".join(df_data["eng_text"].astype(str)))
tab1 = sorted(list(uniq_cases), reverse=True)
print(tab1)

['z', 'y', 'x', 'w', 'v', 'u', 't', 's', 'r', 'q', 'p', 'o', 'n', 'm', 'l', 'k', 'j', 'i', 'h', 'g', 'f', 'e', 'd', 'c', 'b', 'a', ']', '[', 'Z', 'Y', 'X', 'W', 'V', 'U', 'T', 'S', 'R', 'Q', 'P', 'O', 'N', 'M', 'L', 'K', 'J', 'I', 'H', 'G', 'F', 'E', 'D', 'C', 'B', 'A', '?', ':', '9', '8', '7', '6', '5', '4', '3', '2', '1', '0', '/', '.', '-', ',', ')', '(', "'", '%', '$', '"', '!', ' ']

In [288]:
uniq_cases = set("".join(df_data["pol_text"].astype(str)))
tab2 = sorted(list(uniq_cases), reverse=True)
print(tab2)

['ż', 'Ż', 'ź', 'Ź', 'ś', 'Ś', 'ń', 'Ń', 'ł', 'Ł', 'ę', 'Ę', 'ć', 'Ć', 'ą', 'Ą', 'ó', 'Ó', 'z', 'y', 'x', 'w', 'v', 'u', 't', 's', 'r', 'q', 'p', 'o', 'n', 'm', 'l', 'k', 'j', 'i', 'h', 'g', 'f', 'e', 'd', 'c', 'b', 'a', ']', '[', 'Z', 'Y', 'X', 'W', 'V', 'U', 'T', 'S', 'R', 'Q', 'P', 'O', 'N', 'M', 'L', 'K', 'J', 'I', 'H', 'G', 'F', 'E', 'D', 'C', 'B', 'A', '?', ':', '9', '8', '7', '6', '5', '4', '3', '2', '1', '0', '/', '.', '-', ',', ')', '(', "'", '%', '$', '"', '!', ' ']

In [421]:
def tokenize_eng(snt):
    snt = snt.lower()
    snt = re.sub("(?<! )'(?! )", r" '", snt)
    snt = re.sub(r"""([\]?:)\[(/\.\-,%\$"!])""", r" \1 ", snt)
    snt = re.sub(r"\s+", " ", snt).strip()
    return re.split(r'\s+', snt.strip())

In [419]:
def tokenize_pol(snt):
    snt = snt.lower()
    snt = re.sub(r"""([\]?:)\[(/\.\-,%\$"!])""", r" \1 ", snt)
    snt = re.sub(r"\s+", " ", snt).strip()
    return re.split(r'\s+', snt.strip())

In [425]:
df_data = df_data.drop(['len_ratio'], axis=1)

#### 3.1 Splitting and trimming on quantile

In [428]:
df_data['eng_split'] = df_data['eng_text'].apply(tokenize_eng)
df_data['pol_split'] = df_data['pol_text'].apply(tokenize_pol)
df_data.sample(10)

,eng_text,pol_text,eng_split,pol_split
194378,"Chuck, here's a grand from Moore.","Chuck, tu masz kasę od Moore'a.","[chuck, ,, here, 's, a, grand, from, moore, .]","[chuck, ,, tu, masz, kasę, od, moore'a, .]"
286480,Do you suppose he'll listen about Capt. Jack?,"Myślisz, że mnie wysłucha?","[do, you, suppose, he, 'll, listen, about, cap...","[myślisz, ,, że, mnie, wysłucha, ?]"
386683,"What'd you wish, Mary?",O czym pomyślałaś?,"[what, 'd, you, wish, ,, mary, ?]","[o, czym, pomyślałaś, ?]"
276449,Do I look all right?,Jak wyglądam?,"[do, i, look, all, right, ?]","[jak, wyglądam, ?]"
85599,Have you seen a ghost?,Zobaczyłeś ducha?,"[have, you, seen, a, ghost, ?]","[zobaczyłeś, ducha, ?]"
376404,"This way, please.","Tędy, proszę.","[this, way, ,, please, .]","[tędy, ,, proszę, .]"
108087,Good evening.,Dobry wieczór.,"[good, evening, .]","[dobry, wieczór, .]"
392987,Tell him the queen is dead.,Powiedz mu że królowa nie żyje.,"[tell, him, the, queen, is, dead, .]","[powiedz, mu, że, królowa, nie, żyje, .]"
193192,"Now, we'll fix this for you.",Poprawimy to dla ciebie.,"[now, ,, we, 'll, fix, this, for, you, .]","[poprawimy, to, dla, ciebie, .]"
9130,What'd he get in my way for?,To po co mi wchodzi w drogę?,"[what, 'd, he, get, in, my, way, for, ?]","[to, po, co, mi, wchodzi, w, drogę, ?]"

In [452]:
thres1 = df_data['eng_split'].str.len().quantile(0.99)
mask1 = df_data['eng_split'].str.len() > thres1

thres2 = df_data['pol_split'].str.len().quantile(0.99)
mask2 = df_data['pol_split'].str.len() > thres2
print(mask1.sum(), mask2.sum(), (mask1 | mask2).sum())

df_data = df_data[~(mask1 | mask2)].reset_index(drop=True)

4113 3960 5510

#### 3.2 BPE Init. Uniq_freq

In [467]:
uniq_freq_eng = Counter(df_data['eng_split'].explode())
uniq_freq_pol = Counter(df_data['pol_split'].explode())

In [476]:
min_freq = 1
sum(v for k, v in uniq_freq_eng.items() if v <= min_freq)

14144

In [479]:
print(len([k for k, v in uniq_freq_pol.items() if v <= min_freq]))

53192

In [472]:
len(uniq_freq_eng), uniq_freq_eng

(40087,
 Counter({'.': 435802,
          ',': 177291,
          'you': 134548,
          'i': 122767,
          'the': 89859,
          '?': 84640,
          'to': 73192,
          'a': 61661,
          "'s": 57045,
          'it': 55074,
          "'t": 50411,
          'that': 43020,
          'and': 41124,
          'of': 39514,
          'in': 32142,
          '!': 30794,
          'me': 29977,
          'what': 26868,
          'is': 26378,
          'he': 26149,
          'for': 23935,
          'we': 23370,
          'this': 20366,
          'your': 20158,
          'be': 20137,
          'my': 20105,
          "'ll": 20011,
          'have': 19830,
          'don': 18888,
          'do': 18663,
          'on': 18052,
          'no': 17694,
          "'m": 16935,
          'all': 16776,
          'but': 16067,
          'was': 15781,
          "'re": 15483,
          'with': 15435,
          'can': 15365,
          'here': 15059,
          'not': 14896,
          'are': 14431,
          'know': 14310,
          'there': 14310,
          'him': 14193,
          'get': 13469,
          'if': 12400,
          'well': 12155,
          'they': 11807,
          'now': 11736,
          "'ve": 11579,
          'like': 11372,
          'yes': 10842,
          'out': 10839,
          'she': 10741,
          'come': 10653,
          'go': 10570,
          'right': 10414,
          'so': 10352,
          'about': 10349,
          'at': 10100,
          'up': 9851,
          'oh': 9750,
          'will': 9685,
          'just': 9650,
          'see': 9619,
          'good': 9404,
          'her': 9170,
          'as': 9044,
          '"': 8870,
          'one': 8831,
          'got': 8827,
          'how': 8698,
          "'d": 7878,
          '-': 7821,
          'want': 7783,
          'think': 7743,
          'why': 7726,
          'his': 7396,
          'mr': 7390,
          'going': 7023,
          'did': 6784,
          'take': 6657,
          'them': 6612,
          'been': 6579,
          'when': 6444,
          'from': 6437,
          'let': 6379,
          'tell': 6330,
          'who': 6283,
          'where': 6175,
          'say': 6142,
          'very': 5833,
          'back': 5736,
          'man': 5539,
          'time': 5538,
          'look': 5465,
          'an': 5437,
          'had': 5395,
          'too': 5297,
          'us': 5228,
          'would': 5165,
          'never': 5037,
          'didn': 4959,
          'were': 4912,
          'sir': 4907,
          'little': 4764,
          'way': 4572,
          'or': 4571,
          'then': 4556,
          'some': 4544,
          'down': 4510,
          'must': 4353,
          'any': 4343,
          'make': 4312,
          'only': 4213,
          'could': 4125,
          'more': 4078,
          'by': 4064,
          'has': 4035,
          'something': 4018,
          'thank': 3991,
          'our': 3987,
          'over': 3933,
          'give': 3923,
          'won': 3826,
          'much': 3806,
          'sure': 3682,
          'please': 3634,
          'night': 3541,
          'better': 3447,
          'yeah': 3404,
          'nothing': 3379,
          'anything': 3219,
          'away': 3136,
          'two': 3114,
          'mean': 3060,
          'old': 3053,
          'off': 3035,
          'love': 3028,
          'hello': 3018,
          'am': 2934,
          'miss': 2929,
          'before': 2916,
          'said': 2882,
          'again': 2882,
          'find': 2839,
          'should': 2800,
          'long': 2767,
          'isn': 2738,
          'thing': 2720,
          'sorry': 2676,
          'help': 2667,
          'after': 2623,
          'thought': 2600,
          'put': 2573,
          'home': 2550,
          'than': 2528,
          'ever': 2525,
          'first': 2521,
          'people': 2514,
          'father': 2502,
          'things': 2447,
          'always': 2424,
          'those': 2422,
          'maybe': 2417,
          'day': 2410,
          'keep': 2393,
          'talk': 2389,
          'into': 2380,
          'gonna': 2372,
          'mrs': 2366,
          'told': 2360,
          'wait': 2348,
          'mind': 2339,
          'ain': 2336,
          'because': 2327,
          'last': 2314,
          'may': 2299,
          'leave': 2297,
          'these': 2289,
          'other': 2277,
          'dear': 2255,
          'around': 2245,
          'life': 2245,
          'even': 2242,
          'course': 2213,
          'money': 2207,
          'wouldn': 2160,
          'new': 2154,
          'morning': 2147,
          'really': 2098,
          'name': 2067,
          'nice': 2061,
          'matter': 2051,
          'everything': 2034,
          'might': 2030,
          'work': 2029,
          'haven': 2015,
          'still': 2010,
          ':': 1991,
          'enough': 1989,
          'place': 1966,
          'girl': 1956,
          'men': 1953,
          'doing': 1934,
          'does': 1933,
          'call': 1911,
          'thanks': 1896,
          'hey': 1882,
          'need': 1876,
          'stay': 1861,
          'stop': 1823,
          'house': 1787,
          'came': 1777,
          'remember': 1771,
          'years': 1757,
          'ask': 1757,
          'another': 1757,
          'room': 1751,
          'hear': 1737,
          'yourself': 1734,
          'through': 1734,
          'boy': 1733,
          'afraid': 1721,
          'doesn': 1714,
          'understand': 1690,
          'made': 1681,
          'done': 1673,
          'their': 1670,
          'big': 1668,
          'coming': 1659,
          'believe': 1656,
          'great': 1653,
          'mother': 1653,
          'left': 1651,
          'feel': 1647,
          'tonight': 1646,
          'every': 1620,
          'couldn': 1609,
          'shall': 1607,
          'bad': 1605,
          'kind': 1582,
          'own': 1565,
          'three': 1553,
          'woman': 1527,
          'care': 1511,
          'darling': 1498,
          'listen': 1496,
          'doctor': 1493,
          'wanted': 1492,
          'myself': 1484,
          'friend': 1474,
          'lot': 1456,
          'seen': 1455,
          'once': 1446,
          'minute': 1438,
          'else': 1430,
          'world': 1412,
          'business': 1411,
          'heard': 1410,
          'such': 1395,
          'fine': 1394,
          'tomorrow': 1389,
          'pretty': 1388,
          'dr': 1385,
          'sit': 1383,
          'show': 1372,
          'lady': 1363,
          'wife': 1361,
          'try': 1354,
          'alone': 1343,
          'quite': 1341,
          'hope': 1335,
          'young': 1328,
          'bring': 1313,
          'dead': 1312,
          'wasn': 1303,
          'knew': 1299,
          'yet': 1295,
          'without': 1287,
          'guess': 1284,
          'same': 1282,
          'being': 1270,
          'getting': 1264,
          'idea': 1260,
          'live': 1252,
          'looking': 1236,
          'wrong': 1236,
          'suppose': 1234,
          'wish': 1231,
          'happened': 1229,
          'while': 1227,
          'happy': 1224,
          'saw': 1218,
          'boys': 1213,
          'along': 1201,
          'most': 1192,
          'went': 1188,
          'soon': 1187,
          'drink': 1172,
          'found': 1165,
          'guy': 1156,
          'trouble': 1153,
          'next': 1141,
          'gone': 1138,
          'best': 1125,
          'uh': 1121,
          'until': 1115,
          'gentlemen': 1115,
          'town': 1112,
          'head': 1109,
          'days': 1107,
          'since': 1104,
          'few': 1104,
          'glad': 1102,
          'today': 1097,
          'job': 1096,
          'many': 1095,
          'married': 1092,
          'ready': 1087,
          'whole': 1083,
          'trying': 1077,
          'hold': 1076,
          'talking': 1070,
          'run': 1068,
          'forget': 1041,
          'perhaps': 1038,
          'hand': 1033,
          'waiting': 1030,
          'use': 1029,
          'stand': 1023,
          'captain': 1019,
          'says': 1018,
          'mine': 1016,
          'kill': 996,
          'which': 994,
          'okay': 993,
          'meet': 992,
          'evening': 984,
          'open': 981,
          'used': 973,
          'together': 968,
          'huh': 967,
          'wants': 963,
          'play': 961,
          'ago': 957,
          'somebody': 956,
          'police': 954,
          'beautiful': 952,
          'case': 944,
          'send': 944,
          'aren': 943,
          'worry': 927,
          'husband': 924,
          'took': 924,
          'killed': 921,
          'pay': 918,
          'chance': 918,
          'door': 913,
          'nobody': 906,
          'poor': 903,
          'hurry': 898,
          'water': 896,
          'under': 892,
          'son': 890,
          'friends': 883,
          'later': 879,
          'turn': 875,
          'word': 871,
          'speak': 869,
          'sleep': 861,
          'start': 860,
          'both': 858,
          'late': 855,
          'someone': 853,
          'hands': 852,
          'five': 852,
          'yours': 844,
          'face': 835,
          'heart': 835,
          'excuse': 835,
          'country': 830,
          'everybody': 830,
          'easy': 829,
          'wonderful': 829,
          'far': 826,
          'death': 822,
          'rest': 819,
          'moment': 811,
          'baby': 809,
          'car': 807,
          'against': 807,
          'looks': 803,
          'comes': 803,
          'thinking': 800,
          'war': 795,
          'knows': 793,
          'rather': 791,
          'gave': 790,
          'hard': 788,
          'eyes': 788,
          'anybody': 787,
          'read': 787,
          'lost': 783,
          'watch': 782,
          'hurt': 780,
          'brother': 777,
          'ought': 775,
          'bed': 774,
          'anyone': 765,
          'certainly': 765,
          'fight': 763,
          'bit': 763,
          'god': 760,
          'child': 759,
          'half': 755,
          'kid': 755,
          'goodbye': 752,
          'each': 751,
          'till': 750,
          'happen': 743,
          'year': 737,
          'marry': 734,
          'true': 733,
          'eat': 726,
          "'em": 718,
          'die': 717,
          'anyway': 717,
          'ahead': 717,
          'sister': 715,
          'makes': 713,
          'gun': 712,
          'brought': 706,
          'seems': 705,
          'end': 700,
          'office': 700,
          'minutes': 700,
          'l': 699,
          'four': 695,
          'taking': 692,
          'dinner': 691,
          'train': 690,
          'ma': 688,
          'women': 687,
          'funny': 685,
          'fire': 685,
          'monsieur': 683,
          'fool': 681,
          'change': 681,
          'goes': 679,
          'already': 678,
          'crazy': 676,
          'asked': 672,
          'george': 670,
          'important': 668,
          'quiet': 667,
          'gotta': 662,
          'fellow': 660,
          'joe': 660,
          'bet': 659,
          'called': 645,
          'luck': 642,
          "'": 642,
          'story': 641,
          'break': 637,
          'hour': 636,
          'buy': 635,
          'having': 633,
          'law': 631,
          'o': 629,
          'sent': 629,
          'children': 627,
          'met': 626,
          '10': 626,
          'shot': 626,
          'answer': 624,
          'week': 622,
          'sort': 621,
          'walk': 619,
          'king': 618,
          'means': 617,
          'real': 615,
          'tried': 609,
          'hate': 603,
          'gets': 600,
          'leaving': 600,
          'daughter': 598,
          'bill': 598,
          'times': 597,
          'almost': 594,
          'ah': 594,
          'reason': 592,
          'family': 590,
          'horse': 588,
          'move': 584,
          'shouldn': 583,
          'probably': 582,
          'shut': 582,
          'ya': 582,
          'himself': 579,
          'couple': 578,
          'letter': 577,
          'tired': 576,
          'professor': 572,
          'exactly': 570,
          'wonder': 570,
          'part': 569,
          'wanna': 569,
          'lord': 568,
          'either': 567,
          'boat': 566,
          'dance': 565,
          'making': 562,
          'known': 562,
          'john': 562,
          'free': 562,
          'set': 560,
          'madame': 560,
          'hotel': 560,
          'full': 558,
          'cut': 558,
          'party': 558,
          'cold': 557,
          'lovely': 557,
          'uncle': 556,
          'close': 554,
          'ship': 554,
          'afternoon': 549,
          'telling': 548,
          'truth': 548,
          'city': 542,
          'seem': 540,
          'side': 538,
          'six': 536,
          'number': 534,
          'murder': 533,
          'tom': 531,
          'order': 531,
          'dog': 531,
          'pardon': 530,
          'saying': 525,
          'honey': 525,
          'save': 524,
          'paris': 524,
          'write': 522,
          'general': 521,
          'hours': 521,
          'york': 519,
          '00': 518,
          'expect': 516,
          'alright': 514,
          'months': 513,
          'taken': 512,
          'hit': 512,
          'johnny': 510,
          'between': 508,
          'eh': 508,
          'light': 506,
          'boss': 506,
          'different': 505,
          'blood': 498,
          'quick': 498,
          '000': 498,
          'jim': 497,
          'safe': 493,
          'clear': 493,
          'alive': 493,
          'though': 492,
          'hat': 490,
          'silly': 486,
          'working': 485,
          'outside': 484,
          'hot': 484,
          'mary': 484,
          'frank': 484,
          'behind': 483,
          'its': 482,
          'plenty': 481,
          'anymore': 481,
          'catch': 479,
          'high': 478,
          'living': 477,
          'sick': 476,
          'charles': 476,
          'line': 474,
          'sometimes': 473,
          'others': 472,
          'shoot': 471,
          'girls': 470,
          'forgive': 469,
          'news': 468,
          'mad': 464,
          'careful': 463,
          'also': 463,
          'fact': 461,
          'street': 461,
          'lose': 460,
          'land': 458,
          'clothes': 457,
          'gentleman': 457,
          'red': 456,
          'colonel': 455,
          'company': 455,
          'henry': 455,
          'book': 454,
          'front': 454,
          'question': 454,
          'sweet': 453,
          'least': 452,
          'longer': 452,
          'started': 451,
          'strange': 451,
          'running': 450,
          'able': 450,
          'bye': 450,
          'second': 449,
          'died': 449,
          'doc': 449,
          'white': 445,
          'promise': 443,
          'school': 443,
          'fun': 442,
          'nick': 441,
          'stuff': 440,
          'deal': 439,
          'picture': 439,
          'guys': 436,
          'master': 436,
          'phone': 434,
          'hasn': 430,
          'christmas': 428,
          'throw': 426,
          'pick': 425,
          'except': 422,
          'army': 420,
          'orders': 419,
          'trust': 418,
          'inside': 418,
          'point': 417,
          'awful': 417,
          'follow': 416,
          'thousand': 416,
          'weeks': 416,
          'ten': 416,
          'words': 416,
          'hadn': 415,
          'feeling': 413,
          'worth': 413,
          "'am": 413,
          'present': 411,
          'feet': 411,
          'sam': 411,
          'body': 410,
          'changed': 410,
          'happens': 409,
          'music': 407,
          'coffee': 405,
          'lie': 404,
          'yesterday': 404,
          'ride': 402,
          'cannot': 400,
          'game': 399,
          'weren': 398,
          'drive': 392,
          'none': 391,
          'everyone': 391,
          '1': 390,
          'beat': 390,
          'lucky': 390,
          'black': 388,
          'loved': 388,
          'sing': 388,
          'miles': 387,
          'whatever': 387,
          'across': 387,
          'madam': 387,
          'mistake': 387,
          'looked': 386,
          'paper': 385,
          'judge': 384,
          'aunt': 382,
          'person': 381,
          'lives': 380,
          'carry': 380,
          'ladies': 380,
          'asking': 380,
          'sense': 378,
          'court': 378,
          'hi': 378,
          'honor': 377,
          'sell': 376,
          'touch': 376,
          'charlie': 375,
          'hang': 374,
          'interested': 373,
          'road': 373,
          'air': 372,
          'dress': 372,
          'american': 367,
          'somewhere': 366,
          'sign': 365,
          'scared': 365,
          'pull': 364,
          'act': 364,
          'food': 362,
          'kids': 361,
          'london': 361,
          'table': 360,
          'small': 359,
          'papers': 358,
          'coat': 358,
          'fault': 357,
          'playing': 357,
          'secret': 356,
          'drop': 356,
          'hair': 356,
          'duty': 355,
          'state': 354,
          'wear': 354,
          'eye': 353,
          'kept': 353,
          'paul': 353,
          'jack': 353,
          'folks': 352,
          'kiss': 351,
          'check': 350,
          'pleasure': 350,
          'given': 349,
          'busy': 349,
          'tough': 349,
          'england': 349,
          'fast': 348,
          'unless': 348,
          'trip': 346,
          'sound': 346,
          'terrible': 346,
          'eddie': 345,
          'near': 344,
          'possible': 344,
          'upon': 344,
          'become': 343,
          'fix': 343,
          'step': 340,
          'mustn': 340,
          'count': 339,
          'forgot': 338,
          '20': 338,
          'drunk': 338,
          'early': 337,
          'seeing': 337,
          'worried': 337,
          'earth': 336,
          'smart': 336,
          'straight': 335,
          'takes': 335,
          'caught': 334,
          'de': 334,
          'dad': 334,
          'besides': 332,
          'sea': 332,
          '30': 332,
          'cross': 331,
          'welcome': 330,
          'dark': 330,
          'horses': 329,
          'fall': 329,
          'fair': 329,
          'wedding': 328,
          'imagine': 327,
          'stick': 326,
          'pass': 325,
          'grand': 324,
          'majesty': 324,
          'difference': 323,
          'win': 323,
          'ring': 322,
          'worse': 322,
          'dream': 320,
          'sounds': 319,
          'swell': 319,
          'window': 318,
          'soul': 318,
          'learn': 318,
          'gold': 317,
          'marriage': 316,
          'return': 315,
          'finished': 315,
          'human': 314,
          'giving': 313,
          'france': 313,
          'hungry': 312,
          'mighty': 312,
          '3': 311,
          'serious': 310,
          'meant': 309,
          'promised': 309,
          'lieutenant': 309,
          'figure': 309,
          'station': 308,
          'devil': 308,
          'born': 308,
          'simple': 308,
          'past': 308,
          'hundred': 307,
          'laugh': 306,
          'explain': 306,
          'piece': 306,
          'peace': 305,
          'cry': 304,
          'heaven': 303,
          'clean': 303,
          'calling': 301,
          'interesting': 301,
          'sergeant': 301,
          'certain': 300,
          'fella': 300,
          'broke': 299,
          '5': 298,
          'often': 298,
          'supposed': 297,
          'charge': 296,
          'questions': 296,
          'hospital': 296,
          'finish': 295,

In [473]:
len(uniq_freq_pol), uniq_freq_pol

(113603,
 Counter({'.': 413780,
          ',': 183948,
          '?': 83444,
          'nie': 82694,
          'to': 53190,
          'się': 47857,
          'w': 33288,
          '!': 29675,
          'na': 29617,
          'i': 28962,
          'że': 27810,
          'z': 26468,
          'tak': 24059,
          'jest': 23868,
          'co': 23351,
          'do': 21754,
          'o': 16448,
          'jak': 16207,
          'mnie': 14640,
          'ale': 14296,
          'mi': 12232,
          'a': 11634,
          'pan': 11472,
          'za': 10597,
          'go': 9391,
          'czy': 9083,
          '"': 8717,
          'ci': 8337,
          'tu': 7998,
          'ja': 7969,
          'pani': 7754,
          'może': 7525,
          'tego': 7476,
          'cię': 7454,
          'tym': 7440,
          'mam': 7102,
          'jestem': 7090,
          'dla': 6931,
          'ma': 6643,
          'już': 6606,
          'tylko': 6593,
          'jeśli': 6583,
          'proszę': 6547,
          'po': 6435,
          'teraz': 6140,
          'ty': 6021,
          'jesteś': 5837,
          'dobrze': 5655,
          'od': 5461,
          'będzie': 5401,
          'bardzo': 5288,
          'coś': 5272,
          'nic': 5194,
          'wszystko': 5049,
          'wiem': 4956,
          'tam': 4912,
          'panie': 4737,
          'ten': 4723,
          'gdzie': 4633,
          'masz': 4603,
          'być': 4487,
          'kiedy': 4437,
          'mogę': 4415,
          'ciebie': 4317,
          'on': 4269,
          'są': 3986,
          'ze': 3971,
          'dziękuję': 3968,
          'jej': 3944,
          'jeszcze': 3836,
          'dlaczego': 3793,
          'był': 3758,
          'chcę': 3705,
          'jego': 3697,
          'ją': 3656,
          'pana': 3534,
          'tutaj': 3524,
          'sobie': 3472,
          'by': 3443,
          'nigdy': 3403,
          'więc': 3348,
          'też': 3344,
          'mu': 3255,
          'mój': 3232,
          'prawda': 3163,
          'było': 3061,
          'przez': 3050,
          'nas': 3005,
          'wiesz': 2926,
          'kto': 2911,
          'żeby': 2907,
          'chcesz': 2860,
          'ich': 2855,
          'będę': 2847,
          'możesz': 2813,
          'domu': 2770,
          'moja': 2602,
          'dobry': 2548,
          'zawsze': 2465,
          'muszę': 2425,
          'lepiej': 2390,
          'zrobić': 2386,
          'chyba': 2373,
          'och': 2365,
          'nim': 2363,
          'gdy': 2329,
          'tej': 2206,
          'je': 2188,
          'oczywiście': 2185,
          'nawet': 2165,
          'niech': 2120,
          'bo': 2119,
          'tobą': 2111,
          'trochę': 2088,
          'ona': 2076,
          'porządku': 2063,
          'no': 2062,
          'te': 2042,
          '-': 2036,
          'mamy': 2003,
          'bez': 1997,
          'powiedzieć': 1990,
          'moje': 1981,
          'chce': 1955,
          'przepraszam': 1955,
          'właśnie': 1950,
          'więcej': 1940,
          'mną': 1938,
          'była': 1914,
          'chodź': 1911,
          'sam': 1907,
          ':': 1888,
          'kochanie': 1888,
          'cóż': 1861,
          'dzień': 1841,
          'myślę': 1798,
          'naprawdę': 1761,
          'sir': 1753,
          'będziesz': 1738,
          'chodzi': 1725,
          'nam': 1716,
          'niż': 1707,
          'który': 1690,
          'dziś': 1684,
          'niego': 1668,
          'musisz': 1666,
          'wszyscy': 1662,
          'ta': 1662,
          'twój': 1622,
          'ktoś': 1612,
          'musi': 1607,
          'powiedz': 1589,
          'czego': 1569,
          'aby': 1564,
          'przed': 1554,
          'razem': 1554,
          'raz': 1550,
          'stało': 1514,
          'jesteśmy': 1487,
          'miał': 1480,
          'dobra': 1467,
          'czas': 1458,
          'pewnie': 1445,
          'czemu': 1443,
          'powiedział': 1442,
          'panu': 1442,
          'myślisz': 1434,
          'rzeczy': 1428,
          'dalej': 1391,
          'dzięki': 1384,
          'możemy': 1343,
          'zbyt': 1335,
          'przy': 1334,
          'wie': 1334,
          'lat': 1329,
          'was': 1317,
          'tę': 1316,
          'taki': 1310,
          'rozumiem': 1302,
          'cześć': 1302,
          'stąd': 1289,
          'życie': 1281,
          'tych': 1278,
          'mówi': 1278,
          'nikt': 1274,
          'musimy': 1266,
          'myśli': 1260,
          'dobranoc': 1254,
          'ludzi': 1247,
          'czym': 1247,
          'czasu': 1240,
          'temu': 1237,
          'jeden': 1237,
          'twoje': 1233,
          'daj': 1231,
          'ludzie': 1228,
          'jutro': 1224,
          'moim': 1218,
          'zobaczyć': 1218,
          'dużo': 1213,
          'wiele': 1203,
          'im': 1183,
          'dwa': 1164,
          'twoja': 1157,
          'szybko': 1153,
          'mieć': 1152,
          'ani': 1149,
          'siebie': 1147,
          'pod': 1129,
          'skąd': 1121,
          'nadzieję': 1114,
          'będziemy': 1112,
          'byłem': 1107,
          'u': 1107,
          'można': 1100,
          'hej': 1099,
          'długo': 1099,
          'potem': 1098,
          'chciałbym': 1095,
          'kim': 1090,
          'nią': 1090,
          'zaraz': 1090,
          'mojego': 1085,
          'człowiek': 1080,
          'powiem': 1078,
          'kilka': 1065,
          'albo': 1061,
          'gdyby': 1056,
          'mojej': 1037,
          'prostu': 1036,
          'panowie': 1035,
          'niej': 1032,
          'miejsce': 1029,
          'ile': 1024,
          'iść': 1015,
          'pieniądze': 1011,
          'wtedy': 1011,
          'nocy': 1008,
          'doktorze': 1008,
          'takie': 1006,
          'swoje': 998,
          'wygląda': 996,
          'kiedyś': 990,
          'tobie': 987,
          'dlatego': 986,
          'trzeba': 982,
          'zanim': 978,
          'panno': 977,
          'które': 976,
          'wszystkie': 973,
          'idź': 971,
          'znaczy': 967,
          'sposób': 967,
          'wiedzieć': 956,
          'myślałem': 952,
          'cały': 950,
          'przykro': 945,
          'moją': 944,
          'aż': 943,
          'jako': 940,
          'panią': 939,
          'pomóc': 935,
          'widzę': 935,
          'takiego': 925,
          'dzisiaj': 921,
          'wam': 917,
          'oni': 912,
          'znowu': 912,
          'mówić': 900,
          'widziałem': 898,
          'pewno': 887,
          'jaki': 885,
          'wszystkich': 884,
          'chwilę': 884,
          'tyle': 879,
          'zostać': 879,
          'nich': 879,
          'miło': 879,
          'jasne': 875,
          'wieczór': 875,
          'miałem': 873,
          'mówię': 868,
          'mówisz': 865,
          'widzisz': 861,
          'robisz': 854,
          'mógł': 847,
          'rację': 840,
          'trzy': 836,
          'znam': 834,
          'będą': 834,
          'dni': 834,
          'sama': 828,
          'pokoju': 826,
          'my': 826,
          'witaj': 822,
          'bardziej': 820,
          'ojciec': 814,
          'spójrz': 810,
          'żebyś': 805,
          'dom': 804,
          'nad': 803,
          'kocham': 793,
          'razie': 793,
          'robić': 787,
          'sie': 784,
          'mają': 780,
          'dnia': 779,
          'pracy': 777,
          'taka': 776,
          'lub': 774,
          'swoją': 773,
          'później': 772,
          'dziecko': 769,
          'dzieci': 767,
          'drzwi': 761,
          'bądź': 758,
          'która': 754,
          'nami': 754,
          'droga': 753,
          'stary': 750,
          'robi': 750,
          'lubię': 745,
          'bym': 743,
          'dość': 743,
          'powiedziałem': 742,
          'rano': 736,
          'zrobię': 732,
          'każdy': 728,
          'twoim': 725,
          'drogi': 717,
          'dzieje': 714,
          'oto': 714,
          'pomysł': 711,
          'jakie': 709,
          'chciałem': 706,
          'pierwszy': 705,
          'jakieś': 704,
          'samo': 701,
          'cieszę': 699,
          'podoba': 697,
          'kogoś': 696,
          'gdybym': 695,
          'widzieć': 694,
          'jakiś': 688,
          'chodźmy': 686,
          'zrobił': 679,
          'wcześniej': 676,
          'wciąż': 673,
          'mów': 671,
          'stanie': 669,
          'życia': 667,
          'czuję': 665,
          '10': 658,
          'pójdę': 656,
          'dobre': 655,
          'został': 653,
          'pieniędzy': 652,
          'znaleźć': 652,
          'musiał': 652,
          'człowieka': 652,
          'twojej': 650,
          'nasz': 648,
          'weź': 646,
          'chciał': 645,
          'wieczorem': 644,
          'posłuchaj': 643,
          'sprawa': 641,
          'wszystkim': 641,
          'noc': 639,
          'tą': 633,
          'kobiety': 632,
          'nasze': 627,
          'nadal': 624,
          'poza': 621,
          'byłeś': 620,
          'porozmawiać': 618,
          'pewien': 617,
          'sobą': 617,
          'żyje': 615,
          'pozwól': 614,
          'we': 614,
          'źle': 611,
          'takim': 610,
          'witam': 609,
          'byłam': 606,
          'prawie': 604,
          'kapitanie': 602,
          'wczoraj': 601,
          'innego': 601,
          'wydaje': 599,
          'sądzę': 598,
          'mówiłem': 597,
          'panna': 596,
          'mamo': 592,
          'kobieta': 586,
          'wasza': 586,
          'moich': 585,
          'kogo': 579,
          'chłopcy': 578,
          'dokąd': 576,
          'panem': 576,
          'widzenia': 576,
          'dziewczyna': 574,
          'niczego': 574,
          'znasz': 572,
          'przecież': 571,
          'prawo': 570,
          'twoją': 569,
          'miała': 568,
          'którą': 565,
          'wystarczy': 565,
          'którzy': 558,
          'mały': 558,
          'byłoby': 557,
          'ojca': 557,
          'ponieważ': 556,
          'dr': 551,
          'nikogo': 550,
          'powinieneś': 545,
          'halo': 545,
          'słuchaj': 544,
          'żebym': 543,
          'twojego': 543,
          'roku': 542,
          'szczęście': 542,
          'facet': 538,
          'idę': 537,
          'dam': 537,
          'były': 535,
          'przeciwko': 535,
          'czegoś': 534,
          'mogą': 534,
          'da': 532,
          'przestań': 532,
          'minut': 530,
          'koniec': 529,
          'dać': 528,
          'całą': 525,
          'jedno': 523,
          'żona': 522,
          'wy': 522,
          'powiesz': 521,
          'żadnych': 521,
          'idzie': 520,
          'rozumiesz': 519,
          'zabrać': 519,
          'mówił': 519,
          'pracę': 518,
          'imię': 518,
          'pokój': 517,
          'joe': 517,
          'dwóch': 516,
          'znów': 515,
          'końcu': 515,
          'razy': 514,
          'pamiętasz': 514,
          'swój': 512,
          'ojcze': 508,
          'słyszałem': 508,
          'byś': 507,
          'gdzieś': 502,
          'jednak': 502,
          'powinienem': 502,
          'mąż': 501,
          'wiedziałem': 500,
          'powodu': 499,
          'wina': 499,
          'oczy': 497,
          'sprawy': 497,
          'świetnie': 496,
          'świecie': 496,
          'całkiem': 494,
          'powinien': 492,
          'obawiam': 491,
          'pamiętam': 491,
          'dwie': 490,
          'rzecz': 489,
          'nowy': 487,
          'powiedziałeś': 486,
          'którego': 486,
          'mógłbym': 483,
          'jednego': 483,
          'czeka': 482,
          'nowego': 481,
          'myślałam': 480,
          'nimi': 479,
          'wielu': 478,
          'wrócę': 474,
          'list': 472,
          'kiedykolwiek': 472,
          'ręce': 471,
          'swoim': 470,
          'wyglądasz': 470,
          'najpierw': 469,
          'szkoda': 466,
          'wejść': 465,
          'wyjść': 464,
          'chciałam': 462,
          'strony': 461,
          'macie': 461,
          'jaką': 460,
          'dopóki': 460,
          'powiedziała': 458,
          'miasta': 457,
          'broń': 457,
          'daleko': 457,
          'spokojnie': 456,
          'dokładnie': 453,
          'spać': 453,
          'takich': 452,
          'jedną': 452,
          'inaczej': 452,
          'słowa': 450,
          'natychmiast': 450,
          'wrócić': 446,
          'lata': 446,
          'martw': 446,
          'której': 443,
          'całe': 442,
          'jesteście': 442,
          'swojego': 440,
          'swojej': 439,
          'jedna': 439,
          'oh': 437,
          'sprawę': 436,
          'zabić': 433,
          'jakby': 433,
          'wybacz': 431,
          'przyjaciel': 431,
          'gdybyś': 429,
          '00': 427,
          'skoro': 426,
          'wody': 425,
          'doktor': 425,
          'żyć': 424,
          'madame': 422,
          'pięć': 420,
          'śmierć': 419,
          'idziemy': 419,
          'wiedział': 418,
          'serce': 418,
          'wysokość': 418,
          'miejscu': 417,
          'potrzebuję': 415,
          'czyż': 415,
          'trzymaj': 415,
          'ależ': 415,
          'johnny': 415,
          'chcemy': 413,
          'innych': 411,
          'chwili': 410,
          'zostaw': 409,
          'przyszedł': 409,
          'pomocy': 408,
          'zgadza': 406,
          'mógłby': 406,
          'także': 405,
          'zna': 405,
          'tato': 404,
          'spokój': 403,
          'zamknij': 402,
          'miejsca': 401,
          'matka': 400,
          'wielki': 400,
          'mogłem': 399,
          'numer': 399,
          'głowy': 399,
          'parę': 398,
          'poczekaj': 398,
          'słowo': 397,
          'każdym': 397,
          'którym': 396,
          'należy': 396,
          'późno': 396,
          'życiu': 396,
          'mieście': 395,
          'george': 395,
          'czekać': 393,
          'kłopoty': 392,
          'prawdę': 392,
          'inny': 391,
          'swoich': 391,
          'miałam': 391,
          'jechać': 391,
          'uważaj': 390,
          'mówią': 390,
          'wierzę': 390,
          'człowiekiem': 389,
          'żadnego': 387,
          '20': 386,
          'inne': 385,
          'śmierci': 385,
          'ach': 383,
          'mary': 383,
          'dostać': 382,
          'wcale': 382,
          'boże': 381,
          'john': 381,
          'byli': 379,
          'zostanie': 379,
          'widziałam': 379,
          'których': 378,
          'miłość': 378,
          'zrobi': 378,
          'piękna': 377,
          'idziesz': 377,
          'raczej': 377,
          'pół': 377,
          'chciałabym': 377,
          'zabierz': 377,
          'zrobisz': 375,
          'świat': 373,
          'jim': 373,
          'taką': 372,
          'zobaczenia': 372,
          'cztery': 371,
          'mężczyzna': 370,
          'widziałeś': 370,
          'cicho': 369,
          'ode': 368,
          'nazywa': 368,
          'boję': 368,
          'męża': 367,
          'zrobiłeś': 366,
          'zamierzam': 366,
          'zrób': 364,
          'wkrótce': 363,
          'prawa': 362,
          'powinniśmy': 362,
          'hotelu': 362,
          'rozmawiać': 361,
          'powrotem': 361,
          'statek': 361,
          '30': 360,
          'chłopcze': 359,
          'wróci': 359,
          'patrz': 359,
          'pewna': 358,
          'między': 357,
          'jeżeli': 356,
          'kapitan': 355,
          'wracaj': 354,
          'zrobiłem': 354,
          'pewnością': 354,
          'drodze': 354,
          'mała': 353,
          'zaczekaj': 352,
          'młody': 352,
          'tom': 351,
          'wziąć': 351,
          'ostatni': 351,
          'podczas': 351,
          'dopiero': 350,
          'stać': 349,
          'ciągle': 349,
          'kolację': 348,
          'twoich': 348,
          'mógłbyś': 348,
          'henry': 348,
          'wspaniale': 346,
          'naszym': 346,
          'dziwne': 346,
          'jednym': 344,
          'czasem': 344,
          'również': 344,
          'bill': 344,
          'miły': 343,
          'najbardziej': 343,
          'kochasz': 342,
          'odejść': 342,
          'naszego': 341,
          '3': 340,
          'godziny': 340,
          'samochód': 339,
          'dziewczyny': 339,
          'problem': 338,
          'piękne': 338,
          'przyjdzie': 337,
          'wszystkiego': 337,
          '2': 336,
          'każdego': 335,
          'sądzisz': 335,
          'czujesz': 334,
          '5': 334,
          'twarz': 333,
          'byłaś': 333,
          'zły': 332,
          'zatrzymać': 330,
          'ważne': 330,
          'rękę': 330,
          'poznać': 328,
          'możliwe': 328,
          'naszych': 327,
          'pewnego': 326,
          'robię': 326,
          'góry': 325,
          'policja': 325,
          'górę': 324,
          'jorku': 324,
          'kraju': 323,
          'zrobimy': 323,
          'nazwisko': 323,
          'usiądź': 323,
          'skarbie': 322,
          'mieli': 321,
          'powie': 321,
          'jaka': 321,
          'pociąg': 321,
          'moi': 320,
          'głowę': 320,
          'wiadomość': 319,
          'udało': 319,
          'widział': 319,
          'charles': 319,
          'wezmę': 318,
          'uda': 318,
          'mówiąc': 318,
          'wiedziałam': 318,
          'spotkać': 318,
          'policji': 317,
          'miasto': 316,
          'razu': 315,
          'zupełnie': 315,
          'zobaczysz': 310,
          'zabił': 309,
          'wystarczająco': 308,
          'mogła': 308,
          'dłużej': 308,
          'chwileczkę': 306,
          'ziemi': 305,
          'często': 305,
          'przynajmniej': 304,
          'zobaczymy': 304,
          'chcą': 303,
          'sprawie': 302,
          'miałeś': 302,
          'czasami': 302,
          'przynieś': 302,
          'możecie': 302,
          'naszej': 302,
          'zamiar': 302,
          'zabawne': 302,
          'nick': 302,
          'zobacz': 301,
          'cokolwiek': 301,
          'innym': 301,
          'frank': 301,
          'pomóż': 300,
          'pokażę': 299,
          'wiemy': 298,
          'wybaczyć': 298,
          'szansę': 297,
          'potrzebuje': 297,
          'trudno': 297,
          'nasza': 296,
          'drogę': 296,
          'wejdź': 296,
          'lecz': 296,
          'ślub': 295,
          'siadaj': 295,
          'żegnaj': 293,
          'choć': 292,
          'de': 292,
          'tędy': 292,
          'dał': 291,
          'gotowy': 291,
          'zostań': 291,
          'spokoju': 291,
          'nazywam': 290,
          'obchodzi': 290,
          'pójść': 290,
          'chciała': 290,
          'zobaczę': 289,
          'zostało': 289,
          '000': 289,
          'wspólnego': 289,
          'praca': 288,
          'cała': 288,
          'dół': 288,
          'powiedziałam': 288,
          'lubi': 287,
          'rób': 287,
          'mama': 286,
          'myśleć': 286,
          'powinnaś': 286,
          'inni': 286,
          'nowym': 286,
          'czuje': 285,
          'monsieur': 285,
          'bóg': 284,
          'spotkanie': 284,
          'chodźcie': 283,
          'świata': 283,
          'szczęśliwa': 283,
          'byliśmy': 283,
          'synu': 282,
          'przyjść': 282,
          'kocha': 281,
          'szybciej': 281,
          'zależy': 281,
          'lubisz': 280,
          'zewnątrz': 280,
          'została': 280,
          'trzech': 280,
          'stronie': 280,
          'strasznie': 279,
          'obiad': 278,
          'boisz': 278,

In [ ]:
df_data =

In [420]:
tokenize_pol('"To jedynie piąta klasa." Och, Juan, kiedy się pobierzemy?')

['"',
 'to',
 'jedynie',
 'piąta',
 'klasa',
 '.',
 '"',
 'och',
 ',',
 'juan',
 ',',
 'kiedy',
 'się',
 'pobierzemy',
 '?']

In [416]:
df_data['pol_text'].sample(30).iloc[10]

'"To jedynie piąta klasa." Och, Juan, kiedy się pobierzemy?'

In [300]:
test_snt2 = "Hmmm, 'cause?"
tokenize_eng(test_snt2)

"hmmm , 'cause ?"

In [221]:
mask = df_data["eng_text"].apply(lambda x: bool(re.search(r"[^ ]+'[^ ]+", x)))
df_data[mask]

,eng_text,pol_text,len_ratio
1,"Yeah, I want to tell him I'm okay.","Tak, powiem, że wszystko w porządku.",1.333333
4,"Elizabeth Keen is not your wife, she's your ta...","Elizabeth Keen nie jest twoją żoną, tylko celem.",1.125000
9,You'll be in America by morning.,Rano będziesz w USA.,1.500000
10,"We're taking you to Washington, D.C.",Zabieramy cię do Waszyngtonu.,1.500000
13,"Yes, we'll take care of it.",Dobrze. Zajmiemy się tym.,1.500000
...,...,...,...
466174,You haven't had a hint of a sneeze for over an...,Nie kichnąłeś już od godziny.,2.400000
466175,I'll bet you're sorry I'm not sneezing.,"Założę się, że się z tego cieszysz.",1.000000
466178,"You're tired, so am I.",Jesteś zmęczony i ja też.,1.000000
466181,What's the matter with...,Co jest z tą...,1.000000
466185,I really don't know what to think of Mr. Barre...,"Nie wiem, co mam sądzić o panu Barredout.",1.250000

In [289]:
wanted_case = '"'
mask = df_data["eng_text"].apply(lambda x: wanted_case in x)
df_data[mask]

,eng_text,pol_text,len_ratio
185,Because the only word I know that contains the...,"Bo jedyne znane mi słowo z literami ""v"" i ""g"" ...",1.166667
373,"""All that do so are abomination unto the Lord ...","""Te, które to uczynią, obrażą imię Pana, Boga ...",1.222222
494,I will be to this generation a second Mohammed...,"/Będę dla naszego pokolenia /drugim Mahometem,...",1.312500
543,"they would say, ""Shed my blood that I may be s...","""Przeleje swoją krew dla własnego ocalenia i m...",1.454545
628,"My father says, ""Judge not, lest ye be judged.""","Mój ojciec mawia: ""Nie osądzaj, żeby nie zosta...",1.000000
...,...,...,...
461740,"""Willie Stark.","""Willie Stark.",1.000000
461757,"""Voice in the wilderness.","""Wołający na puszczy.",1.333333
461856,"""My friends....","""Przyjaciele...",2.000000
462098,"""Clown, show-off, playboy,"" they yelled out.","""Klaun, playboy"", krzyczeli.",2.000000
465190,"I want ""Henrik"" engraved, with today's date.","Proszę wygrawerować ""Henrik"" i dzisiejszą datę.",1.166667