## 04. scratchpad

### 1. Data Upload

In [1]:
import pandas as pd
import os
from collections import defaultdict, Counter
import re

In [2]:
def upload_to_dataframe(root, files, num_lines):
    path_eng, path_pol = [root+f for f in files]
    data = defaultdict(list)
    
    with open (path_eng, encoding="utf_8") as f_eng, open (path_pol, encoding="utf_8") as f_pol:
        for _ in range(num_lines):
            data['eng_text'].append(f_eng.readline().strip())
            data['pol_text'].append(f_pol.readline().strip())
    return pd.DataFrame(data)

In [3]:
root = "../data/opus_opensub/en-pl.txt/"
files = ('OpenSubtitles.en-pl.en', '/OpenSubtitles.en-pl.pl')
df = upload_to_dataframe(root, files, 600000)

### 2. EDA & Sanitazation

#### 2.1 English Non-Ascii Sentences

In [4]:
def nonascii_list(df_series, is_pol):
    if is_pol:
        pl_chars = set("ąęćłńóśźżĄĘĆŁŃÓŚŹŻ")
        requir = lambda x: x.isascii() or x in pl_chars
    else:
        requir = lambda x: x.isascii()
        
    text_all = ''.join(df_series)
    unique_dct = {x for x in text_all if not requir(x)}
    return sorted(list(unique_dct))

In [5]:
print(nonascii_list(df['eng_text'], False))

['\x80', '\x81', '\x82', '\x83', '\x84', '\x85', '\x88', '\x8b', '\x8c', '\x8e', '\x8f', '\x91', '\x94', '\x96', '\x98', '\x99', '\x9c', '\x9d', '\xa0', '¡', '¢', '£', '¤', '¥', '¦', '§', '¨', '©', 'ª', '¬', '\xad', '°', '±', '²', '³', '´', 'µ', '¶', '·', '¸', '¹', 'º', '¼', '½', '¾', '¿', 'Á', 'Â', 'Ã', 'Ä', 'Å', 'Ç', 'É', 'Ê', 'Ì', 'Ï', 'Ð', 'Ñ', 'Ô', 'Ö', 'Ø', 'Ü', 'Ý', 'Þ', 'ß', 'à', 'á', 'â', 'ã', 'ä', 'å', 'ç', 'è', 'é', 'ê', 'ì', 'í', 'î', 'ï', 'ð', 'ñ', 'ó', 'ô', 'ö', 'ù', 'ú', 'û', 'ü', 'ý', 'þ', 'Ă', 'ď', 'ę', 'Ł', 'ń', 'ő', 'œ', 'ś', 'Š', 'š', 'Ј', 'С', 'й', '،', 'أ', 'إ', 'ئ', 'ا', 'ب', 'ة', 'ت', 'ح', 'ر', 'س', 'ش', 'ع', 'غ', 'ف', 'ك', 'ل', 'م', 'ن', 'و', 'ي', 'َ', 'ُ', 'ِ', 'ّ', 'ْ', '\u200b', '‒', '–', '—', '‚', '€', '™', '─', '☻', '♥', '♪', '慹', '拢', '檛', '鈥', 'ﬁ', 'ﬂ']

In [6]:
is_ascii = lambda text: text.isascii()
maska = df['eng_text'].apply(is_ascii)
df_non_ascii = df[~maska].copy().reset_index(drop=True)
print(df_non_ascii.shape)
df_non_ascii.head()

(4595, 2)

,eng_text,pol_text
0,¿You had never seen A crab suedes? Them there ...,- Nigdy wcześniej nie widziałaś raków?
1,"He hears ¿, where you live?",Nigdy wcześniej nie byłam w lesie.
2,"Boys ¿, they are there?",Jesteście tam chłopaki?
3,- Te atrapé. - No es gracioso. Your he catches...,- Ale twoje mina była.
4,"Your also ¿, it is not like that?","- Tak, niezła jest"

In [7]:
df_2 = df[maska].reset_index(drop=True)
df_2.shape

(595405, 2)

#### 2.2 Polish Non-Ascii Sentences

In [8]:
pl_chars = set("ąęćłńóśźżĄĘĆŁŃÓŚŹŻ")
requir = lambda let: not let.isascii() and let not in pl_chars
maska = df_2['pol_text'].apply(lambda snt: any([requir(let) for let in snt]))
df_non_ascii = df_2[maska].copy().reset_index(drop=True)
print(df_non_ascii.shape)
df_non_ascii.sample(10)

(1227, 2)

,eng_text,pol_text
1138,"In June, July and August We look cute when we'...","¶ Czerwiec, lipiec, sierpień ¶ W szortach cudn..."
463,- Well...,- Cóž...
666,- I've had to compromise.,Ale musialem išc na kompromis.
647,Smart enough to understand a situation when it...,"Jest pan na tyle madry, by pojac nasze wyjašni..."
693,"Well, I... see by the papers you certainly got...","Widze z gazet, že stales sie prawdziwym senato..."
968,"Calm down, darling.","Rémy! - Przestań, skarbie."
238,- We can't find him.,–Bądź co bądź nie możemy go znaleźć.
712,- Clarissa... where can we get a drink?,- Clarisso... gdzie možemy sie napic?
866,"- Oh, fine. Fine, Joe.","- Šwietnie, Joe."
364,Garcon!,- Garçon!

In [9]:
df_3 = df_2[~maska].reset_index(drop=True)
print(df_3.shape)
df_3.sample(5)

(594178, 2)

,eng_text,pol_text
582214,Know what happened to her?,Gdzie ona teraz jest?
145620,"What's he saying, Bill?","Co on mówi, Bill?"
92851,Ya can't argue against that.,Nie możesz temu zaprzeczać.
374706,I've done everything in my power to help you f...,"Zrobiłem wszystko, co w mojej mocy, aby pomóc ..."
71572,- I don't care for the value.,- Nie interesuje mnie to.

In [10]:
print(nonascii_list(df_3['eng_text'], False))
print(nonascii_list(df_3['pol_text'], True))

[]
[]

In [11]:
df_3.iloc[74182]['eng_text']

'The next time I...'

In [12]:
df_3.iloc[74182]['pol_text']

'Następnym razem...'

#### 2.3 Short Or Empty Examples

In [13]:
mask1 = df_3['eng_text'].str.len() >= 3
mask2 = df_3['pol_text'].str.len() >= 3

In [14]:
df_4 = df_3[mask1 & mask2].reset_index(drop=True)
df_4.head()

,eng_text,pol_text
0,"Previously on ""The Blacklist""...",/W poprzednich odcinkach: /
1,- You want to call your daddy?,- Chcesz zadzwonić do taty?
2,"- Yeah, I want to tell him I'm okay.","- Tak, powiem, że wszystko w porządku."
3,Okay.,Dobrze.
4,Lizzy... Be careful of your husband.,"Lizzy, uważaj na męża."

In [15]:
df_4.shape

(593894, 2)

#### 2.4 Dialog like sentences [starts with - ]

In [16]:
is_dialog = lambda snt: bool(re.match(r"^ *- *", snt))
mask = df_4['eng_text'].apply(is_dialog) | df_4['pol_text'].apply(is_dialog)
df_dialogs = df_4[mask].copy().reset_index(drop=True)
df_dialogs.head()

,eng_text,pol_text
0,- You want to call your daddy?,- Chcesz zadzwonić do taty?
1,"- Yeah, I want to tell him I'm okay.","- Tak, powiem, że wszystko w porządku."
2,- 45 seconds.,Szybciej! 45 sekund.
3,It's okay. It's okay. It's okay.,- Już dobrze.
4,It's okay. You're okay. You're okay.,- Odpoczywaj.

In [17]:
def fix_dialog(snt):
    return re.sub(r"^ *- *", "", snt)

df_4['eng_text'] = df_4['eng_text'].apply(fix_dialog).reset_index(drop=True)
df_4['pol_text'] = df_4['pol_text'].apply(fix_dialog).reset_index(drop=True)
df_4.sample(30)

,eng_text,pol_text
496234,I hear Karl-Magnus has returned home.,"Słyszę, że Karl-Magnus wrócił do domu."
111803,"Why, I've been at...",Byłem u...
562568,You must look after her.,Musi się nią zająć.
435316,But-,Ale...
392345,We'll split the difference.,Damy na środku.
36373,"This fire, this voice, this agony?","Ogniowi, głosowi, męczarni."
189920,"It's nice to see you, Lehmann.","Miło cię widzieć, Lehmann."
195345,Why not? I guess we can make you talk.,"Myślę, że możemy zmusić cię do mówienia."
428551,Haven't I told you not to answer the phone at ...,"Nie mówiłem ci, żeby w nocy nie odbierać telef..."
447138,Thank you.,"Możesz iść. Dziękuję, siostro."
87300,Well he and I are just like that.,Ponieważ między nami oto taka przepaść.
98232,There...,Proszę...
502655,No.,Nie.
484937,Thank you.,Dziękuję.
245700,Don't tell them where we're going.,"Nie mów im, dokąd pojedziemy."
210868,Ever noticed how doctors and surgeons have suc...,Zastanawiałeś się dlaczego chirurdzy mają taki...
502786,Yes.,Tak.
550347,What a goon.,Co za matołek.
42526,"You're too flighty, too impatient","Jesteś zbyt lekkomyślny, zbyt niecierpliwy..."
238016,Let her go!,Puść ją!
508647,So I was told once before.,Wiem o tym.
273765,Have them shot.,Roztrzelać.
511470,We need to go to Noge's home.,Chcę poznać rodziców Noge.
19621,Am I to blame in the end?,To ja ponoszę winę.
465611,"You make me feel- l don't know, warm.",Nie wiem.
455225,All aboooaard!,Wszyscy na pokład!
227305,It was Little Joe the wrangler,Był sobie kowboj Mały Joe
528681,Aren't you tired?,Nie jesteś zmęczony?
568346,And it never stops beating.,Który nie przestaje bić.
418662,I'm ashamed of you.,Wstyd mi za ciebie.

#### 2.5 Broken Dialog like sentences [somehwere has -]

# Do naprawy (lepszy re przed tokenziacja)

In [18]:
broken_dialog = lambda snt: bool(re.match(r".* +- +.*", snt))
mask1 = df_4['eng_text'].apply(broken_dialog)
mask2 = df_4['pol_text'].apply(broken_dialog)

In [19]:
df_4[mask1 | mask2].sample(5)

,eng_text,pol_text
326393,You had a gang of what?,Jaki gang? - Chłopaków.
361743,When Father set up the trust for the boys why ...,Dlaczego ojciec założył fundusz powierniczy dl...
7083,"""For the first time in my life I am frightened...",Ostrzegam cię - uważaj na tego Wenk'a
510537,"Can I get you something else? - Nothing more, ...",moja droga.
87346,Good. - Are you coming in?,Zejdziecie?

In [20]:
df_5 = df_4[~mask1 & ~mask2].reset_index(drop=True)

In [21]:
broken_dialog = lambda snt: bool(re.match(r".*-.*", snt))

In [22]:
df_5.sample(50)

,eng_text,pol_text
183602,"What do I care? Alright boys, put him in.","Dobra, weźcie go tam."
355135,"Goodbye, Uncle Charles.","Do widzenia, wujku."
268757,I'm trying to concentrate.,Pozwól się skupić!
349750,I shall see that you're not disturbed sir.,"Dopilnuję, żeby panu nie przeszkadzano."
361649,There's somebody down here to see you.,Ktoś chce się z wami zobaczyć.
544787,Let him have a drink!,Niech się napije!
356193,My brother said later!,"Mój brat powiedział, że później!"
569136,I pressed the gun.,Chwyciłam broń.
177389,Door shaker!,Szejker drzwi!
449319,I didn't want to believe it.,Nie chciałem uwierzyć.
500777,I want to talk to you.,Chcę z tobą pogadać.
49181,Hercules? Venus?,Herkules?
409900,It's perfectly natural she should want to see ...,"To naturalne, że chciała mnie zobaczyć. Zwłasz..."
542083,I ain't giving. I'm just showing.,"Nie daję, tylko pokazuję."
227772,Nobody cares about me.,Nikt o mnie nie dba.
314290,I don't think you'd better go yet.,"Nie sądzę, żebyście powinni już jechać."
428949,"And strangely enough, that's just where he is.","I dziwnie jest, to gdzie jest teraz."
193124,Couldn't we continue this discussion over a wh...,"Czy możemy dokończyć tę rozmowę po grze, przy ..."
123562,That's quite all right.,Nie trzeba.
566946,"No, it's just that everything's ""Americans thi...","Nie, ale wszyscy o tej Ameryce... Ameryka to....."
512494,But if you're only,"* Ale, jeżeli jesteś tylko *"
445322,"But every now and then, we have our little dis...",Ale od czasu do czasu trochę się posprzeczamy.
333694,Is it forbidden to enter there?,Czy wejście tam jest zakazane?
99280,He went on the road again.,Udał się w drogę.
97163,Shut up.,Zamknij się!
517946,Ninety percent of the time I get away with tha...,W 90 procentach przypadków to działa.
354705,I've dropped in to register a new subject.,Chciałbym zarejestrować nowe dziecko.
311747,Mr Gruffydd?,Panie Gruffydd?
129832,"100,000 francs reward for my capture.","100,000 franków nagrody za schwytanie mnie."
40097,I don't mind having a difficult fatherinlaw.,Nie mam nic przeciwko skomplikowanemu teściowi.
334168,"Good morning, young prince.","Dzień dobry, mały książę."
476166,"Which it are, old chap.",Tak stary druhu.
298639,"""He has nothing to recommend him but a certain...","""Nie wyróżnia się niczym poza głupią zwierzęcą..."
511700,Hold it.,"Zaczekajcie, wszyscy."
220372,I'll read you to sleep.,Poczytam ci.
400662,I'm sure it's here to stay when you see such f...,"Zwłaszcza, że mamy po swojej stronie takich pr..."
402573,"It was at the children's party here, and there...","To było przyjęcie dla dzieci, i był magik."
419447,Why did you do it?,Czemu to zrobiłaś?
206019,"Never mind, I'll read it.","Przeczytaj to... Czekaj, ja ci przeczytam."
485946,"Good morning, Mr. Earp.","Dzień dobry, panie Earp."
11053,"""Right here,"" said Big Jim.","""Właśnie tu,"" powiedział Big Jim."
535941,Pretty baby.,Ładna babeczka.
366267,Thank you.,Dziękuję.
126704,We'll go somewhere and celebrate the New Year.,Pójdziemy gdzieś świętować Nowy Rok.
70186,Yeah!,Tak!
362535,You mislaid a couple.,Zgubiłaś parę.
293235,I'm all right!,Nic mi nie jest!
427388,"Destroyer calling trooper, am coming alongside.","Uwaga, ""Trooper"": My zbliżamy się do prawej bu..."
323366,"But they weren't about tramps, lockouts, sweat...","Ale nie zgodzą się na film o włóczęgach, żyjąc..."
129686,"Yes, yes, of course, I know.","Tak, oczywiście, że wiem."

#### 2.6 Different Last Case

In [23]:
mask = df_5['eng_text'].str[-1] != df_5['pol_text'].str[-1]
mask.sum()

57558

In [24]:
df_6 = df_5[~mask].reset_index(drop=True)

#### 2.7 Text length difference

In [25]:
mask = df_6['eng_text'].str.split
df_6['len_ratio'] = df_6['eng_text'].str.split().str.len() / df_6['pol_text'].str.split().str.len()
df_6.head()

,eng_text,pol_text,len_ratio
0,You want to call your daddy?,Chcesz zadzwonić do taty?,1.500000
1,"Yeah, I want to tell him I'm okay.","Tak, powiem, że wszystko w porządku.",1.333333
2,Okay.,Dobrze.,1.000000
3,Lizzy... Be careful of your husband.,"Lizzy, uważaj na męża.",1.500000
4,I can only lead you to the truth.,/Mogę naprowadzić cię na prawdę.,1.600000

In [26]:
thres_left = df_6["len_ratio"].quantile(0.05)
thres_right = df_6["len_ratio"].quantile(0.95)
thres_left, thres_right

(0.75, 2.5)

In [27]:
mask = (df_6["len_ratio"] >= thres_left) & (df_6["len_ratio"] <= thres_right)
mask.sum()

472209

In [28]:
df_7 = df_6[mask].reset_index(drop=True)
df_7.sample(20)

,eng_text,pol_text,len_ratio
358124,lt's very kind of you.,To miłe z Pana strony.,1.000000
448833,I'm going to write him tonight.,Napiszę do niego dziś wieczorem.,1.200000
159532,Pretty enough for Ted's grave.,Jak znalazł na grób Teda.,1.000000
342397,"If the mist clears, we're cooked!","Jeśli mgły opadną, koniec z nami!",1.000000
310469,I was hoping you would.,Taką miałem nadzieję.,1.666667
378740,Do you know anything about building?,Czy wiesz coś na temat budowania?,1.000000
131365,"Well, will Dan go, too?",Czy Dan też wypływa?,1.250000
425898,No.,Nie.,1.000000
265153,I was imagining the criminal was clever enough...,"Wyobrażałam sobie, że przestępca jest na tyle ...",1.000000
112639,We're waiting till General Merritt gets here w...,"Czekamy, aż generał Merritt przybędzie tu z Pi...",1.214286
20401,"This will be your last visit to this country, ...","To będzie pana ostatnia wizyta, pułkowniku.",1.666667
261296,I'm very much obliged to you.,Jestem ci bardzo wdzięczny.,1.500000
31979,"WELL, SONIA, I'M GOING TO GIVE YOU ANOTHER CHA...","Dobrze Soniu, dam ci jeszcze jedną szansę.",1.285714
39758,Different?,Inaczej?,1.000000
118338,"Thanks, dear.","Dzięki, kochanie.",1.000000
11530,"""You think somebody knows my project ""and he i...","""Sądzi pan, że ktoś zna moje plany i jest zain...",1.142857
459633,He called me up.,Zadzwonił do mnie.,1.333333
247870,"Oh, no, not that.",Nie to.,2.000000
78948,"At the risk of offending you, I must tell you ...","Ryzykując zniewagę, przyznam, żeś elegancki ja...",2.125000
259762,Department of duties and sacrifices.,Departament obowiązków i poświęceń.,1.250000

In [29]:
df_7.sample(50)

,eng_text,pol_text,len_ratio
417593,I'd turn them into Army ordnance.,Słyszałem od artylerzystów.,2.000000
67909,Then shut up about it.,Więc o tym nie wspominaj.,1.000000
145466,"You know, this is a beautiful spot here, Hartley.","Wiesz, że to piękne miejsce, Hartley.",1.500000
52875,You can Steal a picture.,Można ukraść zdjęcie.,1.666667
80180,"Becky, Becky, don't... I...","Becky, Becky przestań, ja...",1.000000
78128,had taken his own life.,który odebrał sobie życie.,1.250000
2158,What are you up to?,Co zamierzasz?,2.500000
347344,"That's one of them, the other one's in the cel...",To jedno z nich. Drugie jest w piwnicy.,1.250000
270425,"Never fear, my little one.","Nie martw się, moja mała.",1.000000
149243,These girls know too much.,Te dziewczyny wiedzą za dużo.,1.000000
57005,You come and tell me it's all over ..,"Przychodzisz i mówisz mi, że to już koniec...",1.125000
191162,I'd better hold this for you.,Lepiej to panu potrzymam.,1.500000
136077,Poor little child!,Biednych małych dzieci!,1.000000
195412,What sort of a woman is Lady Esketh?,Jakim typem kobiety jest Lady Esketh?,1.333333
340299,Good Fido.,Dobry Fido.,1.000000
16052,ls she your private property?,"Ma pan wyłączność na ""tę damę""?",0.833333
203574,My sleep only seems to tire me.,Sen wydaje się mnie tylko męczyć.,1.166667
90342,What's the idea of playing blind man's bluff t...,Chcesz się bawić teraz w ciuciubabkę?,2.166667
30328,Everything.,Wszystko.,1.000000
69740,"Hey, Pop! Look! An orange!","Hej, tato, patrz, pomarańcza!",1.250000
332644,Quite.,Nie.,1.000000
467167,They must've reopened the case a dozen times.,Musieliby ponownie otwierać sprawę z tuzin razy.,1.142857
24028,"And then a voice cries out, and I can't listen...",A potem... jakiś głos wrzeszczy... Nie zniosę ...,1.375000
66218,I'd like to see that again.,Chciałbym to jeszcze raz zobaczyć.,1.200000
166181,Please.,Proszę.,1.000000
208955,"Yes, I do.","Tak, zdarza się.",1.000000
413421,We're still looking for the murder weapon.,Wciąż szukamy narzędzia zbrodni.,1.750000
53882,"No, not Mr Moto.","Nie, nie Mr Moto.",1.000000
20921,"Now, please, go back to bed at once.",Proszę natychmiast wrócić do łóżka.,1.600000
427250,And cousin Charlotte's land jaunts do wear one...,A lądowe wyprawy kuzynki Charlotty nieco wycze...,1.571429
372129,Monte was alone.,Monte był sam.,1.000000
154759,You never get home before 3:00 in the morning.,Nie będziesz wracał do domu przed 3 rano.,1.125000
75021,"Say, about this important business of yours th...","Powiedz o tej ważnej sprawie, w którą jesteś z...",1.222222
27920,I forbid you to address my niece.,Zabraniam ci nękać moją siostrzenicę.,1.400000
431533,"Oh, I'm terribly sorry. I thought you were our...","Och, jest mi okropnie przykro myślałam, że jes...",0.916667
319445,But there must be a way out.,Ale musi być jakieś wyjście.,1.400000
443763,No.,Nie.,1.000000
220561,It's gone!,Zniknęła!,2.000000
341121,Off with your pants.,Zdejmuj spodnie.,2.000000
216518,You sit here and enjoy yourself.,Ty siedź tu i baw się dobrze.,0.857143
55672,Come here.,Podejdź.,2.000000
349262,"Who's he, your MP?",Kto jest twoim radnym?,1.000000
332971,I can only submit my findings to His Grace... ...,"Przekażę tylko Jego Ekscelencji moje uwagi, ab...",1.700000
145043,I ask you is there anything wrong with this?,Pytam panią. Czy jest w tym coś złego?,1.125000
286064,"Wise guy, eh?","Przemądrzalec, co?",1.500000
372664,She could still be his wife. He would marry her.,Wciąż mogła zostać jego żoną.,2.000000
393552,Haven't checked yet.,To krewna? Nie sprawdzaliśmy.,0.750000
74900,No.,Nie.,1.000000
154141,Your daughter?,Pana córka?,1.000000
22894,"Are you hurt, Eddie?","Niczego nie złamałeś, Eddie?",1.000000

#### 2.8 Sentences starting with * fix

In [30]:
fix_star = lambda snt: re.sub(r"^ *[*].*", "", snt)
df_7['eng_text'] = df_7['eng_text'].apply(fix_star)
df_7['pol_text'] = df_7['pol_text'].apply(fix_star)

#### 2.9 Action Comments

In [31]:
def mask_distinct(df, col1, col2, chars):
    chars_escaped = "".join(re.escape(c) for c in chars)
    templ = f"[{chars_escaped}]"

    m1 = df[col1].str.contains(templ, regex=True, na=False)
    m2 = df[col2].str.contains(templ, regex=True, na=False)

    return m1 ^ m2

chars = '[]()/\*+#$"️'
mask = mask_distinct(df_7, "eng_text", "pol_text", chars)

df_8 = df_7[~mask].reset_index(drop=True)
df_8.shape

(467550, 3)

In [32]:
df_8.sample(50)

,eng_text,pol_text,len_ratio
166472,Maybe he's handsome like Ed.,Moze on jest przystojny jak Ed.,0.833333
396776,"Don't you find Rio a little hard to take, too?","Nie uważasz, że ciężko jest w Rio?",1.428571
465149,Are you asking me?,Prosisz mnie?,2.000000
78462,Please accept my apologies.,Proszę przyjąć moje przeprosiny.,1.000000
252294,I sort of liked it there.,I tak jakby spodobało mi się.,1.000000
386642,I see.,Rozumiem.,2.000000
294874,Even better than I was before.,Nawet lepiej niż przedtem.,1.500000
341085,I didn't tell them what you were doing.,"Nie o tym, co robisz.",1.600000
86776,All men to your posts!,Wszyscy na stanowiska!,1.666667
92908,"Norton, get me a cup.","Panie Norton, poproszę o kubek.",1.000000
239506,You know how to develop it?,"Wiesz, jak wywołać?",2.000000
336211,And what of Petit?,A co z Petit?,1.000000
117436,Have you really made up your mind to leave me ...,Naprawdę chcesz mnie opuścić... wiesz co będzi...,1.900000
9097,Bring him in.,Dajcie go do mnie.,0.750000
180856,I've been waiting one solid hour to speak to y...,"Czekam od godziny, by z panią porozmawiać, pan...",1.333333
185929,Impertinent but I like it.,Impertynenckie ale podoba mi się.,1.000000
386250,Do you still think that I don't mean what I say?,"A ty wciąż sądzisz, że rzucam słowa na wiatr?",1.222222
237681,Good morning.,Dzień dobry.,1.000000
328414,"Yes, Master.","Tak, panie.",1.000000
183354,All set below!,Na dole wszystko gotowe!,0.750000
275749,"MAN: Hey, we'll give a stop to Murphy and Kelly.",Zatrzymaliśmy Murphy'ego i Kelly'ego.,2.500000
117239,"No, darling.","Nie, kochanie.",1.000000
303020,Yeah.,Tak.,1.000000
281376,"Hello, sheriff speaking.",Mówi szeryf.,1.500000
119510,"I'll get petrol for you, trust me.","Uwierz mi, że zdobędę benzynę dla ciebie.",1.000000
135405,My theatrical skills are questionable.,Moje teatralne umiejętności są dyskusyjne.,1.000000
429444,We were going to enjoy the waning twilight.,Mieliśmy podziwiać brzask jutrzenki.,2.000000
322036,We've got a wonderful setup here.,"Mamy tu świetną kryjówkę, doktorku.",1.200000
99466,It was only me in that mirror.,To byłem tylko ja w tym lustrze.,1.000000
11767,It isn't Behn.,To nie Behn.,1.000000
287698,"Now, don't get your mule streak up.",Nie bądź uparty.,2.333333
147130,I can quite understand that you didn't want to...,"Rozumiem, że nie chciałaś rozmawiać przed tymi...",1.875000
192848,I'm going to get in the movies and wear all th...,Będę występowała w filmach i nosiła te ładne u...,1.444444
191208,You can't do that.,Nie możesz tego zrobić.,1.000000
412599,You look like the first time you jumped.,Wyglądasz jak tuż przed pierwszym skokiem.,1.333333
199289,"Divorce me, ruin my reputation!",I zrujnuje mi reputację!,1.250000
178350,"How do you do, Mr. Clemens?","Jak się pan miewa, panie Clemens?",1.000000
304518,Then I'll have some water.,No to napiję się wody.,1.000000
20356,Other people always manage that on these occas...,"W takich sytuacjach zawsze znajdzie się ktoś, ...",0.888889
436106,Just look at it. What a beautiful piece.,"Niech pan zobaczy, jaki to piękny okaz.",1.142857
334431,I don't understand. I've tried to put it toget...,Próbuję jakoś powiązać morderców z tymi co mni...,2.000000
71304,This is your fault.,To twoja Wina.,1.333333
14692,Not at all!,Wcale nie!,1.500000
148370,Let him spout for the moment.,Niech sobie przez chwilę ulży.,1.200000
173637,Get out!,Wynocha!,2.000000
224394,"No, no, I... I've stopped.",Właśnie... skończyłem.,2.500000
224347,Did you enjoy the party?,Dobrze się bawiłeś?,1.666667
35121,"No, Doctor.","Nie, doktorze.",1.000000
266276,Telegram.,Telegram.,1.000000
177709,I was...,Byłem...,2.000000

#### 2.10  " ` " ---> " ' " & del " ~ "

In [33]:
wanted_case = '`'
mask = df_8["eng_text"].apply(lambda x: wanted_case in x)
df_8[mask]

,eng_text,pol_text,len_ratio
214145,"Revolution had broken out, her diplomats sued ...","Rewolucja na tyłach frontu, dąży do zawarcia p...",1.277778
214152,We`ll examine it.,Zbadajmy go.,1.500000
214157,What do you think you`re doing?,Wstawaj! Co ty robisz?,1.500000
214161,Where`s your hand grenade?,Gdzie masz swój granat?,1.000000
214163,Let `em have it!,Niech je poczują!,1.333333
...,...,...,...
214943,We don`t want to hate one another.,Bez nienawiści ani pogardy.,1.750000
214944,There`s room for everyone.,Każdy ma swe miejsce.,1.000000
214947,"Greed has poisoned men`s souls, has barricaded...","Chciwość zatruła nasze dusze, wzniosła mury ni...",1.333333
214963,You don`t hate.,Przestańcie nienawidzieć.,1.500000
214965,"Soldiers, don`t fight for slavery, fight for l...","Nie walczcie o niewolę, lecz o wolność!",1.142857

In [34]:
df_8["eng_text"] = df_8["eng_text"].str.replace("`", "'", regex=False)
df_8["pol_text"] = df_8["pol_text"].str.replace("`", "'", regex=False)

In [35]:
df_8["eng_text"] = df_8["eng_text"].str.replace("~", "", regex=False)
df_8["pol_text"] = df_8["pol_text"].str.replace("~", "", regex=False)

#### 2.11 Del rows with specific case

In [36]:
def del_row_with_char(df, eng_col, pol_col, chars):
    df_proc = df.copy()
    for char in chars:
        mask1 = df_proc[eng_col].apply(lambda x: char in x)
        mask2 = df_proc[pol_col].apply(lambda x: char in x)
        df_proc = df_proc[~(mask1 | mask2)].reset_index(drop=True)
    return df_proc
    

chars = "=+*@#;|_}{"
df_9 = del_row_with_char(df_8, "eng_text", "pol_text", chars)

#### 2.12 Del rows with dialog -

In [37]:
mask1 = df_9["eng_text"].apply(lambda x: bool(re.search(r' +-[^ ]+', x)))
mask2 = df_9["pol_text"].apply(lambda x: bool(re.search(r' +-[^ ]+', x)))
df_data = df_9[~(mask1 | mask2)].reset_index(drop=True)

#### 3. Data Tokenization

In [38]:
uniq_cases = set("".join(df_data["eng_text"].astype(str)))
tab1 = sorted(list(uniq_cases), reverse=True)
print(tab1)

['z', 'y', 'x', 'w', 'v', 'u', 't', 's', 'r', 'q', 'p', 'o', 'n', 'm', 'l', 'k', 'j', 'i', 'h', 'g', 'f', 'e', 'd', 'c', 'b', 'a', ']', '[', 'Z', 'Y', 'X', 'W', 'V', 'U', 'T', 'S', 'R', 'Q', 'P', 'O', 'N', 'M', 'L', 'K', 'J', 'I', 'H', 'G', 'F', 'E', 'D', 'C', 'B', 'A', '?', ':', '9', '8', '7', '6', '5', '4', '3', '2', '1', '0', '/', '.', '-', ',', ')', '(', "'", '%', '$', '"', '!', ' ']

In [39]:
uniq_cases = set("".join(df_data["pol_text"].astype(str)))
tab2 = sorted(list(uniq_cases), reverse=True)
print(tab2)

['ż', 'Ż', 'ź', 'Ź', 'ś', 'Ś', 'ń', 'Ń', 'ł', 'Ł', 'ę', 'Ę', 'ć', 'Ć', 'ą', 'Ą', 'ó', 'Ó', 'z', 'y', 'x', 'w', 'v', 'u', 't', 's', 'r', 'q', 'p', 'o', 'n', 'm', 'l', 'k', 'j', 'i', 'h', 'g', 'f', 'e', 'd', 'c', 'b', 'a', ']', '[', 'Z', 'Y', 'X', 'W', 'V', 'U', 'T', 'S', 'R', 'Q', 'P', 'O', 'N', 'M', 'L', 'K', 'J', 'I', 'H', 'G', 'F', 'E', 'D', 'C', 'B', 'A', '?', ':', '9', '8', '7', '6', '5', '4', '3', '2', '1', '0', '/', '.', '-', ',', ')', '(', "'", '%', '$', '"', '!', ' ']

In [40]:
def tokenize_eng(snt):
    snt = snt.lower()
    snt = re.sub("(?<! )'(?! )", r" '", snt)
    snt = re.sub(r"""([\]?:)\[(/\.\-,%\$"!])""", r" \1 ", snt)
    snt = re.sub(r"\s+", " ", snt).strip()
    return re.split(r'\s+', snt.strip())

In [41]:
def tokenize_pol(snt):
    snt = snt.lower()
    snt = re.sub(r"""([\]?:)\[(/\.\-,%\$"!])""", r" \1 ", snt)
    snt = re.sub(r"\s+", " ", snt).strip()
    return re.split(r'\s+', snt.strip())

In [42]:
df_data = df_data.drop(['len_ratio'], axis=1)

#### 3.1 Splitting and trimming on quantile

In [43]:
df_data['eng_split'] = df_data['eng_text'].apply(tokenize_eng)
df_data['pol_split'] = df_data['pol_text'].apply(tokenize_pol)
df_data.sample(10)

,eng_text,pol_text,eng_split,pol_split
301812,"Ah, ah, I'm okay.","Nie, nic mi nie jest.","[ah, ,, ah, ,, i, 'm, okay, .]","[nie, ,, nic, mi, nie, jest, .]"
131909,I came here to look at a man.,"Przyszłam tu, żeby spojrzeć na mężczyznę.","[i, came, here, to, look, at, a, man, .]","[przyszłam, tu, ,, żeby, spojrzeć, na, mężczyz..."
415710,"If Abrahams doesn't impress me, I'll try Van D...","Jeśli Abrahams mi się nie spodoba, zwrócę się ...","[if, abrahams, doesn, 't, impress, me, ,, i, '...","[jeśli, abrahams, mi, się, nie, spodoba, ,, zw..."
351137,"Monke, get some water.","Monke, przynieś wody.","[monke, ,, get, some, water, .]","[monke, ,, przynieś, wody, .]"
211568,Never pursue her.,Nigdy jej nie namawiaj.,"[never, pursue, her, .]","[nigdy, jej, nie, namawiaj, .]"
412837,Do you see Father?,Widzisz ojca?,"[do, you, see, father, ?]","[widzisz, ojca, ?]"
337502,"You, turn around.","Ty, odwróć się.","[you, ,, turn, around, .]","[ty, ,, odwróć, się, .]"
30430,HURRY UP.,Pospiesz się.,"[hurry, up, .]","[pospiesz, się, .]"
298697,Will you need me on the way back?,Potrzebny będę w drodze powrotnej?,"[will, you, need, me, on, the, way, back, ?]","[potrzebny, będę, w, drodze, powrotnej, ?]"
453763,"Inside, up the stairs.",Po schodach w górę.,"[inside, ,, up, the, stairs, .]","[po, schodach, w, górę, .]"

In [44]:
thres1 = df_data['eng_split'].str.len().quantile(0.99)
mask1 = df_data['eng_split'].str.len() > thres1

thres2 = df_data['pol_split'].str.len().quantile(0.99)
mask2 = df_data['pol_split'].str.len() > thres2
print(mask1.sum(), mask2.sum(), (mask1 | mask2).sum())

df_data = df_data[~(mask1 | mask2)].reset_index(drop=True)

4113 3960 5510

#### 3.2 BPE Init. Uniq_freq & Rozklad chars

In [148]:
uniq_freq_eng = Counter(df_data['eng_split'].explode())
uniq_freq_pol = Counter(df_data['pol_split'].explode())

In [149]:
len(uniq_freq_eng), len(uniq_freq_pol)

(40087, 113603)

In [250]:
char_factor = lambda word: [x for x in word] + ['</w>']
vocab_chars_eng = [[char_factor(k), v] for k, v in uniq_freq_eng.most_common()]
vocab_chars_pol = [[char_factor(k), v] for k, v in uniq_freq_pol.most_common()]
print(len(vocab_chars_eng), vocab_chars_eng[:5], '\n')
print(len(vocab_chars_pol), vocab_chars_pol[:5])

40087 [[['.', '</w>'], 435802], [[',', '</w>'], 177291], [['y', 'o', 'u', '</w>'], 134548], [['i', '</w>'], 122767], [['t', 'h', 'e', '</w>'], 89859]]

113603 [[['.', '</w>'], 413780], [[',', '</w>'], 183948], [['?', '</w>'], 83444], [['n', 'i', 'e', '</w>'], 82694], [['t', 'o', '</w>'], 53190]]

#### 3.3 BPE Tokenizer most common pairs

In [249]:
class BPETokenizer():
    def __init__(self, vocab_chrs, vocab_size, is_tgt):
        self.vocab_chrs = vocab_chrs
        self.vocab_size = vocab_size
        self.vocab = self.vocab_init(vocab_chrs, is_tgt)
        self.base_size = len(self.vocab)

    def vocab_init(self, vocab_chrs, is_tgt):
        vocab = {'<pad>': 0, '<unk>': 1, '<eos>': 2, '</w>': 3}
        if is_tgt:
            vocab['<bos>'] = 4
            
        uniq_toks = {tok for toks, _ in vocab_chrs for tok in toks}
        uniq_toks.remove('</w>')
        for i, tok in enumerate(uniq_toks, len(vocab)):
            vocab[tok] = i
        return vocab                

    def train_bpe(self):
        for i in range(self.base_size, self.vocab_size):
            pair = self.most_common_pair()
            self.vocab[pair] = i
            pair_con = re.sub('\s+', '', pair)
            self.replace_pairs(pair, pair_con)

    def most_common_pair(self):
        pair_counts = Counter()
        for toks, freq in self.vocab_chrs:
            for pair in map(' '.join, zip(toks, toks[1:])):
                pair_counts[pair] += freq
        return pair_counts.most_common(1)[0][0]

    def replace_pairs(self, pair, pair_con):
        for i, (toks, _) in enumerate(self.vocab_chrs):
            self.vocab_chrs[i][0] = ' '.join(toks).replace(pair, pair_con).split()

In [251]:
tokenizer_eng = BPETokenizer(vocab_chars_eng, 8000, False)

In [254]:
tokenizer_eng.train_bpe()

In [135]:
def connect_pairs(vocab_chars, pair):
    vocab_proc = vocab_chars.copy()
    pair_con = re.sub('\s+', '', pair)
    for i, (toks, _) in enumerate(vocab_proc):
        toks = " ".join(toks).replace(pair, pair_con).split()
        vocab_proc[i][0] = toks
    return vocab_proc

In [221]:
def most_common_pair(vocab_chars):
    pair_counts = Counter()
    for toks, freq in vocab_chars:
        for pair in map(' '.join, zip(toks, toks[1:])):
            pair_counts[pair] += freq
    return pair_counts.most_common(1)[0][0]

In [226]:
vocab_chars_eng

[[['.', '</w>'], 435802],
 [[',', '</w>'], 177291],
 [['y', 'o', 'u', '</w>'], 134548],
 [['i', '</w>'], 122767],
 [['t', 'h', 'e', '</w>'], 89859],
 [['?', '</w>'], 84640],
 [['t', 'o', '</w>'], 73192],
 [['a', '</w>'], 61661],
 [["'", 's', '</w>'], 57045],
 [['i', 't', '</w>'], 55074],
 [["'", 't', '</w>'], 50411],
 [['t', 'h', 'a', 't', '</w>'], 43020],
 [['a', 'n', 'd', '</w>'], 41124],
 [['o', 'f', '</w>'], 39514],
 [['i', 'n', '</w>'], 32142],
 [['!', '</w>'], 30794],
 [['m', 'e', '</w>'], 29977],
 [['w', 'h', 'a', 't', '</w>'], 26868],
 [['i', 's', '</w>'], 26378],
 [['h', 'e', '</w>'], 26149],
 [['f', 'o', 'r', '</w>'], 23935],
 [['w', 'e', '</w>'], 23370],
 [['t', 'h', 'i', 's', '</w>'], 20366],
 [['y', 'o', 'u', 'r', '</w>'], 20158],
 [['b', 'e', '</w>'], 20137],
 [['m', 'y', '</w>'], 20105],
 [["'", 'l', 'l', '</w>'], 20011],
 [['h', 'a', 'v', 'e', '</w>'], 19830],
 [['d', 'o', 'n', '</w>'], 18888],
 [['d', 'o', '</w>'], 18663],
 [['o', 'n', '</w>'], 18052],
 [['n', 'o', '</w>'], 17694],
 [["'", 'm', '</w>'], 16935],
 [['a', 'l', 'l', '</w>'], 16776],
 [['b', 'u', 't', '</w>'], 16067],
 [['w', 'a', 's', '</w>'], 15781],
 [["'", 'r', 'e', '</w>'], 15483],
 [['w', 'i', 't', 'h', '</w>'], 15435],
 [['c', 'a', 'n', '</w>'], 15365],
 [['h', 'e', 'r', 'e', '</w>'], 15059],
 [['n', 'o', 't', '</w>'], 14896],
 [['a', 'r', 'e', '</w>'], 14431],
 [['k', 'n', 'o', 'w', '</w>'], 14310],
 [['t', 'h', 'e', 'r', 'e', '</w>'], 14310],
 [['h', 'i', 'm', '</w>'], 14193],
 [['g', 'e', 't', '</w>'], 13469],
 [['i', 'f', '</w>'], 12400],
 [['w', 'e', 'l', 'l', '</w>'], 12155],
 [['t', 'h', 'e', 'y', '</w>'], 11807],
 [['n', 'o', 'w', '</w>'], 11736],
 [["'", 'v', 'e', '</w>'], 11579],
 [['l', 'i', 'k', 'e', '</w>'], 11372],
 [['y', 'e', 's', '</w>'], 10842],
 [['o', 'u', 't', '</w>'], 10839],
 [['s', 'h', 'e', '</w>'], 10741],
 [['c', 'o', 'm', 'e', '</w>'], 10653],
 [['g', 'o', '</w>'], 10570],
 [['r', 'i', 'g', 'h', 't', '</w>'], 10414],
 [['s', 'o', '</w>'], 10352],
 [['a', 'b', 'o', 'u', 't', '</w>'], 10349],
 [['a', 't', '</w>'], 10100],
 [['u', 'p', '</w>'], 9851],
 [['o', 'h', '</w>'], 9750],
 [['w', 'i', 'l', 'l', '</w>'], 9685],
 [['j', 'u', 's', 't', '</w>'], 9650],
 [['s', 'e', 'e', '</w>'], 9619],
 [['g', 'o', 'o', 'd', '</w>'], 9404],
 [['h', 'e', 'r', '</w>'], 9170],
 [['a', 's', '</w>'], 9044],
 [['"', '</w>'], 8870],
 [['o', 'n', 'e', '</w>'], 8831],
 [['g', 'o', 't', '</w>'], 8827],
 [['h', 'o', 'w', '</w>'], 8698],
 [["'", 'd', '</w>'], 7878],
 [['-', '</w>'], 7821],
 [['w', 'a', 'n', 't', '</w>'], 7783],
 [['t', 'h', 'i', 'n', 'k', '</w>'], 7743],
 [['w', 'h', 'y', '</w>'], 7726],
 [['h', 'i', 's', '</w>'], 7396],
 [['m', 'r', '</w>'], 7390],
 [['g', 'o', 'i', 'n', 'g', '</w>'], 7023],
 [['d', 'i', 'd', '</w>'], 6784],
 [['t', 'a', 'k', 'e', '</w>'], 6657],
 [['t', 'h', 'e', 'm', '</w>'], 6612],
 [['b', 'e', 'e', 'n', '</w>'], 6579],
 [['w', 'h', 'e', 'n', '</w>'], 6444],
 [['f', 'r', 'o', 'm', '</w>'], 6437],
 [['l', 'e', 't', '</w>'], 6379],
 [['t', 'e', 'l', 'l', '</w>'], 6330],
 [['w', 'h', 'o', '</w>'], 6283],
 [['w', 'h', 'e', 'r', 'e', '</w>'], 6175],
 [['s', 'a', 'y', '</w>'], 6142],
 [['v', 'e', 'r', 'y', '</w>'], 5833],
 [['b', 'a', 'c', 'k', '</w>'], 5736],
 [['m', 'a', 'n', '</w>'], 5539],
 [['t', 'i', 'm', 'e', '</w>'], 5538],
 [['l', 'o', 'o', 'k', '</w>'], 5465],
 [['a', 'n', '</w>'], 5437],
 [['h', 'a', 'd', '</w>'], 5395],
 [['t', 'o', 'o', '</w>'], 5297],
 [['u', 's', '</w>'], 5228],
 [['w', 'o', 'u', 'l', 'd', '</w>'], 5165],
 [['n', 'e', 'v', 'e', 'r', '</w>'], 5037],
 [['d', 'i', 'd', 'n', '</w>'], 4959],
 [['w', 'e', 'r', 'e', '</w>'], 4912],
 [['s', 'i', 'r', '</w>'], 4907],
 [['l', 'i', 't', 't', 'l', 'e', '</w>'], 4764],
 [['w', 'a', 'y', '</w>'], 4572],
 [['o', 'r', '</w>'], 4571],
 [['t', 'h', 'e', 'n', '</w>'], 4556],
 [['s', 'o', 'm', 'e', '</w>'], 4544],
 [['d', 'o', 'w', 'n', '</w>'], 4510],
 [['m', 'u', 's', 't', '</w>'], 4353],
 [['a', 'n', 'y', '</w>'], 4343],
 [['m', 'a', 'k', 'e', '</w>'], 4312],
 [['o', 'n', 'l', 'y', '</w>'], 4213],
 [['c', 'o', 'u', 'l', 'd', '</w>'], 4125],
 [['m', 'o', 'r', 'e', '</w>'], 4078],
 [['b', 'y', '</w>'], 4064],
 [['h', 'a', 's', '</w>'], 4035],
 [['s', 'o', 'm', 'e', 't', 'h', 'i', 'n', 'g', '</w>'], 4018],
 [['t', 'h', 'a', 'n', 'k', '</w>'], 3991],
 [['o', 'u', 'r', '</w>'], 3987],
 [['o', 'v', 'e', 'r', '</w>'], 3933],
 [['g', 'i', 'v', 'e', '</w>'], 3923],
 [['w', 'o', 'n', '</w>'], 3826],
 [['m', 'u', 'c', 'h', '</w>'], 3806],
 [['s', 'u', 'r', 'e', '</w>'], 3682],
 [['p', 'l', 'e', 'a', 's', 'e', '</w>'], 3634],
 [['n', 'i', 'g', 'h', 't', '</w>'], 3541],
 [['b', 'e', 't', 't', 'e', 'r', '</w>'], 3447],
 [['y', 'e', 'a', 'h', '</w>'], 3404],
 [['n', 'o', 't', 'h', 'i', 'n', 'g', '</w>'], 3379],
 [['a', 'n', 'y', 't', 'h', 'i', 'n', 'g', '</w>'], 3219],
 [['a', 'w', 'a', 'y', '</w>'], 3136],
 [['t', 'w', 'o', '</w>'], 3114],
 [['m', 'e', 'a', 'n', '</w>'], 3060],
 [['o', 'l', 'd', '</w>'], 3053],
 [['o', 'f', 'f', '</w>'], 3035],
 [['l', 'o', 'v', 'e', '</w>'], 3028],
 [['h', 'e', 'l', 'l', 'o', '</w>'], 3018],
 [['a', 'm', '</w>'], 2934],
 [['m', 'i', 's', 's', '</w>'], 2929],
 [['b', 'e', 'f', 'o', 'r', 'e', '</w>'], 2916],
 [['s', 'a', 'i', 'd', '</w>'], 2882],
 [['a', 'g', 'a', 'i', 'n', '</w>'], 2882],
 [['f', 'i', 'n', 'd', '</w>'], 2839],
 [['s', 'h', 'o', 'u', 'l', 'd', '</w>'], 2800],
 [['l', 'o', 'n', 'g', '</w>'], 2767],
 [['i', 's', 'n', '</w>'], 2738],
 [['t', 'h', 'i', 'n', 'g', '</w>'], 2720],
 [['s', 'o', 'r', 'r', 'y', '</w>'], 2676],
 [['h', 'e', 'l', 'p', '</w>'], 2667],
 [['a', 'f', 't', 'e', 'r', '</w>'], 2623],
 [['t', 'h', 'o', 'u', 'g', 'h', 't', '</w>'], 2600],
 [['p', 'u', 't', '</w>'], 2573],
 [['h', 'o', 'm', 'e', '</w>'], 2550],
 [['t', 'h', 'a', 'n', '</w>'], 2528],
 [['e', 'v', 'e', 'r', '</w>'], 2525],
 [['f', 'i', 'r', 's', 't', '</w>'], 2521],
 [['p', 'e', 'o', 'p', 'l', 'e', '</w>'], 2514],
 [['f', 'a', 't', 'h', 'e', 'r', '</w>'], 2502],
 [['t', 'h', 'i', 'n', 'g', 's', '</w>'], 2447],
 [['a', 'l', 'w', 'a', 'y', 's', '</w>'], 2424],
 [['t', 'h', 'o', 's', 'e', '</w>'], 2422],
 [['m', 'a', 'y', 'b', 'e', '</w>'], 2417],
 [['d', 'a', 'y', '</w>'], 2410],
 [['k', 'e', 'e', 'p', '</w>'], 2393],
 [['t', 'a', 'l', 'k', '</w>'], 2389],
 [['i', 'n', 't', 'o', '</w>'], 2380],
 [['g', 'o', 'n', 'n', 'a', '</w>'], 2372],
 [['m', 'r', 's', '</w>'], 2366],
 [['t', 'o', 'l', 'd', '</w>'], 2360],
 [['w', 'a', 'i', 't', '</w>'], 2348],
 [['m', 'i', 'n', 'd', '</w>'], 2339],
 [['a', 'i', 'n', '</w>'], 2336],
 [['b', 'e', 'c', 'a', 'u', 's', 'e', '</w>'], 2327],
 [['l', 'a', 's', 't', '</w>'], 2314],
 [['m', 'a', 'y', '</w>'], 2299],
 [['l', 'e', 'a', 'v', 'e', '</w>'], 2297],
 [['t', 'h', 'e', 's', 'e', '</w>'], 2289],
 [['o', 't', 'h', 'e', 'r', '</w>'], 2277],
 [['d', 'e', 'a', 'r', '</w>'], 2255],
 [['a', 'r', 'o', 'u', 'n', 'd', '</w>'], 2245],
 [['l', 'i', 'f', 'e', '</w>'], 2245],
 [['e', 'v', 'e', 'n', '</w>'], 2242],
 [['c', 'o', 'u', 'r', 's', 'e', '</w>'], 2213],
 [['m', 'o', 'n', 'e', 'y', '</w>'], 2207],
 [['w', 'o', 'u', 'l', 'd', 'n', '</w>'], 2160],
 [['n', 'e', 'w', '</w>'], 2154],
 [['m', 'o', 'r', 'n', 'i', 'n', 'g', '</w>'], 2147],
 [['r', 'e', 'a', 'l', 'l', 'y', '</w>'], 2098],
 [['n', 'a', 'm', 'e', '</w>'], 2067],
 [['n', 'i', 'c', 'e', '</w>'], 2061],
 [['m', 'a', 't', 't', 'e', 'r', '</w>'], 2051],
 [['e', 'v', 'e', 'r', 'y', 't', 'h', 'i', 'n', 'g', '</w>'], 2034],
 [['m', 'i', 'g', 'h', 't', '</w>'], 2030],
 [['w', 'o', 'r', 'k', '</w>'], 2029],
 [['h', 'a', 'v', 'e', 'n', '</w>'], 2015],
 [['s', 't', 'i', 'l', 'l', '</w>'], 2010],
 [[':', '</w>'], 1991],
 [['e', 'n', 'o', 'u', 'g', 'h', '</w>'], 1989],
 [['p', 'l', 'a', 'c', 'e', '</w>'], 1966],
 [['g', 'i', 'r', 'l', '</w>'], 1956],
 [['m', 'e', 'n', '</w>'], 1953],
 [['d', 'o', 'i', 'n', 'g', '</w>'], 1934],
 [['d', 'o', 'e', 's', '</w>'], 1933],
 [['c', 'a', 'l', 'l', '</w>'], 1911],
 [['t', 'h', 'a', 'n', 'k', 's', '</w>'], 1896],
 [['h', 'e', 'y', '</w>'], 1882],
 [['n', 'e', 'e', 'd', '</w>'], 1876],
 [['s', 't', 'a', 'y', '</w>'], 1861],
 [['s', 't', 'o', 'p', '</w>'], 1823],
 [['h', 'o', 'u', 's', 'e', '</w>'], 1787],
 [['c', 'a', 'm', 'e', '</w>'], 1777],
 [['r', 'e', 'm', 'e', 'm', 'b', 'e', 'r', '</w>'], 1771],
 [['y', 'e', 'a', 'r', 's', '</w>'], 1757],
 [['a', 's', 'k', '</w>'], 1757],
 [['a', 'n', 'o', 't', 'h', 'e', 'r', '</w>'], 1757],
 [['r', 'o', 'o', 'm', '</w>'], 1751],
 [['h', 'e', 'a', 'r', '</w>'], 1737],
 [['y', 'o', 'u', 'r', 's', 'e', 'l', 'f', '</w>'], 1734],
 [['t', 'h', 'r', 'o', 'u', 'g', 'h', '</w>'], 1734],
 [['b', 'o', 'y', '</w>'], 1733],
 [['a', 'f', 'r', 'a', 'i', 'd', '</w>'], 1721],
 [['d', 'o', 'e', 's', 'n', '</w>'], 1714],
 [['u', 'n', 'd', 'e', 'r', 's', 't', 'a', 'n', 'd', '</w>'], 1690],
 [['m', 'a', 'd', 'e', '</w>'], 1681],
 [['d', 'o', 'n', 'e', '</w>'], 1673],
 [['t', 'h', 'e', 'i', 'r', '</w>'], 1670],
 [['b', 'i', 'g', '</w>'], 1668],
 [['c', 'o', 'm', 'i', 'n', 'g', '</w>'], 1659],
 [['b', 'e', 'l', 'i', 'e', 'v', 'e', '</w>'], 1656],
 [['g', 'r', 'e', 'a', 't', '</w>'], 1653],
 [['m', 'o', 't', 'h', 'e', 'r', '</w>'], 1653],
 [['l', 'e', 'f', 't', '</w>'], 1651],
 [['f', 'e', 'e', 'l', '</w>'], 1647],
 [['t', 'o', 'n', 'i', 'g', 'h', 't', '</w>'], 1646],
 [['e', 'v', 'e', 'r', 'y', '</w>'], 1620],
 [['c', 'o', 'u', 'l', 'd', 'n', '</w>'], 1609],
 [['s', 'h', 'a', 'l', 'l', '</w>'], 1607],
 [['b', 'a', 'd', '</w>'], 1605],
 [['k', 'i', 'n', 'd', '</w>'], 1582],
 [['o', 'w', 'n', '</w>'], 1565],
 [['t', 'h', 'r', 'e', 'e', '</w>'], 1553],
 [['w', 'o', 'm', 'a', 'n', '</w>'], 1527],
 [['c', 'a', 'r', 'e', '</w>'], 1511],
 [['d', 'a', 'r', 'l', 'i', 'n', 'g', '</w>'], 1498],
 [['l', 'i', 's', 't', 'e', 'n', '</w>'], 1496],
 [['d', 'o', 'c', 't', 'o', 'r', '</w>'], 1493],
 [['w', 'a', 'n', 't', 'e', 'd', '</w>'], 1492],
 [['m', 'y', 's', 'e', 'l', 'f', '</w>'], 1484],
 [['f', 'r', 'i', 'e', 'n', 'd', '</w>'], 1474],
 [['l', 'o', 't', '</w>'], 1456],
 [['s', 'e', 'e', 'n', '</w>'], 1455],
 [['o', 'n', 'c', 'e', '</w>'], 1446],
 [['m', 'i', 'n', 'u', 't', 'e', '</w>'], 1438],
 [['e', 'l', 's', 'e', '</w>'], 1430],
 [['w', 'o', 'r', 'l', 'd', '</w>'], 1412],
 [['b', 'u', 's', 'i', 'n', 'e', 's', 's', '</w>'], 1411],
 [['h', 'e', 'a', 'r', 'd', '</w>'], 1410],
 [['s', 'u', 'c', 'h', '</w>'], 1395],
 [['f', 'i', 'n', 'e', '</w>'], 1394],
 [['t', 'o', 'm', 'o', 'r', 'r', 'o', 'w', '</w>'], 1389],
 [['p', 'r', 'e', 't', 't', 'y', '</w>'], 1388],
 [['d', 'r', '</w>'], 1385],
 [['s', 'i', 't', '</w>'], 1383],
 [['s', 'h', 'o', 'w', '</w>'], 1372],
 [['l', 'a', 'd', 'y', '</w>'], 1363],
 [['w', 'i', 'f', 'e', '</w>'], 1361],
 [['t', 'r', 'y', '</w>'], 1354],
 [['a', 'l', 'o', 'n', 'e', '</w>'], 1343],
 [['q', 'u', 'i', 't', 'e', '</w>'], 1341],
 [['h', 'o', 'p', 'e', '</w>'], 1335],
 [['y', 'o', 'u', 'n', 'g', '</w>'], 1328],
 [['b', 'r', 'i', 'n', 'g', '</w>'], 1313],
 [['d', 'e', 'a', 'd', '</w>'], 1312],
 [['w', 'a', 's', 'n', '</w>'], 1303],
 [['k', 'n', 'e', 'w', '</w>'], 1299],
 [['y', 'e', 't', '</w>'], 1295],
 [['w', 'i', 't', 'h', 'o', 'u', 't', '</w>'], 1287],
 [['g', 'u', 'e', 's', 's', '</w>'], 1284],
 [['s', 'a', 'm', 'e', '</w>'], 1282],
 [['b', 'e', 'i', 'n', 'g', '</w>'], 1270],
 [['g', 'e', 't', 't', 'i', 'n', 'g', '</w>'], 1264],
 [['i', 'd', 'e', 'a', '</w>'], 1260],
 [['l', 'i', 'v', 'e', '</w>'], 1252],
 [['l', 'o', 'o', 'k', 'i', 'n', 'g', '</w>'], 1236],
 [['w', 'r', 'o', 'n', 'g', '</w>'], 1236],
 [['s', 'u', 'p', 'p', 'o', 's', 'e', '</w>'], 1234],
 [['w', 'i', 's', 'h', '</w>'], 1231],
 [['h', 'a', 'p', 'p', 'e', 'n', 'e', 'd', '</w>'], 1229],
 [['w', 'h', 'i', 'l', 'e', '</w>'], 1227],
 [['h', 'a', 'p', 'p', 'y', '</w>'], 1224],
 [['s', 'a', 'w', '</w>'], 1218],
 [['b', 'o', 'y', 's', '</w>'], 1213],
 [['a', 'l', 'o', 'n', 'g', '</w>'], 1201],
 [['m', 'o', 's', 't', '</w>'], 1192],
 [['w', 'e', 'n', 't', '</w>'], 1188],
 [['s', 'o', 'o', 'n', '</w>'], 1187],
 [['d', 'r', 'i', 'n', 'k', '</w>'], 1172],
 [['f', 'o', 'u', 'n', 'd', '</w>'], 1165],
 [['g', 'u', 'y', '</w>'], 1156],
 [['t', 'r', 'o', 'u', 'b', 'l', 'e', '</w>'], 1153],
 [['n', 'e', 'x', 't', '</w>'], 1141],
 [['g', 'o', 'n', 'e', '</w>'], 1138],
 [['b', 'e', 's', 't', '</w>'], 1125],
 [['u', 'h', '</w>'], 1121],
 [['u', 'n', 't', 'i', 'l', '</w>'], 1115],
 [['g', 'e', 'n', 't', 'l', 'e', 'm', 'e', 'n', '</w>'], 1115],
 [['t', 'o', 'w', 'n', '</w>'], 1112],
 [['h', 'e', 'a', 'd', '</w>'], 1109],
 [['d', 'a', 'y', 's', '</w>'], 1107],
 [['s', 'i', 'n', 'c', 'e', '</w>'], 1104],
 [['f', 'e', 'w', '</w>'], 1104],
 [['g', 'l', 'a', 'd', '</w>'], 1102],
 [['t', 'o', 'd', 'a', 'y', '</w>'], 1097],
 [['j', 'o', 'b', '</w>'], 1096],
 [['m', 'a', 'n', 'y', '</w>'], 1095],
 [['m', 'a', 'r', 'r', 'i', 'e', 'd', '</w>'], 1092],
 [['r', 'e', 'a', 'd', 'y', '</w>'], 1087],
 [['w', 'h', 'o', 'l', 'e', '</w>'], 1083],
 [['t', 'r', 'y', 'i', 'n', 'g', '</w>'], 1077],
 [['h', 'o', 'l', 'd', '</w>'], 1076],
 [['t', 'a', 'l', 'k', 'i', 'n', 'g', '</w>'], 1070],
 [['r', 'u', 'n', '</w>'], 1068],
 [['f', 'o', 'r', 'g', 'e', 't', '</w>'], 1041],
 [['p', 'e', 'r', 'h', 'a', 'p', 's', '</w>'], 1038],
 [['h', 'a', 'n', 'd', '</w>'], 1033],
 [['w', 'a', 'i', 't', 'i', 'n', 'g', '</w>'], 1030],
 [['u', 's', 'e', '</w>'], 1029],
 [['s', 't', 'a', 'n', 'd', '</w>'], 1023],
 [['c', 'a', 'p', 't', 'a', 'i', 'n', '</w>'], 1019],
 [['s', 'a', 'y', 's', '</w>'], 1018],
 [['m', 'i', 'n', 'e', '</w>'], 1016],
 [['k', 'i', 'l', 'l', '</w>'], 996],
 [['w', 'h', 'i', 'c', 'h', '</w>'], 994],
 [['o', 'k', 'a', 'y', '</w>'], 993],
 [['m', 'e', 'e', 't', '</w>'], 992],
 [['e', 'v', 'e', 'n', 'i', 'n', 'g', '</w>'], 984],
 [['o', 'p', 'e', 'n', '</w>'], 981],
 [['u', 's', 'e', 'd', '</w>'], 973],
 [['t', 'o', 'g', 'e', 't', 'h', 'e', 'r', '</w>'], 968],
 [['h', 'u', 'h', '</w>'], 967],
 [['w', 'a', 'n', 't', 's', '</w>'], 963],
 [['p', 'l', 'a', 'y', '</w>'], 961],
 [['a', 'g', 'o', '</w>'], 957],
 [['s', 'o', 'm', 'e', 'b', 'o', 'd', 'y', '</w>'], 956],
 [['p', 'o', 'l', 'i', 'c', 'e', '</w>'], 954],
 [['b', 'e', 'a', 'u', 't', 'i', 'f', 'u', 'l', '</w>'], 952],
 [['c', 'a', 's', 'e', '</w>'], 944],
 [['s', 'e', 'n', 'd', '</w>'], 944],
 [['a', 'r', 'e', 'n', '</w>'], 943],
 [['w', 'o', 'r', 'r', 'y', '</w>'], 927],
 [['h', 'u', 's', 'b', 'a', 'n', 'd', '</w>'], 924],
 [['t', 'o', 'o', 'k', '</w>'], 924],
 [['k', 'i', 'l', 'l', 'e', 'd', '</w>'], 921],
 [['p', 'a', 'y', '</w>'], 918],
 [['c', 'h', 'a', 'n', 'c', 'e', '</w>'], 918],
 [['d', 'o', 'o', 'r', '</w>'], 913],
 [['n', 'o', 'b', 'o', 'd', 'y', '</w>'], 906],
 [['p', 'o', 'o', 'r', '</w>'], 903],
 [['h', 'u', 'r', 'r', 'y', '</w>'], 898],
 [['w', 'a', 't', 'e', 'r', '</w>'], 896],
 [['u', 'n', 'd', 'e', 'r', '</w>'], 892],
 [['s', 'o', 'n', '</w>'], 890],
 [['f', 'r', 'i', 'e', 'n', 'd', 's', '</w>'], 883],
 [['l', 'a', 't', 'e', 'r', '</w>'], 879],
 [['t', 'u', 'r', 'n', '</w>'], 875],
 [['w', 'o', 'r', 'd', '</w>'], 871],
 [['s', 'p', 'e', 'a', 'k', '</w>'], 869],
 [['s', 'l', 'e', 'e', 'p', '</w>'], 861],
 [['s', 't', 'a', 'r', 't', '</w>'], 860],
 [['b', 'o', 't', 'h', '</w>'], 858],
 [['l', 'a', 't', 'e', '</w>'], 855],
 [['s', 'o', 'm', 'e', 'o', 'n', 'e', '</w>'], 853],
 [['h', 'a', 'n', 'd', 's', '</w>'], 852],
 [['f', 'i', 'v', 'e', '</w>'], 852],
 [['y', 'o', 'u', 'r', 's', '</w>'], 844],
 [['f', 'a', 'c', 'e', '</w>'], 835],
 [['h', 'e', 'a', 'r', 't', '</w>'], 835],
 [['e', 'x', 'c', 'u', 's', 'e', '</w>'], 835],
 [['c', 'o', 'u', 'n', 't', 'r', 'y', '</w>'], 830],
 [['e', 'v', 'e', 'r', 'y', 'b', 'o', 'd', 'y', '</w>'], 830],
 [['e', 'a', 's', 'y', '</w>'], 829],
 [['w', 'o', 'n', 'd', 'e', 'r', 'f', 'u', 'l', '</w>'], 829],
 [['f', 'a', 'r', '</w>'], 826],
 [['d', 'e', 'a', 't', 'h', '</w>'], 822],
 [['r', 'e', 's', 't', '</w>'], 819],
 [['m', 'o', 'm', 'e', 'n', 't', '</w>'], 811],
 [['b', 'a', 'b', 'y', '</w>'], 809],
 [['c', 'a', 'r', '</w>'], 807],
 [['a', 'g', 'a', 'i', 'n', 's', 't', '</w>'], 807],
 [['l', 'o', 'o', 'k', 's', '</w>'], 803],
 [['c', 'o', 'm', 'e', 's', '</w>'], 803],
 [['t', 'h', 'i', 'n', 'k', 'i', 'n', 'g', '</w>'], 800],
 [['w', 'a', 'r', '</w>'], 795],
 [['k', 'n', 'o', 'w', 's', '</w>'], 793],
 [['r', 'a', 't', 'h', 'e', 'r', '</w>'], 791],
 [['g', 'a', 'v', 'e', '</w>'], 790],
 [['h', 'a', 'r', 'd', '</w>'], 788],
 [['e', 'y', 'e', 's', '</w>'], 788],
 [['a', 'n', 'y', 'b', 'o', 'd', 'y', '</w>'], 787],
 [['r', 'e', 'a', 'd', '</w>'], 787],
 [['l', 'o', 's', 't', '</w>'], 783],
 [['w', 'a', 't', 'c', 'h', '</w>'], 782],
 [['h', 'u', 'r', 't', '</w>'], 780],
 [['b', 'r', 'o', 't', 'h', 'e', 'r', '</w>'], 777],
 [['o', 'u', 'g', 'h', 't', '</w>'], 775],
 [['b', 'e', 'd', '</w>'], 774],
 [['a', 'n', 'y', 'o', 'n', 'e', '</w>'], 765],
 [['c', 'e', 'r', 't', 'a', 'i', 'n', 'l', 'y', '</w>'], 765],
 [['f', 'i', 'g', 'h', 't', '</w>'], 763],
 [['b', 'i', 't', '</w>'], 763],
 [['g', 'o', 'd', '</w>'], 760],
 [['c', 'h', 'i', 'l', 'd', '</w>'], 759],
 [['h', 'a', 'l', 'f', '</w>'], 755],
 [['k', 'i', 'd', '</w>'], 755],
 [['g', 'o', 'o', 'd', 'b', 'y', 'e', '</w>'], 752],
 [['e', 'a', 'c', 'h', '</w>'], 751],
 [['t', 'i', 'l', 'l', '</w>'], 750],
 [['h', 'a', 'p', 'p', 'e', 'n', '</w>'], 743],
 [['y', 'e', 'a', 'r', '</w>'], 737],
 [['m', 'a', 'r', 'r', 'y', '</w>'], 734],
 [['t', 'r', 'u', 'e', '</w>'], 733],
 [['e', 'a', 't', '</w>'], 726],
 [["'", 'e', 'm', '</w>'], 718],
 [['d', 'i', 'e', '</w>'], 717],
 [['a', 'n', 'y', 'w', 'a', 'y', '</w>'], 717],
 [['a', 'h', 'e', 'a', 'd', '</w>'], 717],
 [['s', 'i', 's', 't', 'e', 'r', '</w>'], 715],
 [['m', 'a', 'k', 'e', 's', '</w>'], 713],
 [['g', 'u', 'n', '</w>'], 712],
 [['b', 'r', 'o', 'u', 'g', 'h', 't', '</w>'], 706],
 [['s', 'e', 'e', 'm', 's', '</w>'], 705],
 [['e', 'n', 'd', '</w>'], 700],
 [['o', 'f', 'f', 'i', 'c', 'e', '</w>'], 700],
 [['m', 'i', 'n', 'u', 't', 'e', 's', '</w>'], 700],
 [['l', '</w>'], 699],
 [['f', 'o', 'u', 'r', '</w>'], 695],
 [['t', 'a', 'k', 'i', 'n', 'g', '</w>'], 692],
 [['d', 'i', 'n', 'n', 'e', 'r', '</w>'], 691],
 [['t', 'r', 'a', 'i', 'n', '</w>'], 690],
 [['m', 'a', '</w>'], 688],
 [['w', 'o', 'm', 'e', 'n', '</w>'], 687],
 [['f', 'u', 'n', 'n', 'y', '</w>'], 685],
 [['f', 'i', 'r', 'e', '</w>'], 685],
 [['m', 'o', 'n', 's', 'i', 'e', 'u', 'r', '</w>'], 683],
 [['f', 'o', 'o', 'l', '</w>'], 681],
 [['c', 'h', 'a', 'n', 'g', 'e', '</w>'], 681],
 [['g', 'o', 'e', 's', '</w>'], 679],
 [['a', 'l', 'r', 'e', 'a', 'd', 'y', '</w>'], 678],
 [['c', 'r', 'a', 'z', 'y', '</w>'], 676],
 [['a', 's', 'k', 'e', 'd', '</w>'], 672],
 [['g', 'e', 'o', 'r', 'g', 'e', '</w>'], 670],
 [['i', 'm', 'p', 'o', 'r', 't', 'a', 'n', 't', '</w>'], 668],
 [['q', 'u', 'i', 'e', 't', '</w>'], 667],
 [['g', 'o', 't', 't', 'a', '</w>'], 662],
 [['f', 'e', 'l', 'l', 'o', 'w', '</w>'], 660],
 [['j', 'o', 'e', '</w>'], 660],
 [['b', 'e', 't', '</w>'], 659],
 [['c', 'a', 'l', 'l', 'e', 'd', '</w>'], 645],
 [['l', 'u', 'c', 'k', '</w>'], 642],
 [["'", '</w>'], 642],
 [['s', 't', 'o', 'r', 'y', '</w>'], 641],
 [['b', 'r', 'e', 'a', 'k', '</w>'], 637],
 [['h', 'o', 'u', 'r', '</w>'], 636],
 [['b', 'u', 'y', '</w>'], 635],
 [['h', 'a', 'v', 'i', 'n', 'g', '</w>'], 633],
 [['l', 'a', 'w', '</w>'], 631],
 [['o', '</w>'], 629],
 [['s', 'e', 'n', 't', '</w>'], 629],
 [['c', 'h', 'i', 'l', 'd', 'r', 'e', 'n', '</w>'], 627],
 [['m', 'e', 't', '</w>'], 626],
 [['1', '0', '</w>'], 626],
 [['s', 'h', 'o', 't', '</w>'], 626],
 [['a', 'n', 's', 'w', 'e', 'r', '</w>'], 624],
 [['w', 'e', 'e', 'k', '</w>'], 622],
 [['s', 'o', 'r', 't', '</w>'], 621],
 [['w', 'a', 'l', 'k', '</w>'], 619],
 [['k', 'i', 'n', 'g', '</w>'], 618],
 [['m', 'e', 'a', 'n', 's', '</w>'], 617],
 [['r', 'e', 'a', 'l', '</w>'], 615],
 [['t', 'r', 'i', 'e', 'd', '</w>'], 609],
 [['h', 'a', 't', 'e', '</w>'], 603],
 [['g', 'e', 't', 's', '</w>'], 600],
 [['l', 'e', 'a', 'v', 'i', 'n', 'g', '</w>'], 600],
 [['d', 'a', 'u', 'g', 'h', 't', 'e', 'r', '</w>'], 598],
 [['b', 'i', 'l', 'l', '</w>'], 598],
 [['t', 'i', 'm', 'e', 's', '</w>'], 597],

In [102]:
def most_common_pair(vocab_chars):
    freq_pair = defaultdict(int)
    for toks, freq in vocab_chars:
        toks_pairs = [" ".join(pair) for pair in zip(toks, toks[1:])]
        for pair in toks_pairs:
            freq_pair[pair] += freq
    return max(freq_pair.items(), key=lambda x: x[1])[0]

In [190]:
pair_counts = Counter()
pair_counts[('t','h')] += 10
pair_counts[('t','h')] += 10
pair_counts.most_common(1)

[(('t', 'h'), 20)]

In [144]:
def bpe_tokenizer(vocab_chars, vocab_list, vocab_size):
    for _ in range(vocab_size):
        pair = most_common_pair(vocab_chars)
        vocab_list.append(re.sub('\s+', '', pair))
        print(pair)
        vocab_chars = connect_pairs(vocab_chars, pair)