## 06. scratchpad

In [28]:
import pickle
import pandas as pd
import Data
import re
from collections import Counter
from tqdm.notebook import tqdm

In [3]:
# with open("../data/dataframe_eng.pkl", 'rb') as f:
#     data_eng = pickle.load(f)

# with open("../data/dataframe_pol.pkl", 'rb') as f:
#     data_pol = pickle.load(f)

In [2]:
# with open("../data/bpe_tokenizer_eng.pkl", 'rb') as f:
#     tokenizer_eng = pickle.load(f)
    
# with open("../data/bpe_tokenizer_pol.pkl", 'rb') as f:
#     tokenizer_pol = pickle.load(f)

### New data

In [4]:
with open('../data/europarl/europarl-v7.pl-en.en', 'r', encoding='utf-8') as f:
    eng_lines = f.readlines()

with open('../data/europarl/europarl-v7.pl-en.pl', 'r', encoding='utf-8') as f:
    pol_lines = f.readlines()

pairs = [(e.strip(), p.strip()) for e, p in zip(eng_lines, pol_lines)
         if e.strip() and p.strip() 
         and not e.strip().startswith('<') 
         and not p.strip().startswith('<')]

df_europarl = pd.DataFrame(pairs, columns=['eng_text', 'pol_text'])
print(len(df_europarl))
df_europarl.head()

629380

,eng_text,pol_text
0,Action taken on Parliament's resolutions: see ...,Działania podjęte w wyniku rezolucji Parlament...
1,Documents received: see Minutes,Składanie dokumentów: patrz protokół
2,Written statements (Rule 116): see Minutes,Oświadczenia pisemne (art. 116 Regulaminu): pa...
3,Texts of agreements forwarded by the Council: ...,Teksty porozumień przekazane przez Radę: patrz...
4,Membership of Parliament: see Minutes,Skład Parlamentu: patrz protokół

In [5]:
requir = lambda x: re.sub(r"^[(]..[)]", "", x)
df_europarl['eng_text'] = df_europarl['eng_text'].apply(requir)
df_europarl['pol_text'] = df_europarl['pol_text'].apply(requir)

In [6]:
mask_eng = df_europarl['eng_text'].apply(lambda x: bool(re.search(r".+[(].+[)].+", x)))
mask_pol = df_europarl['pol_text'].apply(lambda x: bool(re.search(r".+[(].+[)].+", x)))

In [7]:
mask_eng.sum(), mask_pol.sum(), (mask_eng | mask_pol).sum()

(22461, 21196, 25231)

In [8]:
df_europarl = df_europarl[~(mask_eng | mask_pol)].reset_index(drop=True)
df_europarl

,eng_text,pol_text
0,Action taken on Parliament's resolutions: see ...,Działania podjęte w wyniku rezolucji Parlament...
1,Documents received: see Minutes,Składanie dokumentów: patrz protokół
2,Texts of agreements forwarded by the Council: ...,Teksty porozumień przekazane przez Radę: patrz...
3,Membership of Parliament: see Minutes,Skład Parlamentu: patrz protokół
4,Membership of committees and delegations: see ...,Skład komisji i delegacji: patrz protokół
...,...,...
604144,Composition of committees and delegations : se...,Skład komisji i delegacji: Patrz protokól
604145,Agenda of the next sitting : see Minutes,Porządek obrad następnego posiedzenia: Patrz p...
604146,Closure of the sitting,Zamknięcie posiedzenia
604147,(The sitting closed at 22.25),(The sitting closed at 22.25)
604148,. -,. -

In [9]:
uniq_eng = set("".join(df_europarl["eng_text"].astype(str)))
uniq_pol = set("".join(df_europarl["pol_text"].astype(str)))
print(f"Eng uniq: {len(uniq_eng)} | Pol uniq: {len(uniq_pol)}")

Eng uniq: 262 | Pol uniq: 267

In [10]:
tgt_eng = ['z', 'y', 'x', 'w', 'v', 'u', 't', 's', 'r', 'q', 'p', 'o', 'n', 'm', 'l', 'k', 'j', 'i', 'h', 'g', 'f', 'e', 'd', 'c', 'b', 'a', ']', '[', 'Z', 'Y', 'X', 'W', 'V', 'U', 'T', 'S', 'R', 'Q', 'P', 'O', 'N', 'M', 'L', 'K', 'J', 'I', 'H', 'G', 'F', 'E', 'D', 'C', 'B', 'A', '?', ':', '9', '8', '7', '6', '5', '4', '3', '2', '1', '0', '/', '.', '-', ',', ')', '(', "'", '%', '"', '!', ' ', ';']
tgt_pol = ['ż', 'Ż', 'ź', 'Ź', 'ś', 'Ś', 'ń', 'Ń', 'ł', 'Ł', 'ę', 'Ę', 'ć', 'Ć', 'ą', 'Ą', 'ó', 'Ó', 'z', 'y', 'x', 'w', 'v', 'u', 't', 's', 'r', 'q', 'p', 'o', 'n', 'm', 'l', 'k', 'j', 'i', 'h', 'g', 'f', 'e', 'd', 'c', 'b', 'a', ']', '[', 'Z', 'Y', 'X', 'W', 'V', 'U', 'T', 'S', 'R', 'Q', 'P', 'O', 'N', 'M', 'L', 'K', 'J', 'I', 'H', 'G', 'F', 'E', 'D', 'C', 'B', 'A', '?', ':', '9', '8', '7', '6', '5', '4', '3', '2', '1', '0', '/', '.', '-', ',', ')', '(', "'", '%', '"', '!', ' ', ';']

In [11]:
eng_delchars = [x for x in sorted(list(uniq_eng), reverse=True) if x not in tgt_eng]
pol_delchars = [x for x in sorted(list(uniq_pol), reverse=True) if x not in tgt_pol]
regex_eng = "[" + "".join(map(re.escape, eng_delchars)) + "]"
regex_pol = "[" + "".join(map(re.escape, pol_delchars)) + "]"

In [13]:
mask_eng = df_europarl["eng_text"].str.contains(regex_eng, na=False)
mask_pol = df_europarl["pol_text"].str.contains(regex_pol, na=False)
mask_eng.sum(), mask_pol.sum(), (mask_eng | mask_pol).sum()

(10115, 21667, 24257)

In [14]:
df_europarl = df_europarl[~(mask_eng | mask_pol)].reset_index(drop=True)
#df_europarl = df_europarl[~mask_eng].reset_index(drop=True)

In [15]:
uniq_eng = set("".join(df_europarl["eng_text"].astype(str)))
uniq_pol = set("".join(df_europarl["pol_text"].astype(str)))
print(f"Eng uniq: {len(uniq_eng)} | Pol uniq: {len(uniq_pol)}")

Eng uniq: 78 | Pol uniq: 94

In [17]:
mask_1 = (df_europarl["eng_text"].str[-1] == '.') & (df_europarl["pol_text"].str[-1] != '.')
mask_2 = (df_europarl["eng_text"].str[-1] != '.') & (df_europarl["pol_text"].str[-1] == '.')

In [18]:
mask_1.sum(), mask_2.sum(), (mask_1 | mask_2).sum()

(1960, 1108, 3068)

In [19]:
(~(mask_1 | mask_2)).sum()

576824

In [20]:
df_europarl = df_europarl[~(mask_1 | mask_2)].reset_index(drop=True)

In [21]:
def tokenize_eng(snt):
    snt = snt.lower()
    snt = re.sub("(?<! )'(?! )", r" '", snt)
    snt = re.sub(r"""([\]?:)\[(/\.\-,%\$"!])""", r" \1 ", snt)
    snt = re.sub(r"\s+", " ", snt).strip()
    return re.split(r'\s+', snt.strip())

def tokenize_pol(snt):
    snt = snt.lower()
    snt = re.sub(r"""([\]?:)\[(/\.\-,%\$"!])""", r" \1 ", snt)
    snt = re.sub(r"\s+", " ", snt).strip()
    return re.split(r'\s+', snt.strip())

In [22]:
df_europarl['eng_split'] = df_europarl["eng_text"].apply(tokenize_eng)
df_europarl['pol_split'] = df_europarl["pol_text"].apply(tokenize_pol)

In [23]:
df_europarl['eng_split']

0         [action, taken, on, parliament, 's, resolution...
1                    [documents, received, :, see, minutes]
2         [texts, of, agreements, forwarded, by, the, co...
3             [membership, of, parliament, :, see, minutes]
4         [membership, of, committees, and, delegations,...
                                ...
576819    [composition, of, committees, and, delegations...
576820    [agenda, of, the, next, sitting, :, see, minutes]
576821                          [closure, of, the, sitting]
576822          [(, the, sitting, closed, at, 22, ., 25, )]
576823                                               [., -]
Name: eng_split, Length: 576824, dtype: object

In [24]:
uniq_freq_eng = Counter(df_europarl['eng_split'].explode())
uniq_freq_pol = Counter(df_europarl['pol_split'].explode())

In [25]:
char_factor = lambda word: [x for x in word] + ['_']
vocab_chars_eng = [[char_factor(k), v] for k, v in uniq_freq_eng.most_common()]
vocab_chars_pol = [[char_factor(k), v] for k, v in uniq_freq_pol.most_common()]
print(len(vocab_chars_eng), vocab_chars_eng[:5], '\n')
print(len(vocab_chars_pol), vocab_chars_pol[:5])

50655 [[['t', 'h', 'e', '_'], 1019855], [[',', '_'], 712258], [['.', '_'], 562408], [['o', 'f', '_'], 488571], [['t', 'o', '_'], 458481]]

158653 [[[',', '_'], 876176], [['.', '_'], 578767], [['w', '_'], 432544], [['i', '_'], 304762], [['n', 'a', '_'], 192303]]

In [26]:
pair_vocab_eng = [[list(zip(tab, tab[1:])), v] for tab, v in vocab_chars_eng]
pair_vocab_pol = [[list(zip(tab, tab[1:])), v] for tab, v in vocab_chars_pol]

In [29]:
from BPE_tokenizer import BPETokenizer

In [30]:
tokenizer_eng = BPETokenizer(vocab_chars_eng, pair_vocab_eng, 12000, 600, False)
tokenizer_eng.train_bpe()

  0%|          | 0/11945 [00:00<?, ?it/s]

In [32]:
tokenizer_pol = BPETokenizer(vocab_chars_pol, pair_vocab_pol, 24000, 600, True)
tokenizer_pol.train_bpe()

  0%|          | 0/23935 [00:00<?, ?it/s]

In [35]:
df_eng = df_europarl[['eng_text', 'eng_split']]
df_pol = df_europarl[['pol_text', 'pol_split']]

In [37]:
df_eng.head()

,eng_text,eng_split
0,Action taken on Parliament's resolutions: see ...,"[action, taken, on, parliament, 's, resolution..."
1,Documents received: see Minutes,"[documents, received, :, see, minutes]"
2,Texts of agreements forwarded by the Council: ...,"[texts, of, agreements, forwarded, by, the, co..."
3,Membership of Parliament: see Minutes,"[membership, of, parliament, :, see, minutes]"
4,Membership of committees and delegations: see ...,"[membership, of, committees, and, delegations,..."

In [41]:
encoder_eng1.vocab_encoder

{'<pad>': 0,
 '<unk>': 1,
 '<eos>': 2,
 '_': 3,
 'a': 4,
 'b': 5,
 '5': 6,
 'g': 7,
 '2': 8,
 'u': 9,
 's': 10,
 'x': 11,
 'n': 12,
 'y': 13,
 '3': 14,
 't': 15,
 ')': 16,
 "'": 17,
 ']': 18,
 '1': 19,
 '"': 20,
 'p': 21,
 'w': 22,
 'j': 23,
 '/': 24,
 'k': 25,
 '!': 26,
 'f': 27,
 '-': 28,
 'i': 29,
 '8': 30,
 'o': 31,
 'm': 32,
 '[': 33,
 '?': 34,
 'r': 35,
 'h': 36,
 'l': 37,
 '6': 38,
 '7': 39,
 '0': 40,
 '9': 41,
 '%': 42,
 ';': 43,
 '4': 44,
 'd': 45,
 'q': 46,
 'z': 47,
 '.': 48,
 'c': 49,
 ':': 50,
 'e': 51,
 '(': 52,
 'v': 53,
 ',': 54,
 'e_': 55,
 'th': 56,
 's_': 57,
 't_': 58,
 'n_': 59,
 'd_': 60,
 'the_': 61,
 'in': 62,
 'er': 63,
 'an': 64,
 'y_': 65,
 'ti': 66,
 're': 67,
 ',_': 68,
 'o_': 69,
 'or': 70,
 'en': 71,
 'al': 72,
 'on_': 73,
 '._': 74,
 'f_': 75,
 'on': 76,
 'ar': 77,
 'of_': 78,
 'ou': 79,
 'to_': 80,
 'and_': 81,
 'ro': 82,
 'is_': 83,
 'g_': 84,
 'in_': 85,
 'ing_': 86,
 'ed_': 87,
 'es_': 88,
 'is': 89,
 'at_': 90,
 'a_': 91,
 'er_': 92,
 'ic': 93,
 'at': 94,
 'st': 95,
 'si': 96,
 'om': 97,
 'ec': 98,
 'al_': 99,
 'tion_': 100,
 'for': 101,
 'l_': 102,
 'that_': 103,
 'an_': 104,
 'em': 105,
 'it': 106,
 'ent_': 107,
 've_': 108,
 'ly_': 109,
 'ac': 110,
 'ha': 111,
 'pro': 112,
 'su': 113,
 'wi': 114,
 'li': 115,
 'eu': 116,
 'wh': 117,
 'h_': 118,
 'es': 119,
 'com': 120,
 'for_': 121,
 'we_': 122,
 'un': 123,
 'pe': 124,
 'i_': 125,
 'r_': 126,
 'po': 127,
 'no': 128,
 'this_': 129,
 'am': 130,
 'en_': 131,
 'it_': 132,
 'con': 133,
 'le_': 134,
 'us': 135,
 'ation_': 136,
 'as_': 137,
 'ts_': 138,
 'ri': 139,
 'el': 140,
 'as': 141,
 'th_': 142,
 'euro': 143,
 'tion': 144,
 'por': 145,
 'op': 146,
 'ur': 147,
 'are_': 148,
 'ci': 149,
 'be_': 150,
 'ad': 151,
 'ev': 152,
 'ag': 153,
 'ab': 154,
 'ld_': 155,
 '-_': 156,
 'be': 157,
 'w_': 158,
 'res': 159,
 'im': 160,
 'comm': 161,
 'not_': 162,
 'cou': 163,
 'ex': 164,
 'ul': 165,
 'k_': 166,
 'have_': 167,
 'le': 168,
 'europe': 169,
 'lo': 170,
 'ce_': 171,
 'european_': 172,
 'par': 173,
 'di': 174,
 'tr': 175,
 'with_': 176,
 'ne': 177,
 'll_': 178,
 'm_': 179,
 'ity_': 180,
 'ould_': 181,
 'ter': 182,
 'de': 183,
 'il': 184,
 'tions_': 185,
 'so_': 186,
 'sh': 187,
 'ate_': 188,
 'will_': 189,
 'ere_': 190,
 'gh': 191,
 'pre': 192,
 'ich_': 193,
 'ver': 194,
 'which_': 195,
 'bu': 196,
 'coun': 197,
 'ol': 198,
 'ta': 199,
 'vi': 200,
 'by_': 201,
 'our_': 202,
 'ap': 203,
 'sion_': 204,
 'pl': 205,
 'du': 206,
 'tic': 207,
 'ke_': 208,
 'qu': 209,
 'ch': 210,
 'ff': 211,
 'the': 212,
 'all_': 213,
 'ay_': 214,
 'sid': 215,
 'ment_': 216,
 'wor': 217,
 'ion_': 218,
 'has_': 219,
 'ers_': 220,
 'ted_': 221,
 'me': 222,
 'p_': 223,
 'ic_': 224,
 'port_': 225,
 'emb': 226,
 'ust_': 227,
 'se_': 228,
 'tive_': 229,
 'or_': 230,
 'str': 231,
 'ar_': 232,
 'commis': 233,
 'port': 234,
 'ther_': 235,
 'ds_': 236,
 'ma': 237,
 'also_': 238,
 'go': 239,
 'out_': 240,
 'gr': 241,
 'ir': 242,
 'st_': 243,
 'memb': 244,
 'co': 245,
 'ent': 246,
 'reg': 247,
 'mo': 248,
 'ant_': 249,
 'se': 250,
 'ow': 251,
 'ents_': 252,
 'stat': 253,
 'would_': 254,
 'able_': 255,
 'presid': 256,
 'fro': 257,
 "'s_": 258,
 'from_': 259,
 'tur': 260,
 'me_': 261,
 'ally_': 262,
 'pos': 263,
 'commission_': 264,
 'one_': 265,
 'should_': 266,
 'fin': 267,
 'tu': 268,
 'must_': 269,
 'pec': 270,
 'but_': 271,
 'et_': 272,
 'so': 273,
 'ch_': 274,
 'ra': 275,
 'eu_': 276,
 'ess_': 277,
 'you': 278,
 'member_': 279,
 'to': 280,
 'ir_': 281,
 'tri': 282,
 'mor': 283,
 'dis': 284,
 'man': 285,
 'union_': 286,
 'inter': 287,
 'use_': 288,
 'per': 289,
 'its_': 290,
 'econ': 291,
 'ations_': 292,
 'ding_': 293,
 'there_': 294,
 'states_': 295,
 'president_': 296,
 'liam': 297,
 'parliam': 298,
 'ting_': 299,
 'more_': 300,
 'rec': 301,
 'us_': 302,
 'mr_': 303,
 'bl': 304,
 'you_': 305,
 'em_': 306,
 'inc': 307,
 'ese_': 308,
 'min': 309,
 'duc': 310,
 'righ': 311,
 'been_': 312,
 'cial_': 313,
 'ties_': 314,
 'tional_': 315,
 'ement_': 316,
 'te': 317,
 'can_': 318,
 'pe_': 319,
 'are': 320,
 'pol': 321,
 'their_': 322,
 'um': 323,
 '20': 324,
 'ris': 325,
 'parliament_': 326,
 'king_': 327,
 'mar': 328,
 'these_': 329,
 'ance_': 330,
 'import': 331,
 'sup': 332,
 'ess': 333,
 'und': 334,
 'very_': 335,
 'lu': 336,
 'we': 337,
 'oc': 338,
 'pres': 339,
 'they_': 340,
 'end': 341,
 'ter_': 342,
 'ary_': 343,
 'ies_': 344,
 'ons_': 345,
 'europe_': 346,
 'ty_': 347,
 'ge_': 348,
 'was_': 349,
 'econom': 350,
 'sur': 351,
 'do_': 352,
 'sa': 353,
 'am_': 354,
 'polic': 355,
 'na': 356,
 'like_': 357,
 'ence_': 358,
 'bec': 359,
 'te_': 360,
 'la': 361,
 'ob': 362,
 'est': 363,
 'pu': 364,
 'other_': 365,
 'need_': 366,
 'report_': 367,
 'now_': 368,
 'ord': 369,
 'ther': 370,
 'sib': 371,
 'fac': 372,
 'evel': 373,
 'agre': 374,
 'gy_': 375,
 'vo': 376,
 'hi': 377,
 'ain': 378,
 'reat': 379,
 'ever_': 380,
 'fore_': 381,
 'cer': 382,
 'sec': 383,
 'fu': 384,
 'he': 385,
 'ous_': 386,
 'sti': 387,
 'ing': 388,
 'cont': 389,
 'gh_': 390,
 'what_': 391,
 'important_': 392,
 'countri': 393,
 'ener': 394,
 'bet': 395,
 'gi': 396,
 'countries_': 397,
 'pr': 398,
 'work_': 399,
 'peop': 400,
 'evelop': 401,
 'od_': 402,
 'develop': 403,
 'fi': 404,
 'ause_': 405,
 'tec': 406,
 'ce': 407,
 'enc': 408,
 'ser': 409,
 'reas': 410,
 'res_': 411,
 'gu': 412,
 'tiv': 413,
 'som': 414,
 'if_': 415,
 'people_': 416,
 'age_': 417,
 'fe': 418,
 'ely_': 419,
 'dec': 420,
 'leg': 421,
 'ye': 422,
 'about_': 423,
 'time_': 424,
 'counci': 425,
 'ade_': 426,
 'new_': 427,
 'jec': 428,
 'council_': 429,
 'mark': 430,
 'my_': 431,
 'national_': 432,
 'dem': 433,
 ':_': 434,
 'ated_': 435,
 'wel': 436,
 'ility_': 437,
 'who_': 438,
 '0_': 439,
 'ffic': 440,
 'id_': 441,
 'ren': 442,
 'ture_': 443,
 'only_': 444,
 'ans': 445,
 'our': 446,
 'propos': 447,
 'est_': 448,
 'rights_': 449,
 'ten': 450,
 'ard_': 451,
 'policy_': 452,
 'de_': 453,
 'because_': 454,
 'there': 455,
 'au': 456,
 'support_': 457,
 'how': 458,
 'gn': 459,
 'however_': 460,
 'cle': 461,
 'economic_': 462,
 'el_': 463,
 'issu': 464,
 'fir': 465,
 'sure_': 466,
 'day_': 467,
 'bo': 468,
 'ong_': 469,
 'olu': 470,
 'therefore_': 471,
 'eve_': 472,
 'pri': 473,
 'ose_': 474,
 'ge': 475,
 'fr': 476,
 'fa': 477,
 'lis': 478,
 'cour': 479,
 'ho': 480,
 'mon': 481,
 'ast_': 482,
 'form': 483,
 'finan': 484,
 'with': 485,
 'ough_': 486,
 'ded_': 487,
 'tical_': 488,
 'inv': 489,
 'such_': 490,
 'ans_': 491,
 'ise_': 492,
 'ght_': 493,
 'ffec': 494,
 'comp': 495,
 'trans': 496,
 'oun': 497,
 'oper': 498,
 'do': 499,
 'ay': 500,
 'up_': 501,
 'ticul': 502,
 'ever': 503,
 'emp': 504,
 'pon': 505,
 'sy': 506,
 'no_': 507,
 'direc': 508,
 'particul': 509,
 'poli': 510,
 'rel': 511,
 'ving_': 512,
 'fo': 513,
 'ween_': 514,
 'between_': 515,
 'ens_': 516,
 'acc': 517,
 'ks_': 518,
 'commit': 519,
 'sible_': 520,
 'when_': 521,
 'ments_': 522,
 'chan': 523,
 'take_': 524,
 'enti': 525,
 'tiz': 526,
 'citiz': 527,
 'produc': 528,
 'if': 529,
 'into_': 530,
 'spec': 531,
 'respon': 532,
 'protec': 533,
 'fun': 534,
 'many_': 535,
 '?_': 536,
 'those_': 537,
 'make_': 538,
 'ities_': 539,
 'try_': 540,
 'tic_': 541,
 'beli': 542,
 'way_': 543,
 'bas': 544,
 'poin': 545,
 'all': 546,
 'arly_': 547,
 'vis': 548,
 'come_': 549,
 'deb': 550,
 'als_': 551,
 'order_': 552,
 'market_': 553,
 'ating_': 554,
 'sel': 555,
 'some_': 556,
 'vic': 557,
 'energy_': 558,
 'probl': 559,
 'ency_': 560,
 'ef': 561,
 'appro': 562,
 'sub': 563,
 'ue_': 564,
 'thin': 565,
 'stru': 566,
 'social_': 567,
 'ad_': 568,
 'financial_': 569,
 'stan': 570,
 'sum': 571,
 'can': 572,
 'ass': 573,
 'publ': 574,
 'concer': 575,
 'ards_': 576,
 'gover': 577,
 'tly_': 578,
 'ces_': 579,
 'get_': 580,
 'syst': 581,
 'ame_': 582,
 'ver_': 583,
 'most_': 584,
 'posi': 585,
 'ia_': 586,
 'govern': 587,
 'stitu': 588,
 'fre': 589,
 'any_': 590,
 'them_': 591,
 'cris': 592,
 '200': 593,
 'believe_': 594,
 'mea': 595,
 'development_': 596,
 'own_': 597,
 'increas': 598,
 'ms_': 599,
 'ru': 600,
 'political_': 601,
 'cre': 602,
 'ars_': 603,
 'regul': 604,
 'ems_': 605,
 'ate': 606,
 'being_': 607,
 'again': 608,
 'citizens_': 609,
 'against_': 610,
 'gre': 611,
 'ine_': 612,
 'inclu': 613,
 'unity_': 614,
 'hum': 615,
 'sion': 616,
 'thing_': 617,
 'sul': 618,
 'ple_': 619,
 'situ': 620,
 'ved_': 621,
 'effec': 622,
 'cri': 623,
 'ace_': 624,
 'ps_': 625,
 'human_': 626,
 'alis': 627,
 'cur': 628,
 'mat': 629,
 'clear_': 630,
 'tor': 631,
 'ext_': 632,
 'provi': 633,
 'ach_': 634,
 'think_': 635,
 'crisis_': 636,
 'well_': 637,
 'ke': 638,
 'treat': 639,
 'agreement_': 640,
 'were_': 641,
 'than_': 642,
 'requ': 643,
 'made_': 644,
 'public_': 645,
 'mu': 646,
 'read': 647,
 'sures_': 648,
 'hel': 649,
 'olution_': 650,
 'ari': 651,
 'vie': 652,
 'mil': 653,
 'country_': 654,
 'end_': 655,
 'ques': 656,
 'today_': 657,
 'ental_': 658,
 ';_': 659,
 'bud': 660,
 'ings_': 661,
 'first_': 662,
 'grou': 663,
 'tee_': 664,
 'ves_': 665,
 'act_': 666,
 'sp': 667,
 'mi': 668,
 'ful': 669,
 'ffer': 670,
 'where_': 671,
 'cas': 672,
 'anis': 673,
 'situation_': 674,
 'low_': 675,
 'even_': 676,
 'red_': 677,
 'measures_': 678,
 'nec': 679,
 'impl': 680,
 'here_': 681,
 'lim': 682,
 'equ': 683,
 'cooper': 684,
 'af': 685,
 'just_': 686,
 'ions_': 687,
 'contin': 688,
 'secur': 689,
 'low': 690,
 'strate': 691,
 'thr': 692,
 'rit': 693,
 'right_': 694,
 'future_': 695,
 'iti': 696,
 'debate_': 697,
 'under': 698,
 'adop': 699,
 'fact_': 700,
 'curren': 701,
 'democ': 702,
 'struc': 703,
 'commission': 704,
 'lev': 705,
 'than': 706,
 'eur_': 707,
 'ality_': 708,
 'concern': 709,
 'nee': 710,
 'international_': 711,
 'issue_': 712,
 'how_': 713,
 'rap': 714,
 'possible_': 715,
 'ain_': 716,
 'over_': 717,
 'compe': 718,
 'tives_': 719,
 'ress_': 720,
 'level_': 721,
 'world_': 722,
 'years_': 723,
 'proc': 724,
 'resul': 725,
 'tw': 726,
 'sign': 727,
 'shi': 728,
 'lar': 729,
 'ements_': 730,
 'same_': 731,
 'ensure_': 732,
 'decis': 733,
 'state_': 734,
 'pect_': 735,
 'ed': 736,
 'vir': 737,
 'say_': 738,
 'ative_': 739,
 'legis': 740,
 'tak': 741,
 '%_': 742,
 'ready_': 743,
 'good_': 744,
 'cep': 745,
 'want_': 746,
 'commissioner_': 747,
 'ber_': 748,
 'ying_': 749,
 'change_': 750,
 'achi': 751,
 'eng': 752,
 'dur': 753,
 'mes_': 754,
 'cannot_': 755,
 'cooperation_': 756,
 'area_': 757,
 'ffici': 758,
 'tor_': 759,
 'br': 760,
 'certa': 761,
 'ication_': 762,
 'impro': 763,
 'ish_': 764,
 'ope_': 765,
 'ish': 766,
 'consid': 767,
 'ig': 768,
 'institu': 769,
 'proposal_': 770,
 'action_': 771,
 'sions_': 772,
 'exam': 773,
 'could_': 774,
 'does_': 775,
 'fl': 776,
 'security_': 777,
 'soci': 778,
 'ste': 779,
 'year_': 780,
 'inform': 781,
 "'_": 782,
 'view_': 783,
 'two_': 784,
 'protection_': 785,
 'envir': 786,
 'environ': 787,
 'much_': 788,
 'ical_': 789,
 'see_': 790,
 'ven': 791,
 'then_': 792,
 'ack': 793,
 'part_': 794,
 'mis': 795,
 'treaty_': 796,
 'ack_': 797,
 'vote_': 798,
 'system_': 799,
 'lob': 800,
 'legal_': 801,
 'emplo': 802,
 'ability_': 803,
 'both_': 804,
 'why_': 805,
 'fer': 806,
 'ays_': 807,
 'common_': 808,
 'orities_': 809,
 'point_': 810,
 'particular_': 811,
 'spe': 812,
 'ful_': 813,
 'servic': 814,
 'ply_': 815,
 'consum': 816,
 'auth': 817,
 'disc': 818,
 'had_': 819,
 'already_': 820,
 'sed_': 821,
 'ited_': 822,
 'tribu': 823,
 'heal': 824,
 'pa': 825,
 'mad': 826,
 'still_': 827,
 'gener': 828,
 'num': 829,
 'pen': 830,
 'committee_': 831,
 'repres': 832,
 'within_': 833,
 'ist': 834,
 'int': 835,
 'om_': 836,
 'differ': 837,
 'through_': 838,
 'ority_': 839,
 'ast': 840,
 '2_': 841,
 'tural_': 842,
 'inci': 843,
 'implem': 844,
 'know_': 845,
 'wom': 846,
 'question_': 847,
 'clu': 848,
 'directive_': 849,
 'gram': 850,
 '5_': 851,
 'place_': 852,
 'glob': 853,
 'your_': 854,
 'discus': 855,
 'necess': 856,
 'program': 857,
 'clo': 858,
 'ject_': 859,
 'ite_': 860,
 'pare': 861,
 'under_': 862,
 'used_': 863,
 'ous': 864,
 'dic': 865,
 'col': 866,
 '1_': 867,
 'said_': 868,
 'course_': 869,
 'elec': 870,
 'too_': 871,
 'women_': 872,
 'id': 873,
 'bon_': 874,
 'madam_': 875,
 'ound_': 876,
 'um_': 877,
 'dra': 878,
 'trade_': 879,
 'thank_': 880,
 'gro': 881,
 'ship_': 882,
 'fur': 883,
 'loc': 884,
 'fav': 885,
 'group_': 886,
 'form_': 887,
 'employ': 888,
 'opport': 889,
 'ear': 890,
 '(_': 891,
 'necessary_': 892,
 'without_': 893,
 'indu': 894,
 'case_': 895,
 'goti': 896,
 'proce': 897,
 'information_': 898,
 'negoti': 899,
 'nal_': 900,
 'peri': 901,
 'hope_': 902,
 'members_': 903,
 'may_': 904,
 'strategy_': 905,
 'resolution_': 906,
 'cap': 907,
 'ric': 908,
 'taken_': 909,
 'ei': 910,
 'competi': 911,
 'maj': 912,
 'initi': 913,
 'rul': 914,
 'position_': 915,
 'amend': 916,
 'process_': 917,
 'acy_': 918,
 'law_': 919,
 'car': 920,
 'medi': 921,
 'last_': 922,
 'princi': 923,
 'sector_': 924,
 'lion_': 925,
 'ten_': 926,
 'loo': 927,
 'val': 928,
 'ific': 929,
 'ven_': 930,
 'led_': 931,
 'put_': 932,
 'rapport': 933,
 'objec': 934,
 'particularly_': 935,
 'inde': 936,
 'requi': 937,
 '7_': 938,
 'safe': 939,
 'sive_': 940,
 'bal': 941,
 '201': 942,
 'role_': 943,
 'long_': 944,
 'budget_': 945,
 'help_': 946,
 'secon': 947,
 'voted_': 948,
 'some': 949,
 'arm': 950,
 'clim': 951,
 'jo': 952,
 'minis': 953,
 'tn': 954,
 'climate_': 955,
 'work': 956,
 'ources_': 957,
 'issues_': 958,
 'ince_': 959,
 'ator': 960,
 'needs_': 961,
 'ently_': 962,
 'av': 963,
 'respect_': 964,
 'example_': 965,
 'ong': 966,
 'bi': 967,
 'problem_': 968,
 'problems_': 969,
 'org': 970,
 '9_': 971,
 'self_': 972,
 'ban': 973,
 'main': 974,
 'grow': 975,
 'sen': 976,
 'pow': 977,
 'ricul': 978,
 'ling_': 979,
 'areas_': 980,
 'government_': 981,
 'invol': 982,
 'tech': 983,
 'favour_': 984,
 'ame': 985,
 '8_': 986,
 'number_': 987,
 'means_': 988,
 'tes_': 989,
 'legisl': 990,
 'agricul': 991,
 'sibility_': 992,
 'rules_': 993,
 'ates_': 994,
 'rs_': 995,
 'fund': 996,
 'il_': 997,
 'sim': 998,
 'estab': 999,
 ...}

In [48]:
class BPEEncoder_2():
    def __init__(self, bpe_vocab, thres_tup=55, is_tgt=False):
        self.vocab_encoder = {"".join(k): v for k, v in bpe_vocab.items()}
        self.vocab_tuple = list(bpe_vocab.keys())[thres_tup:]
        self.char_factor = lambda word: [x for x in word] + ['_']

    def encode_snt(self, tokenized_snt):
        return [y for x in tokenized_snt for y in self.encode_word(x)]

    def encode_word(self, word):
        word_factor = self.char_factor(word)
        word_id = self.vocab_encoder.get("".join(word_factor), None)
        if word_id is None:
            word_pairs = list(zip(word_factor, word_factor[1:]))
            for pair in self.vocab_tuple:
                if pair in word_pairs:
                    p_1, p_2 = map(re.escape, pair)
                    word_factor = re.sub(rf"(?<=\s){p_1}\s{p_2}(?=\s)", f"{pair[0]}{pair[1]}", f" {' '.join(word_factor)} ").split()
                    word_pairs = list(zip(word_factor, word_factor[1:]))
            yield from [self.vocab_encoder[x] for x in word_factor]
        else:
            yield from [word_id]

In [49]:
encoder_eng2 = BPEEncoder_2(tokenizer_eng.vocab)

In [51]:
encoder_eng2.encode_snt(['corrections', 'to', 'votes', 'and', 'voting', 'intentions', ':', 'see', 'minutes'])

[6556, 80, 3842, 81, 1976, 4494, 434, 790, 1791]

In [34]:
df_europarl.head()

,eng_text,pol_text,eng_split,pol_split
0,Action taken on Parliament's resolutions: see ...,Działania podjęte w wyniku rezolucji Parlament...,"[action, taken, on, parliament, 's, resolution...","[działania, podjęte, w, wyniku, rezolucji, par..."
1,Documents received: see Minutes,Składanie dokumentów: patrz protokół,"[documents, received, :, see, minutes]","[składanie, dokumentów, :, patrz, protokół]"
2,Texts of agreements forwarded by the Council: ...,Teksty porozumień przekazane przez Radę: patrz...,"[texts, of, agreements, forwarded, by, the, co...","[teksty, porozumień, przekazane, przez, radę, ..."
3,Membership of Parliament: see Minutes,Skład Parlamentu: patrz protokół,"[membership, of, parliament, :, see, minutes]","[skład, parlamentu, :, patrz, protokół]"
4,Membership of committees and delegations: see ...,Skład komisji i delegacji: patrz protokół,"[membership, of, committees, and, delegations,...","[skład, komisji, i, delegacji, :, patrz, proto..."

In [42]:
from tqdm.auto import tqdm
tqdm.pandas()

In [47]:
df_2 = df_europarl[['pol_text', 'pol_split']].copy()
df_2['pol_ids'] = df_2['pol_text'].progress_apply(encoder_pol.encode_snt)

  0%|          | 0/576824 [00:00<?, ?it/s]

In [48]:
with open("../data/dataframe_pol_europarl.pkl", 'wb') as f:
    pickle.dump(df_2, f)

In [3]:
with open("../data/tokenizer_eng_2.pkl", 'rb') as f:
    tokenizer_eng = pickle.load(f)

with open("../data/tokenizer_pol_2.pkl", 'rb') as f:
    tokenizer_pol = pickle.load(f)

with open("../data/dataframe_europarl.pkl", 'rb') as f:
    df_europarl = pickle.load(f)

In [49]:
with open("../data/tokenizer_eng_2.pkl", 'wb') as f:
    pickle.dump(tokenizer_eng, f)

with open("../data/tokenizer_pol_2.pkl", 'wb') as f:
    pickle.dump(tokenizer_pol, f)

In [50]:
with open("../data/dataframe_europarl.pkl", 'wb') as f:
    pickle.dump(df_europarl, f)