## 06. scratchpad

In [26]:
import pickle
import pandas as pd
from BPE_tokenizer import BPETokenizer, BPEEncoder
import Data
import re
from collections import Counter

In [2]:
with open("../data/dataframe_eng.pkl", 'rb') as f:
    data_eng = pickle.load(f)

with open("../data/dataframe_pol.pkl", 'rb') as f:
    data_pol = pickle.load(f)

In [5]:
with open("../data/bpe_tokenizer_eng.pkl", 'rb') as f:
    tokenizer_eng = pickle.load(f)
    
with open("../data/bpe_tokenizer_pol.pkl", 'rb') as f:
    tokenizer_pol = pickle.load(f)

In [56]:
data_pol['pol_ids'].str.len().nlargest(1000)

219180    46
6323      45
51920     45
3559      44
52078     44
          ..
5523      29
5567      29
5794      29
6629      29
6648      29
Name: pol_ids, Length: 1000, dtype: int64

In [33]:
df_final = pd.concat([data_eng, data_pol], axis=1)[['eng_text', 'eng_ids', 'pol_text', 'pol_ids']]

In [59]:
mask1 = df_final['eng_ids'].str.len() > 29
mask2 = df_final['pol_ids'].str.len() > 29
print(mask1.sum(), mask2.sum(), (mask1 | mask2).sum())
df_final = df_final[~(mask1 | mask2)].reset_index(drop=True)

1854 971 2338

In [65]:
data_test = df_final.sample(50000).reset_index(drop=True)
train_df, val_df = Data.shuffle_split(data_test, 0.85)

train_data = Data.EngPolDataset(train_df, 'eng_ids', 'pol_ids')
val_data = Data.EngPolDataset(val_df, 'eng_ids', 'pol_ids')

### New data

In [71]:
with open('../data/europarl/europarl-v7.pl-en.en', 'r', encoding='utf-8') as f:
    eng_lines = f.readlines()

with open('../data/europarl/europarl-v7.pl-en.pl', 'r', encoding='utf-8') as f:
    pol_lines = f.readlines()

pairs = [(e.strip(), p.strip()) for e, p in zip(eng_lines, pol_lines)
         if e.strip() and p.strip() 
         and not e.strip().startswith('<') 
         and not p.strip().startswith('<')]

df_europarl = pd.DataFrame(pairs, columns=['eng_text', 'pol_text'])
print(len(df_europarl))
df_europarl.head()

629380

,eng_text,pol_text
0,Action taken on Parliament's resolutions: see ...,Działania podjęte w wyniku rezolucji Parlament...
1,Documents received: see Minutes,Składanie dokumentów: patrz protokół
2,Written statements (Rule 116): see Minutes,Oświadczenia pisemne (art. 116 Regulaminu): pa...
3,Texts of agreements forwarded by the Council: ...,Teksty porozumień przekazane przez Radę: patrz...
4,Membership of Parliament: see Minutes,Skład Parlamentu: patrz protokół

In [84]:
bool(re.search(r"[(]..[)]", "(IT) Mr President, the subject is an oral amen..."))

True

In [95]:
df_europarl[mask]['eng_text'].apply(lambda x: re.sub(r"^[(]..[)]", "", x))

60         It is proposed that the sum of 50 000 in para...
1656       Mr President, I would like to make an unequiv...
1713                              Mr. Chairman, colleagues,
1733       Mr President, after tens of years of politica...
1739       Mr President, a few months ago the European P...
                                ...
625096     Madam President, I was happy to back this rep...
625104     the better it will be for all the farmers of ...
625106     Madam President, the common agricultural poli...
625114     Madam President, ladies and gentlemen, I have...
628808     Mr President, ladies and gentlemen, the Europ...
Name: eng_text, Length: 18356, dtype: object

In [96]:
requir = lambda x: re.sub(r"^[(]..[)]", "", x)
df_europarl['eng_text'] = df_europarl['eng_text'].apply(requir)
df_europarl['pol_text'] = df_europarl['pol_text'].apply(requir)

In [108]:
bool(re.search(r".+[(].+[)].+", "Written statements (Rule 116): see."))

True

In [113]:
mask_eng = df_europarl['eng_text'].apply(lambda x: bool(re.search(r".+[(].+[)].+", x)))
mask_pol = df_europarl['pol_text'].apply(lambda x: bool(re.search(r".+[(].+[)].+", x)))

In [117]:
mask_eng.sum(), mask_pol.sum(), (mask_eng | mask_pol).sum()

(22461, 21196, 25231)

In [123]:
df_europarl = df_europarl[~(mask_eng | mask_pol)].reset_index(drop=True)
df_europarl

,eng_text,pol_text
0,Action taken on Parliament's resolutions: see ...,Działania podjęte w wyniku rezolucji Parlament...
1,Documents received: see Minutes,Składanie dokumentów: patrz protokół
2,Texts of agreements forwarded by the Council: ...,Teksty porozumień przekazane przez Radę: patrz...
3,Membership of Parliament: see Minutes,Skład Parlamentu: patrz protokół
4,Membership of committees and delegations: see ...,Skład komisji i delegacji: patrz protokół
...,...,...
604144,Composition of committees and delegations : se...,Skład komisji i delegacji: Patrz protokól
604145,Agenda of the next sitting : see Minutes,Porządek obrad następnego posiedzenia: Patrz p...
604146,Closure of the sitting,Zamknięcie posiedzenia
604147,(The sitting closed at 22.25),(The sitting closed at 22.25)
604148,. -,. -

In [125]:
uniq_eng = set("".join(df_europarl["eng_text"].astype(str)))
uniq_pol = set("".join(df_europarl["pol_text"].astype(str)))
print(f"Eng uniq: {len(uniq_eng)} | Pol uniq: {len(uniq_pol)}")

Eng uniq: 262 | Pol uniq: 267

In [163]:
tgt_eng = ['z', 'y', 'x', 'w', 'v', 'u', 't', 's', 'r', 'q', 'p', 'o', 'n', 'm', 'l', 'k', 'j', 'i', 'h', 'g', 'f', 'e', 'd', 'c', 'b', 'a', ']', '[', 'Z', 'Y', 'X', 'W', 'V', 'U', 'T', 'S', 'R', 'Q', 'P', 'O', 'N', 'M', 'L', 'K', 'J', 'I', 'H', 'G', 'F', 'E', 'D', 'C', 'B', 'A', '?', ':', '9', '8', '7', '6', '5', '4', '3', '2', '1', '0', '/', '.', '-', ',', ')', '(', "'", '%', '"', '!', ' ', ';']
tgt_pol = ['ż', 'Ż', 'ź', 'Ź', 'ś', 'Ś', 'ń', 'Ń', 'ł', 'Ł', 'ę', 'Ę', 'ć', 'Ć', 'ą', 'Ą', 'ó', 'Ó', 'z', 'y', 'x', 'w', 'v', 'u', 't', 's', 'r', 'q', 'p', 'o', 'n', 'm', 'l', 'k', 'j', 'i', 'h', 'g', 'f', 'e', 'd', 'c', 'b', 'a', ']', '[', 'Z', 'Y', 'X', 'W', 'V', 'U', 'T', 'S', 'R', 'Q', 'P', 'O', 'N', 'M', 'L', 'K', 'J', 'I', 'H', 'G', 'F', 'E', 'D', 'C', 'B', 'A', '?', ':', '9', '8', '7', '6', '5', '4', '3', '2', '1', '0', '/', '.', '-', ',', ')', '(', "'", '%', '"', '!', ' ', ';']

In [164]:
eng_delchars = [x for x in sorted(list(uniq_eng), reverse=True) if x not in tgt_eng]
pol_delchars = [x for x in sorted(list(uniq_pol), reverse=True) if x not in tgt_pol]
regex_eng = "[" + "".join(map(re.escape, eng_delchars)) + "]"
regex_pol = "[" + "".join(map(re.escape, pol_delchars)) + "]"

In [168]:
eng_delchars

['$']

In [169]:
mask_eng = df_europarl["eng_text"].str.contains(regex_eng, na=False)
#mask_pol = df_europarl["pol_text"].str.contains(regex_pol, na=False)
mask_eng.sum()#, mask_pol.sum(), (mask_eng | mask_pol).sum()

3

In [172]:
#df_europarl = df_europarl[~(mask_eng | mask_pol)].reset_index(drop=True)
df_europarl = df_europarl[~mask_eng].reset_index(drop=True)

In [173]:
uniq_eng = set("".join(df_europarl["eng_text"].astype(str)))
uniq_pol = set("".join(df_europarl["pol_text"].astype(str)))
print(f"Eng uniq: {len(uniq_eng)} | Pol uniq: {len(uniq_pol)}")

Eng uniq: 78 | Pol uniq: 94

In [176]:
print(sorted(list(uniq_eng), reverse=True))

['z', 'y', 'x', 'w', 'v', 'u', 't', 's', 'r', 'q', 'p', 'o', 'n', 'm', 'l', 'k', 'j', 'i', 'h', 'g', 'f', 'e', 'd', 'c', 'b', 'a', ']', '[', 'Z', 'Y', 'X', 'W', 'V', 'U', 'T', 'S', 'R', 'Q', 'P', 'O', 'N', 'M', 'L', 'K', 'J', 'I', 'H', 'G', 'F', 'E', 'D', 'C', 'B', 'A', '?', ';', ':', '9', '8', '7', '6', '5', '4', '3', '2', '1', '0', '/', '.', '-', ',', ')', '(', "'", '%', '"', '!', ' ']

In [181]:
df_europarl

,eng_text,pol_text
0,Action taken on Parliament's resolutions: see ...,Działania podjęte w wyniku rezolucji Parlament...
1,Documents received: see Minutes,Składanie dokumentów: patrz protokół
2,Texts of agreements forwarded by the Council: ...,Teksty porozumień przekazane przez Radę: patrz...
3,Membership of Parliament: see Minutes,Skład Parlamentu: patrz protokół
4,Membership of committees and delegations: see ...,Skład komisji i delegacji: patrz protokół
...,...,...
579887,Composition of committees and delegations : se...,Skład komisji i delegacji: Patrz protokól
579888,Agenda of the next sitting : see Minutes,Porządek obrad następnego posiedzenia: Patrz p...
579889,Closure of the sitting,Zamknięcie posiedzenia
579890,(The sitting closed at 22.25),(The sitting closed at 22.25)
579891,. -,. -

In [198]:
mask_1 = (df_europarl["eng_text"].str[-1] == '.') & (df_europarl["pol_text"].str[-1] != '.')
mask_2 = (df_europarl["eng_text"].str[-1] != '.') & (df_europarl["pol_text"].str[-1] == '.')

In [199]:
mask_1.sum(), mask_2.sum(), (mask_1 | mask_2).sum()

(1960, 1108, 3068)

In [201]:
(~(mask_1 | mask_2)).sum()

576824

In [202]:
df_europarl = df_europarl[~(mask_1 | mask_2)].reset_index(drop=True)

In [204]:
def tokenize_eng(snt):
    snt = snt.lower()
    snt = re.sub("(?<! )'(?! )", r" '", snt)
    snt = re.sub(r"""([\]?:)\[(/\.\-,%\$"!])""", r" \1 ", snt)
    snt = re.sub(r"\s+", " ", snt).strip()
    return re.split(r'\s+', snt.strip())

def tokenize_pol(snt):
    snt = snt.lower()
    snt = re.sub(r"""([\]?:)\[(/\.\-,%\$"!])""", r" \1 ", snt)
    snt = re.sub(r"\s+", " ", snt).strip()
    return re.split(r'\s+', snt.strip())

In [205]:
df_europarl['eng_split'] = df_europarl["eng_text"].apply(tokenize_eng)
df_europarl['pol_split'] = df_europarl["pol_text"].apply(tokenize_pol)

In [219]:
df_europarl['eng_split']

0         [action, taken, on, parliament, 's, resolution...
1                    [documents, received, :, see, minutes]
2         [texts, of, agreements, forwarded, by, the, co...
3             [membership, of, parliament, :, see, minutes]
4         [membership, of, committees, and, delegations,...
                                ...
576819    [composition, of, committees, and, delegations...
576820    [agenda, of, the, next, sitting, :, see, minutes]
576821                          [closure, of, the, sitting]
576822          [(, the, sitting, closed, at, 22, ., 25, )]
576823                                               [., -]
Name: eng_split, Length: 576824, dtype: object

In [230]:
uniq_freq_eng = Counter(df_europarl['eng_split'].explode())
uniq_freq_pol = Counter(df_europarl['pol_split'].explode())

In [266]:
char_factor = lambda word: [x for x in word] + ['_']
vocab_chars_eng = [[char_factor(k), v] for k, v in uniq_freq_eng.most_common()]
vocab_chars_pol = [[char_factor(k), v] for k, v in uniq_freq_pol.most_common() if v > 1]
print(len(vocab_chars_eng), vocab_chars_eng[:5], '\n')
print(len(vocab_chars_pol), vocab_chars_pol[:5])

50655 [[['t', 'h', 'e', '_'], 1019855], [[',', '_'], 712258], [['.', '_'], 562408], [['o', 'f', '_'], 488571], [['t', 'o', '_'], 458481]]

100547 [[[',', '_'], 876176], [['.', '_'], 578767], [['w', '_'], 432544], [['i', '_'], 304762], [['n', 'a', '_'], 192303]]

In [267]:
pair_vocab_eng = [[list(zip(tab, tab[1:])), v] for tab, v in vocab_chars_eng]
pair_vocab_pol = [[list(zip(tab, tab[1:])), v] for tab, v in vocab_chars_pol]

In [254]:
import BPE_tokenizer
from tqdm.notebook import tqdm
import importlib
importlib.reload(BPE_tokenizer)

In [272]:
vocab_chars_eng, pair_vocab_eng

([[['t', 'h', 'e', '_'], 1019855],
  [[',', '_'], 712258],
  [['.', '_'], 562408],
  [['o', 'f', '_'], 488571],
  [['t', 'o', '_'], 458481],
  [['a', 'n', 'd', '_'], 409816],
  [['i', 'n', '_'], 328584],
  [['t', 'h', 'a', 't', '_'], 244130],
  [['i', 's', '_'], 232040],
  [['a', '_'], 230470],
  [['f', 'o', 'r', '_'], 165561],
  [['w', 'e', '_'], 162306],
  [['t', 'h', 'i', 's', '_'], 153705],
  [['i', '_'], 149372],
  [['o', 'n', '_'], 131780],
  [['i', 't', '_'], 125037],
  [['b', 'e', '_'], 115825],
  [['-', '_'], 113169],
  [['a', 'r', 'e', '_'], 106249],
  [['h', 'a', 'v', 'e', '_'], 96224],
  [['a', 's', '_'], 95598],
  [['e', 'u', 'r', 'o', 'p', 'e', 'a', 'n', '_'], 91656],
  [['n', 'o', 't', '_'], 90226],
  [['w', 'i', 't', 'h', '_'], 88256],
  [['w', 'i', 'l', 'l', '_'], 75079],
  [['w', 'h', 'i', 'c', 'h', '_'], 71357],
  [['b', 'y', '_'], 66418],
  [['h', 'a', 's', '_'], 58463],
  [['a', 'l', 's', 'o', '_'], 50414],
  [['a', 'n', '_'], 48353],
  [['a', 't', '_'], 48041],
  [['a', 'l', 'l', '_'], 45498],
  [['w', 'o', 'u', 'l', 'd', '_'], 44130],
  [['o', 'u', 'r', '_'], 43787],
  [["'", 's', '_'], 42730],
  [['f', 'r', 'o', 'm', '_'], 42706],
  [['c', 'o', 'm', 'm', 'i', 's', 's', 'i', 'o', 'n', '_'], 41381],
  [['s', 'h', 'o', 'u', 'l', 'd', '_'], 41089],
  [['m', 'u', 's', 't', '_'], 40617],
  [['b', 'u', 't', '_'], 40438],
  [['e', 'u', '_'], 39368],
  [['m', 'e', 'm', 'b', 'e', 'r', '_'], 37803],
  [['u', 'n', 'i', 'o', 'n', '_'], 36951],
  [['t', 'h', 'e', 'r', 'e', '_'], 35440],
  [['p', 'r', 'e', 's', 'i', 'd', 'e', 'n', 't', '_'], 35353],
  [['s', 't', 'a', 't', 'e', 's', '_'], 35344],
  [['m', 'r', '_'], 34617],
  [['y', 'o', 'u', '_'], 34588],
  [['b', 'e', 'e', 'n', '_'], 33516],
  [['m', 'o', 'r', 'e', '_'], 33122],
  [['c', 'a', 'n', '_'], 32284],
  [['t', 'h', 'e', 'i', 'r', '_'], 32183],
  [['p', 'a', 'r', 'l', 'i', 'a', 'm', 'e', 'n', 't', '_'], 31787],
  [['t', 'h', 'e', 's', 'e', '_'], 31392],
  [['i', 't', 's', '_'], 30009],
  [['t', 'h', 'e', 'y', '_'], 29812],
  [['e', 'u', 'r', 'o', 'p', 'e', '_'], 29038],
  [['o', 'r', '_'], 28642],
  [['w', 'a', 's', '_'], 28355],
  [['v', 'e', 'r', 'y', '_'], 28245],
  [['d', 'o', '_'], 27740],
  [['l', 'i', 'k', 'e', '_'], 27199],
  [['n', 'e', 'e', 'd', '_'], 27044],
  [['r', 'e', 'p', 'o', 'r', 't', '_'], 26999],
  [['o', 'n', 'e', '_'], 25926],
  [['i', 'm', 'p', 'o', 'r', 't', 'a', 'n', 't', '_'], 24872],
  [['w', 'h', 'a', 't', '_'], 24697],
  [['s', 'o', '_'], 24462],
  [['c', 'o', 'u', 'n', 't', 'r', 'i', 'e', 's', '_'], 24392],
  [['u', 's', '_'], 23645],
  [['i', 'f', '_'], 23177],
  [['p', 'e', 'o', 'p', 'l', 'e', '_'], 23120],
  [['a', 'b', 'o', 'u', 't', '_'], 22465],
  [['c', 'o', 'u', 'n', 'c', 'i', 'l', '_'], 22108],
  [['n', 'e', 'w', '_'], 21903],
  [[':', '_'], 21863],
  [['w', 'h', 'o', '_'], 21715],
  [['o', 't', 'h', 'e', 'r', '_'], 21688],
  [['m', 'y', '_'], 21627],
  [['o', 'n', 'l', 'y', '_'], 21153],
  [['r', 'i', 'g', 'h', 't', 's', '_'], 20928],
  [['p', 'o', 'l', 'i', 'c', 'y', '_'], 20664],
  [['t', 'i', 'm', 'e', '_'], 20471],
  [['b', 'e', 'c', 'a', 'u', 's', 'e', '_'], 20428],
  [['s', 'u', 'p', 'p', 'o', 'r', 't', '_'], 19894],
  [['h', 'o', 'w', 'e', 'v', 'e', 'r', '_'], 19775],
  [['e', 'c', 'o', 'n', 'o', 'm', 'i', 'c', '_'], 19403],
  [['t', 'h', 'e', 'r', 'e', 'f', 'o', 'r', 'e', '_'], 19123],
  [['s', 'u', 'c', 'h', '_'], 18151],
  [['n', 'o', 'w', '_'], 17984],
  [['a', 'm', '_'], 17552],
  [['u', 'p', '_'], 17384],
  [['n', 'o', '_'], 17138],
  [['b', 'e', 't', 'w', 'e', 'e', 'n', '_'], 17002],
  [['w', 'h', 'e', 'n', '_'], 16637],
  [['o', 'u', 't', '_'], 16394],
  [['i', 'n', 't', 'o', '_'], 16336],
  [['?', '_'], 16103],
  [['t', 'h', 'o', 's', 'e', '_'], 16080],
  [['m', 'a', 'k', 'e', '_'], 16059],
  [['w', 'o', 'r', 'k', '_'], 15976],
  [['t', 'a', 'k', 'e', '_'], 15607],
  [['m', 'a', 'r', 'k', 'e', 't', '_'], 15404],
  [['s', 'o', 'm', 'e', '_'], 15165],
  [['e', 'n', 'e', 'r', 'g', 'y', '_'], 15145],
  [['s', 'o', 'c', 'i', 'a', 'l', '_'], 14672],
  [['f', 'i', 'n', 'a', 'n', 'c', 'i', 'a', 'l', '_'], 14654],
  [['m', 'a', 'n', 'y', '_'], 14597],
  [['b', 'e', 'l', 'i', 'e', 'v', 'e', '_'], 14215],
  [['t', 'h', 'e', 'm', '_'], 14195],
  [['d', 'e', 'v', 'e', 'l', 'o', 'p', 'm', 'e', 'n', 't', '_'], 14143],
  [['p', 'o', 'l', 'i', 't', 'i', 'c', 'a', 'l', '_'], 13819],
  [['c', 'i', 't', 'i', 'z', 'e', 'n', 's', '_'], 13769],
  [['a', 'g', 'a', 'i', 'n', 's', 't', '_'], 13759],
  [['b', 'e', 'i', 'n', 'g', '_'], 13673],
  [['h', 'u', 'm', 'a', 'n', '_'], 13224],
  [['c', 'r', 'i', 's', 'i', 's', '_'], 13149],
  [['t', 'h', 'i', 'n', 'k', '_'], 13033],
  [['w', 'e', 'l', 'l', '_'], 13031],
  [['a', 'n', 'y', '_'], 12966],
  [['w', 'e', 'r', 'e', '_'], 12816],
  [['t', 'h', 'a', 'n', '_'], 12772],
  [['a', 'g', 'r', 'e', 'e', 'm', 'e', 'n', 't', '_'], 12743],
  [['m', 'a', 'd', 'e', '_'], 12722],
  [['w', 'a', 'y', '_'], 12710],
  [['c', 'o', 'u', 'n', 't', 'r', 'y', '_'], 12448],
  [['t', 'o', 'd', 'a', 'y', '_'], 12385],
  [['f', 'i', 'r', 's', 't', '_'], 12322],
  [['s', 'i', 't', 'u', 'a', 't', 'i', 'o', 'n', '_'], 12092],
  [['o', 'r', 'd', 'e', 'r', '_'], 11939],
  [['m', 'e', 'a', 's', 'u', 'r', 'e', 's', '_'], 11939],
  [['f', 'u', 't', 'u', 'r', 'e', '_'], 11467],
  [['d', 'e', 'b', 'a', 't', 'e', '_'], 11462],
  [['f', 'a', 'c', 't', '_'], 11430],
  [['j', 'u', 's', 't', '_'], 11257],
  [['i', 'n', 't', 'e', 'r', 'n', 'a', 't', 'i', 'o', 'n', 'a', 'l', '_'],
   11220],
  [['i', 's', 's', 'u', 'e', '_'], 11206],
  [['e', 'v', 'e', 'n', '_'], 11192],
  [['r', 'i', 'g', 'h', 't', '_'], 11096],
  [['h', 'o', 'w', '_'], 11039],
  [['y', 'e', 'a', 'r', 's', '_'], 11010],
  [['l', 'e', 'v', 'e', 'l', '_'], 11003],
  [['w', 'o', 'r', 'l', 'd', '_'], 11003],
  [['m', 'o', 's', 't', '_'], 10938],
  [['h', 'e', 'r', 'e', '_'], 10910],
  [['s', 'a', 'm', 'e', '_'], 10831],
  [['e', 'n', 's', 'u', 'r', 'e', '_'], 10772],
  [['w', 'h', 'e', 'r', 'e', '_'], 10707],
  [['s', 'a', 'y', '_'], 10636],
  [['s', 't', 'a', 't', 'e', '_'], 10552],
  [['n', 'a', 't', 'i', 'o', 'n', 'a', 'l', '_'], 10525],
  [['%', '_'], 10523],
  [['g', 'o', 'o', 'd', '_'], 10479],
  [['w', 'a', 'n', 't', '_'], 10470],
  [['c', 'o', 'm', 'm', 'i', 's', 's', 'i', 'o', 'n', 'e', 'r', '_'], 10418],
  [['p', 'u', 'b', 'l', 'i', 'c', '_'], 10329],
  [['p', 'o', 's', 's', 'i', 'b', 'l', 'e', '_'], 10283],
  [['c', 'a', 'n', 'n', 'o', 't', '_'], 10271],
  [['c', 'o', 'o', 'p', 'e', 'r', 'a', 't', 'i', 'o', 'n', '_'], 10264],
  [['a', 'r', 'e', 'a', '_'], 10257],
  [['u', 's', 'e', '_'], 10084],
  [['p', 'r', 'o', 'p', 'o', 's', 'a', 'l', '_'], 10045],
  [['c', 'o', 'u', 'l', 'd', '_'], 10007],
  [['d', 'o', 'e', 's', '_'], 9994],
  [['y', 'e', 'a', 'r', '_'], 9925],
  [['t', 'w', 'o', '_'], 9890],
  [['p', 'r', 'o', 't', 'e', 'c', 't', 'i', 'o', 'n', '_'], 9887],
  [['m', 'u', 'c', 'h', '_'], 9840],
  [['s', 'e', 'e', '_'], 9796],
  [['t', 'r', 'e', 'a', 't', 'y', '_'], 9713],
  [['s', 'e', 'c', 'u', 'r', 'i', 't', 'y', '_'], 9709],
  [['c', 'l', 'e', 'a', 'r', '_'], 9695],
  [['v', 'o', 't', 'e', '_'], 9636],
  [['b', 'o', 't', 'h', '_'], 9574],
  [['w', 'h', 'y', '_'], 9552],
  [['c', 'o', 'm', 'm', 'o', 'n', '_'], 9514],
  [['s', 'y', 's', 't', 'e', 'm', '_'], 9470],
  [['p', 'a', 'r', 't', 'i', 'c', 'u', 'l', 'a', 'r', '_'], 9457],
  [['a', 'l', 'r', 'e', 'a', 'd', 'y', '_'], 9269],
  [['w', 'i', 't', 'h', 'i', 'n', '_'], 9100],
  [['s', 't', 'i', 'l', 'l', '_'], 9077],
  [['p', 'o', 'i', 'n', 't', '_'], 9038],
  [['o', 'v', 'e', 'r', '_'], 9019],
  [['p', 'a', 'r', 't', '_'], 9008],
  [['c', 'o', 'm', 'm', 'i', 't', 't', 'e', 'e', '_'], 8999],
  [['k', 'n', 'o', 'w', '_'], 8941],
  [['h', 'a', 'd', '_'], 8939],
  [['t', 'h', 'r', 'o', 'u', 'g', 'h', '_'], 8928],
  [['q', 'u', 'e', 's', 't', 'i', 'o', 'n', '_'], 8892],
  [['d', 'i', 'r', 'e', 'c', 't', 'i', 'v', 'e', '_'], 8864],
  [['y', 'o', 'u', 'r', '_'], 8771],
  [['c', 'h', 'a', 'n', 'g', 'e', '_'], 8711],
  [['a', 'c', 't', 'i', 'o', 'n', '_'], 8709],
  [['m', 'e', '_'], 8617],
  [['u', 'n', 'd', 'e', 'r', '_'], 8587],
  [['s', 'a', 'i', 'd', '_'], 8523],
  [['t', 'o', 'o', '_'], 8495],
  [['w', 'o', 'm', 'e', 'n', '_'], 8469],
  [['m', 'a', 'd', 'a', 'm', '_'], 8456],
  [['t', 'r', 'a', 'd', 'e', '_'], 8403],
  [['t', 'h', 'a', 'n', 'k', '_'], 8393],
  [['c', 'o', 'u', 'r', 's', 'e', '_'], 8329],
  [['a', 'b', 'l', 'e', '_'], 8294],
  [['(', '_'], 8233],
  [['w', 'i', 't', 'h', 'o', 'u', 't', '_'], 8173],
  [['c', 'a', 's', 'e', '_'], 8141],
  [['g', 'r', 'o', 'u', 'p', '_'], 8095],
  [['i', 'n', 'f', 'o', 'r', 'm', 'a', 't', 'i', 'o', 'n', '_'], 8091],
  [['s', 't', 'r', 'a', 't', 'e', 'g', 'y', '_'], 8081],
  [['m', 'e', 'm', 'b', 'e', 'r', 's', '_'], 8071],
  [['r', 'e', 's', 'o', 'l', 'u', 't', 'i', 'o', 'n', '_'], 8070],
  [['h', 'o', 'p', 'e', '_'], 8067],
  [['m', 'a', 'y', '_'], 8059],
  [['o', 'w', 'n', '_'], 7975],
  [['p', 'r', 'o', 'c', 'e', 's', 's', '_'], 7963],
  [['p', 'l', 'a', 'c', 'e', '_'], 7927],
  [['l', 'a', 's', 't', '_'], 7923],
  [['s', 'e', 'c', 't', 'o', 'r', '_'], 7891],
  [['l', 'a', 'w', '_'], 7889],
  [['p', 'a', 'r', 't', 'i', 'c', 'u', 'l', 'a', 'r', 'l', 'y', '_'], 7692],
  [['n', 'e', 'c', 'e', 's', 's', 'a', 'r', 'y', '_'], 7673],
  [['r', 'o', 'l', 'e', '_'], 7595],
  [['b', 'u', 'd', 'g', 'e', 't', '_'], 7579],
  [['h', 'e', 'l', 'p', '_'], 7568],
  [['v', 'o', 't', 'e', 'd', '_'], 7553],
  [['l', 'o', 'n', 'g', '_'], 7524],
  [['c', 'l', 'i', 'm', 'a', 't', 'e', '_'], 7510],
  [['i', 's', 's', 'u', 'e', 's', '_'], 7506],
  [['n', 'e', 'e', 'd', 's', '_'], 7484],
  [['e', 'x', 'a', 'm', 'p', 'l', 'e', '_'], 7421],
  [['t', 'h', 'e', 'n', '_'], 7416],
  [['p', 'r', 'o', 'b', 'l', 'e', 'm', '_'], 7405],
  [['p', 'r', 'o', 'b', 'l', 'e', 'm', 's', '_'], 7403],
  [['r', 'e', 's', 'p', 'e', 'c', 't', '_'], 7397],
  [['p', 'u', 't', '_'], 7338],
  [['t', 'a', 'k', 'e', 'n', '_'], 7325],
  [['a', 'r', 'e', 'a', 's', '_'], 7304],
  [['g', 'o', 'v', 'e', 'r', 'n', 'm', 'e', 'n', 't', '_'], 7295],
  [['f', 'a', 'v', 'o', 'u', 'r', '_'], 7261],
  [['n', 'u', 'm', 'b', 'e', 'r', '_'], 7235],
  [['m', 'e', 'a', 'n', 's', '_'], 7229],
  [['r', 'u', 'l', 'e', 's', '_'], 7187],
  [['b', 'e', 't', 't', 'e', 'r', '_'], 7147],
  [['v', 'i', 'e', 'w', '_'], 7119],
  [['h', 'e', 'a', 'l', 't', 'h', '_'], 7101],
  [['l', 'e', 'g', 'a', 'l', '_'], 7086],
  [['l', 'i', 's', 'b', 'o', 'n', '_'], 7074],
  [['c', 'o', 'm', 'm', 'u', 'n', 'i', 't', 'y', '_'], 7053],
  [[')', '_'], 7025],
  [['s', 'i', 'n', 'c', 'e', '_'], 6991],
  [['g', 'i', 'v', 'e', 'n', '_'], 6885],
  [['e', 'n', 'd', '_'], 6848],
  [['f', 'r', 'a', 'm', 'e', 'w', 'o', 'r', 'k', '_'], 6802],
  [['a', 'f', 't', 'e', 'r', '_'], 6744],
  [['b', 'e', 'f', 'o', 'r', 'e', '_'], 6717],
  [['r', 'e', 'g', 'a', 'r', 'd', '_'], 6622],
  [['h', 'i', 'g', 'h', '_'], 6608],
  [['l', 'e', 't', '_'], 6574],
  [['c', 'u', 'r', 'r', 'e', 'n', 't', '_'], 6487],
  [['p', 'r', 'e', 's', 'i', 'd', 'e', 'n', 'c', 'y', '_'], 6465],
  [['g', 'l', 'o', 'b', 'a', 'l', '_'], 6425],
  [['i', 'n', 's', 't', 'i', 't', 'u', 't', 'i', 'o', 'n', 's', '_'], 6388],
  [['s', 'e', 'r', 'v', 'i', 'c', 'e', 's', '_'], 6376],
  [['g', 'i', 'v', 'e', '_'], 6376],
  [['l', 'e', 'g', 'i', 's', 'l', 'a', 't', 'i', 'o', 'n', '_'], 6345],
  [['h', 'i', 's', '_'], 6345],
  [['r', 'e', 'g', 'u', 'l', 'a', 't', 'i', 'o', 'n', '_'], 6328],
  [['c', 'o', 'n', 't', 'i', 'n', 'u', 'e', '_'], 6322],
  [['t', 'e', 'r', 'm', 's', '_'], 6285],
  [['a', 'g', 'a', 'i', 'n', '_'], 6281],
  [['f', 'u', 'r', 't', 'h', 'e', 'r', '_'], 6237],
  [['r', 'a', 'p', 'p', 'o', 'r', 't', 'e', 'u', 'r', '_'], 6237],
  [['h', 'e', '_'], 6220],
  [['f', 'o', 'o', 'd', '_'], 6194],
  [['i', 'n', 'c', 'l', 'u', 'd', 'i', 'n', 'g', '_'], 6190],
  [['a', 'g', 'r', 'e', 'e', '_'], 6177],
  [['w', 'h', 'e', 't', 'h', 'e', 'r', '_'], 6146],
  [['n', 'e', 'x', 't', '_'], 6123],
  [['g', 'e', 'n', 't', 'l', 'e', 'm', 'e', 'n', '_'], 6106],
  [['f', 'u', 'n', 'd', 'a', 'm', 'e', 'n', 't', 'a', 'l', '_'], 6084],
  [['s', 'e', 't', '_'], 6074],
  [['l', 'a', 'd', 'i', 'e', 's', '_'], 6066],
  [['c', 'o', 'm', 'e', '_'], 6060],
  [['g', 'r', 'e', 'a', 't', '_'], 6028],
  [['w', 'e', 'l', 'c', 'o', 'm', 'e', '_'], 6024],
  [['d', 'i', 'f', 'f', 'e', 'r', 'e', 'n', 't', '_'], 6020],
  [['b', 'a', 's', 'e', 'd', '_'], 6006],
  [['e', 'c', 'o', 'n', 'o', 'm', 'y', '_'], 6001],
  [['i', 'n', 'c', 'r', 'e', 'a', 's', 'e', '_'], 5973],
  [['d', 'e', 'c', 'i', 's', 'i', 'o', 'n', '_'], 5939],
  [['d', 'u', 'r', 'i', 'n', 'g', '_'], 5902],
  [['p', 'r', 'o', 'v', 'i', 'd', 'e', '_'], 5891],
  [['r', 'e', 's', 'u', 'l', 't', '_'], 5886],
  [['a', 'c', 'c', 'e', 's', 's', '_'], 5821],
  [['r', 'e', 's', 'o', 'u', 'r', 'c', 'e', 's', '_'], 5815],
  [['e', 'f', 'f', 'e', 'c', 't', 'i', 'v', 'e', '_'], 5803],
  [['a', 'p', 'p', 'r', 'o', 'a', 'c', 'h', '_'], 5750],
  [['m', 'a', 't', 't', 'e', 'r', '_'], 5736],
  [['w', 'h', 'i', 'l', 'e', '_'], 5716],
  [['f', 'a', 'r', '_'], 5713],
  [['p', 'r', 'o', 'g', 'r', 'e', 's', 's', '_'], 5685],
  [['u', 'n', 'i', 't', 'e', 'd', '_'], 5683],
  [['c', 'o', 'n', 'd', 'i', 't', 'i', 'o', 'n', 's', '_'], 5642],
  [['s', 'a', 'f', 'e', 't', 'y', '_'], 5642],
  [['w', 'o', 'r', 'k', 'i', 'n', 'g', '_'], 5629],
  [['p', 'r', 'o', 'd', 'u', 'c', 't', 's', '_'], 5615],
  [['e', 's', 'p', 'e', 'c', 'i', 'a', 'l', 'l', 'y', '_'], 5604],
  [['p', 'o', 'l', 'i', 'c', 'i', 'e', 's', '_'], 5588],
  [['f', 'u', 'n', 'd', 's', '_'], 5580],
  [['a', 'd', 'o', 'p', 't', 'e', 'd', '_'], 5570],
  [['a', 'u', 't', 'h', 'o', 'r', 'i', 't', 'i', 'e', 's', '_'], 5566],
  [['t', 'o', 'w', 'a', 'r', 'd', 's', '_'], 5537],
  [['c', 'e', 'r', 't', 'a', 'i', 'n', '_'], 5528],
  [['m', 'a', 'k', 'i', 'n', 'g', '_'], 5518],
  [['f', 'r', 'e', 'e', 'd', 'o', 'm', '_'], 5471],
  [['o', 'p', 'p', 'o', 'r', 't', 'u', 'n', 'i', 't', 'y', '_'], 5461],
  [['p', 'r', 'o', 'p', 'o', 's', 'a', 'l', 's', '_'], 5459],
  [['e', 'v', 'e', 'r', 'y', '_'], 5434],
  [['a', 'i', 'd', '_'], 5415],
  [['p', 'o', 's', 'i', 't', 'i', 'o', 'n', '_'], 5413],
  [['b', 'a', 's', 'i', 's', '_'], 5369],
  [['d', 'o', 'n', 'e', '_'], 5359],
  [['t', 'o', 'g', 'e', 't', 'h', 'e', 'r', '_'], 5350],
  [['g', 'r', 'o', 'w', 't', 'h', '_'], 5340],
  [['g', 'o', 'i', 'n', 'g', '_'], 5335],
  [['t', 'r', 'a', 'n', 's', 'p', 'o', 'r', 't', '_'], 5334],
  [['i', 'm', 'p', 'o', 'r', 't', 'a', 'n', 'c', 'e', '_'], 5328],
  [['a', 'n', 'o', 't', 'h', 'e', 'r', '_'], 5313],
  [['t', 'e', 'r', 'm', '_'], 5291],
  [['f', 'r', 'e', 'e', '_'], 5284],
  [['i', 'n', 'd', 'u', 's', 't', 'r', 'y', '_'], 5235],
  [['g', 'r', 'e', 'a', 't', 'e', 'r', '_'], 5230],
  [['f', 'o', 'r', 'w', 'a', 'r', 'd', '_'], 5217],
  [['c', 'h', 'i', 'l', 'd', 'r', 'e', 'n', '_'], 5209],
  [['r', 'e', 'g', 'i', 'o', 'n', '_'], 5202],
  [['m', 'r', 's', '_'], 5200],
  [['n', 'e', 'g', 'o', 't', 'i', 'a', 't', 'i', 'o', 'n', 's', '_'], 5116],
  [['r', 'e', 's', 'e', 'a', 'r', 'c', 'h', '_'], 5111],
  [['s', 'm', 'a', 'l', 'l', '_'], 5109],
  [['h', 'o', 'u', 's', 'e', '_'], 5094],
  [['p', 'r', 'o', 'g', 'r', 'a', 'm', 'm', 'e', '_'], 5067],
  [['u', 's', 'e', 'd', '_'], 5059],
  [['t', 'h', 'r', 'e', 'e', '_'], 5052],
  [['m', 'i', 'l', 'l', 'i', 'o', 'n', '_'], 5031],
  [['c', 'a', 'l', 'l', '_'], 5012],
  [['t', 'h', 'i', 'r', 'd', '_'], 5006],
  [['g', 'e', 'n', 'e', 'r', 'a', 'l', '_'], 4996],
  [['c', 'l', 'e', 'a', 'r', 'l', 'y', '_'], 4987],
  [['o', 'p', 'i', 'n', 'i', 'o', 'n', '_'], 4960],
  [['e', 's', 's', 'e', 'n', 't', 'i', 'a', 'l', '_'], 4960],
  [['i', 'm', 'p', 'l', 'e', 'm', 'e', 'n', 't', 'a', 't', 'i', 'o', 'n', '_'],
   4957],
  [['e', 'u', 'r', '_'], 4951],
  [['s', 'p', 'e', 'c', 'i', 'f', 'i', 'c', '_'], 4917],
  [['f', 'i', 'n', 'd', '_'], 4909],
  [['r', 'e', 'a', 'l', 'l', 'y', '_'], 4880],
  [['d', 'e', 'm', 'o', 'c', 'r', 'a', 'c', 'y', '_'], 4872],
  [['a', 't', 't', 'e', 'n', 't', 'i', 'o', 'n', '_'], 4865],
  [['e', 'f', 'f', 'o', 'r', 't', 's', '_'], 4859],
  [['r', 'e', 's', 'p', 'o', 'n', 's', 'i', 'b', 'i', 'l', 'i', 't', 'y', '_'],
   4858],
  [['f', 'i', 'n', 'a', 'l', 'l', 'y', '_'], 4834],
  [['i', 'n', 't', 'e', 'r', 'n', 'a', 'l', '_'], 4829],
  [['g', 'o', '_'], 4761],
  [['f', 'e', 'w', '_'], 4757],
  [['i', 'm', 'p', 'a', 'c', 't', '_'], 4747],
  [['a', 'c', 'c', 'o', 'u', 'n', 't', '_'], 4740],
  [['a', 's', 'k', '_'], 4724],
  [['s', 'e', 'r', 'i', 'o', 'u', 's', '_'], 4724],
  [['w', 'o', 'r', 'k', 'e', 'r', 's', '_'], 4707],
  [['d', 'e', 'm', 'o', 'c', 'r', 'a', 't', 'i', 'c', '_'], 4701],
  [['s', 'u', 'b', 'j', 'e', 'c', 't', '_'], 4691],
  [['w', 'h', 'o', 'l', 'e', '_'], 4686],
  [['r', 'e', 'a', 'l', '_'], 4673],
  [['a', 'c', 'h', 'i', 'e', 'v', 'e', '_'], 4672],
  [['y', 'e', 't', '_'], 4671],
  [['d', 'i', 'd', '_'], 4654],
  [['m', 'a', 'j', 'o', 'r', '_'], 4647],
  [['b', 'e', 'c', 'o', 'm', 'e', '_'], 4637],
  [['a', 'l', 'l', 'o', 'w', '_'], 4636],
  [['e', 'n', 'v', 'i', 'r', 'o', 'n', 'm', 'e', 'n', 't', 'a', 'l', '_'],
   4631],
  [['s', 'o', 'c', 'i', 'e', 't', 'y', '_'], 4613],
  [['d', 'a', 't', 'a', '_'], 4581],
  [['o', 'n', 'c', 'e', '_'], 4564],
  [['p', 'r', 'e', 's', 'e', 'n', 't', '_'], 4552],
  [['e', 'd', 'u', 'c', 'a', 't', 'i', 'o', 'n', '_'], 4531],
  [['t', 'a', 'k', 'i', 'n', 'g', '_'], 4527],
  [['d', 'i', 'f', 'f', 'i', 'c', 'u', 'l', 't', '_'], 4518],
  [['q', 'u', 'a', 'l', 'i', 't', 'y', '_'], 4510],
  [['s', 't', 'a', 'n', 'd', 'a', 'r', 'd', 's', '_'], 4469],
  [['e', 'n', 'v', 'i', 'r', 'o', 'n', 'm', 'e', 'n', 't', '_'], 4461],
  [['s', 'o', 'm', 'e', 't', 'h', 'i', 'n', 'g', '_'], 4457],
  [['e', 'm', 'p', 'l', 'o', 'y', 'm', 'e', 'n', 't', '_'], 4457],
  [['i', 'n', 't', 'e', 'r', 'e', 's', 't', 's', '_'], 4437],
  [['s', 'i', 'n', 'g', 'l', 'e', '_'], 4432],
  [['r', 'u', 's', 's', 'i', 'a', '_'], 4424],
  [['r', 'e', 'g', 'i', 'o', 'n', 's', '_'], 4423],
  [['m', 'o', 'n', 'e', 'y', '_'], 4408],
  [['s', 't', 'e', 'p', '_'], 4380],
  [['r', 'e', 'a', 's', 'o', 'n', '_'], 4377],
  [['c', 'o', 'n', 's', 'u', 'm', 'e', 'r', 's', '_'], 4375],
  [['f', 'u', 'n', 'd', '_'], 4362],
  [['e', 'u', 'r', 'o', '_'], 4334],
  [['s', 'e', 'c', 'o', 'n', 'd', '_'], 4332],
  [['a', 'g', 'r', 'i', 'c', 'u', 'l', 't', 'u', 'r', 'a', 'l', '_'], 4289],
  [['s', 'o', 'l', 'i', 'd', 'a', 'r', 'i', 't', 'y', '_'], 4261],
  [['a', 'l', 'w', 'a', 'y', 's', '_'], 4249],
  [['e', 'a', 'c', 'h', '_'], 4232],
  [['r', 'e', 'g', 'i', 'o', 'n', 'a', 'l', '_'], 4224],
  [['w', 'i', 's', 'h', '_'], 4217],
  [['l', 'e', 'a', 's', 't', '_'], 4206],
  [['l', 'a', 'r', 'g', 'e', '_'], 4206],
  [['g', 'e', 't', '_'], 4203],
  [['p', 'r', 'i', 'n', 'c', 'i', 'p', 'l', 'e', '_'], 4199],
  [['j', 'o', 'b', 's', '_'], 4178],
  [['a', 'g', 'r', 'e', 'e', 'm', 'e', 'n', 't', 's', '_'], 4171],
  [['p', 'o', 's', 'i', 't', 'i', 'v', 'e', '_'], 4162],
  [['l', 'o', 'o', 'k', '_'], 4145],
  [['p', 'r', 'o', 'd', 'u', 'c', 't', 'i', 'o', 'n', '_'], 4126],
  [['p', 'o', 'w', 'e', 'r', '_'], 4114],
  [['i', 'n', 'd', 'e', 'e', 'd', '_'], 4077],
  [['p', 'r', 'o', 'p', 'o', 's', 'e', 'd', '_'], 4065],
  [['c', 'o', 'm', 'p', 'a', 'n', 'i', 'e', 's', '_'], 4050],
  [['b', 'e', 's', 't', '_'], 4046],
  [['h', 'a', 'v', 'i', 'n', 'g', '_'], 4045],
  [['f', 'u', 'l', 'l', 'y', '_'], 4043],
  [['i', 'm', 'p', 'r', 'o', 'v', 'e', '_'], 4036],
  [['r', 'e', 'c', 'e', 'n', 't', '_'], 4032],
  [['t', 'h', 'i', 'n', 'g', 's', '_'], 4031],
  [['c', 'o', 'n', 'c', 'e', 'r', 'n', 'e', 'd', '_'], 4020],
  [['l', 'i', 'f', 'e', '_'], 4003],
  [['v', 'a', 'r', 'i', 'o', 'u', 's', '_'], 3991],
  [['/', '_'], 3974],
  [['i', 't', 's', 'e', 'l', 'f', '_'], 3973],
  [['r', 'e', 'l', 'a', 't', 'i', 'o', 'n', 's', '_'], 3972],
  [['p', 'l', 'a', 'n', '_'], 3969],
  [['f', 'o', 'r', 'c', 'e', '_'], 3963],
  [['h', 'a', 'n', 'd', '_'], 3955],
  [['f', 'u', 'l', 'l', '_'], 3954],
  [['d', 'o', 'w', 'n', '_'], 3951],

In [269]:
tokenizer_eng = BPE_tokenizer.BPETokenizer(vocab_chars_eng, pair_vocab_eng, 12000, False)
tokenizer_pol = BPE_tokenizer.BPETokenizer(vocab_chars_pol, pair_vocab_pol, 24000, True)

In [273]:
tokenizer_eng.train_bpe()

  0%|          | 0/11945 [00:00<?, ?it/s]

In [274]:
tokenizer_pol.train_bpe()

  0%|          | 0/23935 [00:00<?, ?it/s]

In [45]:
encoder_eng = BPEEncoder(tokenizer_eng.vocab)
encoder_pol = BPEEncoder(tokenizer_pol.vocab, 65, True)

In [6]:
df_europarl.head()

,eng_text,pol_text,eng_split,pol_split,eng_ids
0,Action taken on Parliament's resolutions: see ...,Działania podjęte w wyniku rezolucji Parlament...,"[action, taken, on, parliament, 's, resolution...","[działania, podjęte, w, wyniku, rezolucji, par...","[771, 909, 73, 326, 258, 3994, 434, 790, 1791, 2]"
1,Documents received: see Minutes,Składanie dokumentów: patrz protokół,"[documents, received, :, see, minutes]","[składanie, dokumentów, :, patrz, protokół]","[2769, 2649, 434, 790, 1791, 2]"
2,Texts of agreements forwarded by the Council: ...,Teksty porozumień przekazane przez Radę: patrz...,"[texts, of, agreements, forwarded, by, the, co...","[teksty, porozumień, przekazane, przez, radę, ...","[4207, 78, 1458, 9696, 201, 61, 429, 434, 790,..."
3,Membership of Parliament: see Minutes,Skład Parlamentu: patrz protokół,"[membership, of, parliament, :, see, minutes]","[skład, parlamentu, :, patrz, protokół]","[3303, 78, 326, 434, 790, 1791, 2]"
4,Membership of committees and delegations: see ...,Skład komisji i delegacji: patrz protokół,"[membership, of, committees, and, delegations,...","[skład, komisji, i, delegacji, :, patrz, proto...","[3303, 78, 3853, 81, 5881, 434, 790, 1791, 2]"

In [42]:
from tqdm.auto import tqdm
tqdm.pandas()

In [47]:
df_2 = df_europarl[['pol_text', 'pol_split']].copy()
df_2['pol_ids'] = df_2['pol_text'].progress_apply(encoder_pol.encode_snt)

  0%|          | 0/576824 [00:00<?, ?it/s]

In [48]:
with open("../data/dataframe_pol_europarl.pkl", 'wb') as f:
    pickle.dump(df_2, f)

In [3]:
with open("../data/tokenizer_eng_2.pkl", 'rb') as f:
    tokenizer_eng = pickle.load(f)

with open("../data/tokenizer_pol_2.pkl", 'rb') as f:
    tokenizer_pol = pickle.load(f)

with open("../data/dataframe_europarl.pkl", 'rb') as f:
    df_europarl = pickle.load(f)

In [49]:
with open("../data/tokenizer_eng_2.pkl", 'wb') as f:
    pickle.dump(tokenizer_eng, f)

with open("../data/tokenizer_pol_2.pkl", 'wb') as f:
    pickle.dump(tokenizer_pol, f)

In [50]:
with open("../data/dataframe_europarl.pkl", 'wb') as f:
    pickle.dump(df_europarl, f)